### PR TITLE
[#1300] Add to My Resources button bug fix

### PR DESCRIPTION
**Pull request by mauriel133**
Fixes issue described in #1300

### CODE REVIEW

**Comment by pkdash** [comment]
@mauriel133 Ignore this check failure. It's a known failure that's happening with all PRs.

**Comment by pkdash** [comment]
@zhiyuli can you review this?

**Comment by zhiyuli** [comment]
+1

**Comment by pkdash** [comment]
@mauriel133 Are you available to merge this?

**Pull request merged**
