### PR TITLE
pull fix from develop to master to get ready for hotfix release

### PR DESCRIPTION
**Pull request by hyi**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by hyi** [comment]
@aphelionz This PR pulls iRODS account creation get_or_create fix from develop to master to get ready for hotfix release 1.15.5. Please take a look and approve if it looks good to you. I'll then merge it once it passes tests.

**Comment by sblack-usu** [comment]
What sparked this?  Is this a new issue?

**Comment by aphelionz** [comment]
Found it: https://github.com/hydroshare/hydroshare/issues/2816

**Comment by dtarb** [comment]
Connecting this to ongoing discussions about upgrade scheduling and notifications, I am worried that adding more and more to hotfixes is not efficient use of team time.  It may be more productive and time efficient to get the code already merged into develop deployed following a systematic (i.e. not hotfix) deployment process.

**Comment by aphelionz** [comment]
@dtarb This isn't just a gratuitous cramming in -

**Comment by hyi** [comment]
@aphelionz Feel free to merge it when Jenkins check is complete to get it in for hotfix release. For some reason, it has been pending for a long time. Not sure whether there could be issues on Jenkins side or the waiting queue is just too long.

**Comment by sblack-usu** [comment]
It was held up by my PR to merge develop into the composite resource branch.... It's been timing out at 3 hours.  I think it's just something to do with that branch so yours should come through.  I've extended the timeout to 4 hours to see if the tests really are just taking over 3 hours in the composite resource branch or not.

**Pull request merged**
