### PR TITLE
[WIP] Add OAuth to REST API

### PR DESCRIPTION
**Pull request by selimnairb**
Enable OAuth2 support for REST API.  Also adds GET /hsapi/userInfo/ end point for use by HydroShare OAuth clients.

### CODE REVIEW

**Comment by selimnairb** [comment]
@ironfroggy Can you deploy this on the playground so that @zhiyuli et al. can test the /hsapi/userInfo/ end point with Tethys?

**Comment by mjstealey** [comment]
> @ironfroggy Can you deploy this on the playground so that @zhiyuli et al. can test the /hsapi/userInfo/ end point with Tethys?

@selimnairb, @ironfroggy - Actually if you wouldn't mind this may be good practice for @hyi to deploy on playground. She'll be taking over the DevOps roll along with @rayi113 while I'm out on paternity leave.

**Comment by selimnairb** [comment]
@mjstealey @hyi Sounds good to me.

**Comment by mjstealey** [comment]
@selimnairb - was this ready to be merged? Still has [WIP] in title...

@hyi - I think they just wanted it deployed on playground, and not necessarily merged into the develop branch just yet

**Comment by hyi** [comment]
@mjstealey @selimnairb The PR is against the oauth-server branch, not against develop branch, so I merged it so that I can deploy the oauth-server branch to playground. Let me know if this is not intended.

**Comment by mjstealey** [comment]
> PR is against the oauth-server branch

@hyi - yep, my bad, roll with it! :+1:

**Comment by selimnairb** [comment]
@mjstealey @hyi This isn't ready to be merged into develop, but it may be close.  I wanted @zhiyuli to be able to test the Tethys code against this code running on the play pen.  Merging into the oauth-server branch is okay by me.

**Comment by hyi** [comment]
@selimnairb @zhiyuli @robline @ironfroggy @mjstealey I have deployed the merged branch oauth-server to playground. Please test and see whether things are working as expected.

**Pull request merged**
