### PR TITLE
[#4802] check for periodic tasks = disabled

### LINKED ISSUE #4802: celery workers fail to deregister periodic tasks
**Description of the bug**
We have 2 workers. When we run a worker swap via Jenkins, (AFAIK) we don't have any process that prevents the inactive worker from continuing to run Celery jobs. That's good for `@shared_task` testing of the inactive worker but [@periodic_tasks ](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/tasks.py#L102) continue to run on their cron schedule which is causing duplicate metadata deposit with crossref in addition to potentially creating other issues.

Steps to reproduce the bug:
Take a look at the Flower pages for both workers currently used in production. You will see that they are duplicating periodic tasks.

**Expected behavior**
Periodic tasks should be disabled on the inactive worker

**Additional information**
Related to #4795 

Examples of crossref records that show this issue:
https://doi.crossref.org/servlet/submissionAdmin?sf=detail&submissionID=1543730248
https://doi.crossref.org/servlet/submissionAdmin?sf=detail&submissionID=1543730247

### PR DESCRIPTION
**Pull request by devincowan**
In conjunction with https://github.com/hydroshare/hs-deployment/commit/a81aae94fd32d8939e1dd42c568cc3f44726239e, Resolves #4802 

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
I've updated our Jenkins Job on beta swap so that we can test this
https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Beta%20deployment/job/beta-swap-worker/configure

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4803](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4803)

**Comment by devincowan** [comment]
Making a note confirming that the Jenkins swap on beta works as expected, toggling the DISABLE_PERIODIC_TASKS setting appropriately for active/inactive workers

**Comment by devincowan** [comment]
@sblack-usu I removed the deprecated @periodic_tasks decorator as you suggested and consolidated registering the periodic tasks so that we only have to check the `DISABLE_PERIODIC_TASKS` setting once.

Does this look better?
If preferable, rather than adding this new setting, we could:

1. change our [init-defaultworker](https://github.com/hydroshare/hydroshare/blob/4802-periodic-tasks/scripts/templates/init-defaultworker.template) script so that it doesn't call `celery beat`,
2. Create a new hsctl command that runs `celery beat`
3. Modify our Jenkins swap job so that it calls the new hsctl command on the active worker during swap

**Comment by sblack-usu** [comment]
Looks great, thanks for the updates. It is nice how all the cron tab schedules are consolidated to one place and the settings check only happens once.

**Review by sblack-usu — APPROVED** [review]

**Comment by devincowan** [comment]
Thanks for pushing me to do better!

**Pull request merged**
