### PR TITLE
[#3243] Add response data during file upload to handle metadata status changes

### PR DESCRIPTION
**Pull request by Maurier**
[#3243] This PR extends the logic used to render metadata status changes of resource landing page to functionality regarding file uploads.

Note that the duration of the message has been incremented to 8 seconds (up from 3 seconds) to allow the message to be read.

A close icon ("x") has been added to the top right of this message to dismiss it.

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Create a new resource.
2. Add a Title, Abstract and Keywords.
3. Add some content files.
4. At this point the metadata status message should appear indicating that the resource can be made Public.

### CODE REVIEW

**Comment by sblack-usu** [comment]
Cool, thanks for picking this one up.

**Comment by Maurier** [comment]
@sblack-usu - Good catch, I forgot to add the rest of the logic to update the buttons. I have done so no. Please have another look when you get a chance.

The time this message appears was incremented from 3 seconds to 8 seconds. Based on my judgment, three seconds wasn't enough time for reading this message. But since this message now stays longer, it was not immediately obvious that it would go away. And that is way the progress bar was added.

**Comment by sblack-usu** [comment]
@Maurier - I'm approving the change functionally... I think it's worth passing the progress bar change by someone like @Lizabrazil.  It is introducing a new user feedback mechanic.

**Comment by Lizabrazil** [comment]
@Maurier @sblack-usu I think we should try to avoid introducing UI elements that are not consistent throughout the website. If a user see this and notices it, they would expect that it to show up on other pop ups on the website. Also, progress bar usually indicates that something is happening and in this it is not in progress of an action. I'd say either keep the increased time and remove the bar or just make it a pop up that has to be exited out of. We have the banner up top for when they create a resource about adding keywords, etc. So this pop up is just an additional important reminder.

**Comment by Maurier** [comment]
@Lizabrazil, @sblack-usu - Understood, I have removed the progress bar indicator from the message. This looks exactly as before except for the increased timer in order to be able to read the message.

**Comment by sblack-usu** [comment]
@Maurier - Could you add an x in the top right corner of the popup so the user can close it like?

**Comment by Maurier** [comment]
@sblack-usu - I have added the button. Please have another look when you get a chance.

**Pull request merged**
