### PR TITLE
[#3110] Resource Landing Page - Minor fixes

### PR DESCRIPTION
**Pull request by Maurier**
### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by Maurier** [comment]
retest this, please

**Comment by cuahsimarko** [comment]
Apologies for including Martin Hunt, when Martin Seul was intended.

**Comment by Maurier** [comment]
This PR includes fixes for issues identified in #3111 

I will list them below:

Spacing:
image

Empty menu section:
image

Button css missing:
image

**Comment by cuahsimarko** [comment]
@Maurier can you resolve conflicts

**Comment by cuahsimarko** [comment]
Then I will deploy locally and test UI

**Comment by Maurier** [comment]
I will be solving some recent merge conflicts.

**Pull request merged**
