### PR TITLE
HOTFIX-Ensures generic logical file is created when a file gets added

### PR DESCRIPTION
**Pull request by pkdash**
If multiple files are added to the composite and one of the files does not get added for some reason (e.g., duplicate file name) then the system was failing to create a generic file for each of the files that got added. This may be one of the reasons why we have seen missing logical files that lead to no files being listed on the UI.

### CODE REVIEW

**Comment by pkdash** [comment]
@alvacouch Can you review this hotfix PR?

**Comment by hydrobuild** [comment]
Build finished.

**Comment by pkdash** [comment]
@alvacouch  Will fix those failing tests by end of the day.

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
