### PR TITLE
HOTFIX-1.15-RC1-fix for author optional identifier xml encoding

### PR DESCRIPTION
**Pull request by pkdash**

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by pkdash** [comment]
@aphelionz This PR is now ready for review.

**Comment by pkdash** [comment]
@aphelionz No, I have not deployed it. Feel free to deploy and test. Thanks.

**Comment by aphelionz** [comment]
@Maurier Can you put this on riverdev? I see you have it reserved in https://github.com/hydroshare/hydroshare/issues/898

**Comment by Maurier** [comment]
@aphelionz sure

**Comment by aphelionz** [comment]
@Maurier Thank you!

**Comment by Maurier** [comment]
This can now be tested at https://riverdev.hydroshare.org

**Comment by Maurier** [comment]
@pkdash, I might need to clean the script a little now that we don't need functionality for the 'Other' dropdown option.

**Comment by pkdash** [comment]
@Maurier Sounds good.

**Comment by aphelionz** [comment]
@Maurier @pkdash Looks good functionality-wise.  +1 from me

**Comment by aphelionz** [comment]
@pkdash roger that

**Comment by horsburgh** [comment]
@Maurier - I tried to have a look on riverdev, but I don't think I have an account and I couldn't create one because the recaptcha isn't working.

**Comment by aphelionz** [comment]
@Maurier I *just* updated beta to fix captcha. Like, just now. Please try again.

**Comment by Maurier** [comment]
@aphelionz, this code is only deployed on riverdev, but we currently don't have a way to deploy with a copy of the database. In order for @horsburgh to test he would need to use the default account or wait until this makes it into the release candidate on beta.

**Comment by aphelionz** [comment]
ah, ok... sorry about that

**Comment by hydrobuild** [comment]
Build finished.

**Comment by pkdash** [comment]
@cbcunc Any idea what's causing this build failure?

**Comment by aphelionz** [comment]
jenkins retest this

**Comment by aphelionz** [comment]
retest

**Comment by aphelionz** [comment]
retest this please

**Comment by aphelionz** [comment]
bingo!

**Comment by hydrobuild** [comment]
Build finished.

**Comment by pkdash** [comment]
@aphelionz Not sure if this can be merged.

**Comment by aphelionz** [comment]
@potash why?

**Comment by pkdash** [comment]
@aphelionz I was checking if you are ok with me merging as there has been some code changes after you approved it.

**Comment by aphelionz** [comment]
@pkdash Ah, ok. The code changes are minimal... I'm ok with merging it. If there are problems we can sort them out.

**Pull request merged**
