### PR TITLE
Add sendfile chunks and aio threads to global scope

### PR DESCRIPTION
**Pull request by sblack-usu**
### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW SECURITY HOTSPOTS | 0 |
| NEW CODE SMELLS | 0 |
| NEW VULNERABILITIES | 0 |
| NEW BUGS | 0 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-3979](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-3979)

**Review by alvacouch — CHANGES_REQUESTED** [review]
You also need this in hydroshare-nginx.conf.template for development purposes. Development is sometines done without ssl.

**Comment by alvacouch** [comment]
There are two ways to play this: 

1. Make the ssl and non-ssl versions identical. 
2. Strip all large file support from the non-ssl version.

**Review by alvacouch — APPROVED** [review]
Approved. We can think about the best content for the non-ssl version (for development only) later.

**Pull request merged**
