### PR TITLE
[#2653] update the create resource help page

### PR DESCRIPTION
**Pull request by sblack-usu**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Sign in -> Click Create Resource -> Click the link in the top blue message box "When you click Create Resource, the files will be uploaded to the HydroShare server. Click here to learn more about next steps to share and formally publish your data."  Validate the link takes you to "https://help.hydroshare.org/creating-and-managing-resources/formally-publishing-data/"

### CODE REVIEW

**Comment by sblack-usu** [comment]
No automated tests around this as it's just an updated link in the url.  The previous link returned a 404, so I don't think there is any update to documentation necessary... it just links to the correct page now.  Thumbs up this message if you agree.

**Comment by aphelionz** [comment]
@sblack-usu Agreed in regards to automated testing. I bet @Lizabrazil will green light this fairly quickly as well since it's fixing something important and shouldn't require any user doc updates.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by Lizabrazil** [comment]
I'm not sure this makes sense. That webpage is specific to formally publishing a resource and doesn't cover "sharing." Let's change to the below. 
"Click Create Resource to upload your files and edit associated metadata. Click [here](https://help.hydroshare.org/creating-and-managing-resources/) for more information. "

**Comment by Lizabrazil** [comment]
Sorry this:
"Click Create Resource to upload your files and edit associated metadata. For more information, click [here](https://help.hydroshare.org/creating-and-managing-resources/). "

**Comment by sblack-usu** [comment]
I used the url @dtarb provided in #2653.  I'll run it by him in case he has reason for the url he provided over the one you're linking now.

**Comment by Lizabrazil** [comment]
Ok, thanks. I think it was probably just handed down text and URL but since i have the chance now to clarify the text and provide the right webpage, thought i'd bring it up.

**Comment by sblack-usu** [comment]
Speaking to @dtarb.  He suggests a shorter message: "Click create resource to upload your files.  For more information click here."

**Comment by Lizabrazil** [comment]
That's fine.

**Comment by sblack-usu** [comment]
Pretty cool that github will let you update a file in the browser.

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
