### PR TITLE
Adding blank issue and pull request templates

### PR DESCRIPTION
**Pull request by aphelionz**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Review the text of this pull request description and let me know if you think this will work. If this PR is approved, the text will be auto-inserted.

Note that I'm not I'm not necessarily writing an ISSUE template right now.

### CODE REVIEW

**Comment by aphelionz** [comment]
I don't see a need for writing new automated tests for this.

**Comment by sblack-usu** [comment]
The only thing I can think of is a pretty small nit pick, but it looks like you can add the .md file extension to this file and it'll still work... it's just a bit more descriptive that way, but not a big deal either way.

**Comment by aphelionz** [comment]
@sblack-usu Thanks, please re-approve :)

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@Lizabrazil has decided that no user documentation is necessary here. This in and of itself *is* developer documentation, so I think it's self-sufficient.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by pkdash** [comment]
Is developer documentation in addition to doc strings? If so where this type of documentation would live and if we have guidelines/template for writing such documentation?

**Comment by aphelionz** [comment]
@pkdash good question - this is something that's been coming up on development calls. Currently we are docstring only which gives us the ability to work within readthedocs and swagger easily. From there, we will branch out but it will all live in the code.

Additionally, over the next year or so I'll be asking devs to write README.md files at the root of each django app, but we're not quite there yet.

**Comment by pkdash** [comment]
@aphelionz Sounds good.

**Comment by sblack-usu** [comment]
This has been in use since it was merged into develop.  It's been working correctly and I'm marking it as verified in the RC

**Pull request merged**
