### PR TITLE
[#2696] add default reCAPTCHA test keys and site url

### PR DESCRIPTION
**Pull request by sblack-usu**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Deploy hydroshare locally and navigate to the signup page. Validate that captcha works. There will also be little red text that says "This reCAPTCHA is for testing purposes only. Please report to the site admin if you are seeing this"

### CODE REVIEW

**Comment by sblack-usu** [comment]
Resubmitting PR 2704 against develop

**Comment by sblack-usu** [comment]
@hyi - mind approving this PR again?

**Comment by aphelionz** [comment]
Thanks @sblack-usu

**Comment by hydrobuild** [comment]
Build finished.

**Comment by sblack-usu** [comment]
test this

**Comment by sblack-usu** [comment]
@aphelionz, what's the command to tell Jenkins PR bot to kick off another job?

**Comment by aphelionz** [comment]
@sblack-usu "retest this please"

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by sblack-usu** [comment]
Thanks, I ended up closing it and reopening it to kick off the job.  I'm glad we're enforcing good manners when interacting with the bot.  Perhaps skynet will remember, when it goes online.

**Pull request merged**
