### PR TITLE
update id of radio button to delete box type resource

### PR DESCRIPTION
**Pull request by soumyapurohit**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Edit a resource with a box type and ensure the delete icon is available when the spatial coverage is box type.

### CODE REVIEW

**Review by hyi — APPROVED** [review]
@soumyapurohit I am approving the PR, but also want @sblack-usu or @cuahsimarko to take a quick look as well. @sblack-usu or @cuahsimarko Please take a quick look (one line change) when you have a chance to see if the fix looks good to you as well.

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW SECURITY HOTSPOTS | 0 |
| NEW BUGS | 0 |
| NEW DUPLICATED LINES DENSITY | 0.809716599190283 |
| NEW VULNERABILITIES | 0 |
| NEW CODE SMELLS | 1 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4185](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4185)

**Review by sblack-usu — APPROVED** [review]
I really don't like the name id_type_1, but it may break other functionality if we change it.  I ran this locally and it works.

**Comment by sblack-usu** [comment]
This searches the whole document for the div id id_type_1, this should be fine because ids should be unique.

**Pull request merged**
