### PR TITLE
[WIP][#3136] Move Copy Resource Bag button to file browser's toolbar

### PR DESCRIPTION
**Pull request by Maurier**
As described in #3136:
image

**After:**
----------------
image

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by cuahsimarko** [comment]
Toolbar starting to get crowded. Maybe consider allowing user to toggle words or consider breaking into two categories with a text label for each category of operation. The typical ~1 sec delay on hover doesn't help until you use it enough to memorize the buttons. Many are very intuitive, but sometimes forget.

**Comment by pkdash** [comment]
@Maurier Are you planning to implement suggestion by @cuahsimarko? as part of this PR? I would prefer  that to be implement as a new issue. If you are not planning to make any changes to this PR I can review it today.

**Comment by Maurier** [comment]
@pkdash - Let's wait a little on this until the discussion on https://github.com/hydroshare/hydroshare/issues/3136 wraps up. I'll mark this as WIP in the meantime.

**Comment by cuahsimarko** [comment]
@Maurier Based on a recent conversation, I retract my comment. David can confirm and loop in Jeff, but my understanding is that we can iterate on this, using the iRODS button David suggested in the related PR.

**Comment by dtarb** [comment]
@cuahsimarko @Maurier I confirm that there was agreement at a recent meeting to not at this stage consider hamburger menu.  Any change in overall structure needs to be deferred.  This PR should be completed and merged and deployed using a button based on the iRODS icon shown in #3136.  A redrawing of this icon may be needed to be consistent with our styles colors and icon sizes.

**Comment by sblack-usu** [comment]
Approving and merging to get this deployed to Beta with 1.20.  @Maurier will have an iRODS icon ready on Monday, we can point to the new icon when it's ready.

**Pull request merged**
