### PR TITLE
Keywords editing improvements

### PR DESCRIPTION
**Pull request by pkdash**
This work involves:
- Prevent duplicate keywords
- Allow deleting all keywords (If all keywords are deleted, then the resource gets set to private by the system)

### CODE REVIEW

**Comment by pkdash** [comment]
@zhiyuli Recently you reviewed a similar PR to fix duplicate keywords. This PR seems to fix that problem. Can you review it?

**Comment by zhiyuli** [comment]
@pkdash The changes look good to me. I have one question: are the UI and rest api sharing the same backend regarding this keyword metadata? Do your changes also work for rest api?

**Comment by pkdash** [comment]
@zhiyuli 

> I have one question: are the UI and rest api sharing the same backend regarding this keyword metadata? Do your changes also work for rest api?

That's a good question. The most of the logic for UI support is in the view function. So the rest api and UI not really use the same backend code. I will make change to the backend code so that duplicate keywords are not created. For UI this PR implemented deleting all keywords - I am not sure how we implement that as part of the REST api.

**Comment by pkdash** [comment]
@zhiyuli I have now updated the ```create()``` function of the ```Subject``` metadata element class to prevent adding duplicate keywords. That means it should not be possible to add duplicate keywords using the REST endpoint.

**Comment by zhiyuli** [comment]
+1

**Pull request merged**
