### PR TITLE
[#942] Enhance metadata editing

### PR DESCRIPTION
**Pull request by mauriel133**
Added descriptive text on some metadata elements.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@mauriel133 You can merge this.

**Comment by pkdash** [comment]
@mauriel133 You need to update this with latest develop which is based on Django 1.8.9 before merging.

**Comment by pkdash** [comment]
@mauriel133 You should merge this.

**Pull request merged**
