### PR TITLE
HOTFIX - add ResourceFile indexes and get size off of directory listing

### PR DESCRIPTION
**Pull request by sblack-usu**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Load a resource page with 1000 files in the current file browser directory.  If it does not timeout, you're golden.

### CODE REVIEW

**Comment by sblack-usu** [comment]
django_irods master has diverged from the hydroshare master because of the current state of releases.  I'm just going to include the commit to review here instead of adding a PR in django_irods for now.
https://github.com/hydroshare/django_irods/commit/813bef64ac04d9ca86482fff1b9487b084df385b

**Comment by hyi** [comment]
@sblack-usu @aphelionz I took a quick look and left one comment related to code in django_irods.  Otherwise, everything looks good to me. @alvacouch was assigned as a reviewer and will need to take a quick look as well.

**Comment by sblack-usu** [comment]
I pushed the change addressing @hyi's comment

**Comment by sblack-usu** [comment]
Now part of https://github.com/hydroshare/hydroshare/pull/2889

**Pull request closed without merging**
