### PR TITLE
2408 missing constraint in web app models.py

### PR DESCRIPTION
**Pull request by zhiyuli**
This pr was to address issue #2408. It added two unique constraints for two metadata element classes in models.py.
A pre-check on www data has been performed indicated no duplicated instances of the two classes got created.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
This is odd - this just popped up in my other branch

image

**Comment by zhiyuli** [comment]
@aphelionz 
I can see the errors after running "docker exec -ti hydroshare ./run-pylint" locally. It is odd pylint goes to check .git folder. I guess something went wrong with my local env.
I will close this PR and re-create new branch.

**Comment by zhiyuli** [comment]
A new PR will replace this

**Pull request closed without merging**
