### PR TITLE
[#2048][#74][Hotfix] Create Resource page enhancements

### PR DESCRIPTION
**Pull request by mauriel133**
- Added dropdown indicator to Select Resource button
- Added help text indicating file upload functionality. This help text goes away when files are selected.
- Code cleanup and refactor.

image

### CODE REVIEW

**Comment by pkdash** [comment]
@mauriel133 From which branch you created this hotfix branch?

**Comment by mauriel133** [comment]
This was created from the develop branch so it is targeting the develop branch. After this gets approved and merged I will create another PR based on the release candidate and targeting it.

**Comment by pkdash** [comment]
@mauriel133 I guess I am confused. So you will be doing the same work twice?

**Comment by pkdash** [comment]
All hotfixes for release 1.10 has to be off of release-candidate-1.10.0 branch.

**Comment by mauriel133** [comment]
Shouldn't we get these changes in both develop and release candidate branches?

**Comment by pkdash** [comment]
@mauriel133 
The hotfix for a release branch works like this:
1. Create branch off of the release-candidate branch
2. Create a PR for that branch pointing (based to) release-candidate
3. Merge PR to release candidate (Michael will do that)
4. Michael then merges release-candidate to develop

**Comment by mauriel133** [comment]
I see. I'll close this one and create another based on the release candidate.

**Pull request closed without merging**
