### PR TITLE
Swagger needs these to be explicit lists

### PR DESCRIPTION
**Pull request by aphelionz**

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
This passed a jenkins re-run: http://ci.hydroshare.org:8080/job/hydroshare-pull-requests/1311/

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@alvacouch as suspected, it was just the build server. Can you approve?

**Comment by aphelionz** [comment]
@pkdash Can you give this a quick review when you have a chance?

**Pull request merged**
