### PR TITLE
1822 failed to create refts

### PR DESCRIPTION
**Pull request by zhiyuli**
1) add a missing parameter to get_xml() in ref_ts code
2) remove unused parameter in create_bag_by_irods() in django_irods submodule (see #1822 pr at django_irods).

### CODE REVIEW

**Comment by zhiyuli** [comment]
@hyi @pkdash 
This PR is a quick fix to Ref_TS code. A bug in django_irods was found in manual testing and fixed as well. Please review this PR as well as the corresponding PR in django_irods repo.  Thanks

**Comment by pkdash** [comment]
@zhiyuli Did you test if the xml metadata file is getting generated correctly?

**Comment by zhiyuli** [comment]
@pkdash 
I visually inspected the xml and it looked good.

**Comment by pkdash** [comment]
@zhiyuli Yeah we can do visual inspection only at this point as we don't have unit tests to check the contents of the xml file. +1. Merge once Jenkin checks are successful.

**Comment by hyi** [comment]
This looks good to me. +1. @zhiyuli Just make sure you merge django_irods first, then update django_irods SHA reference before merging this PR. You may also wait for @pkdash's approval on this PR.

**Pull request merged**
