### PR TITLE
[2215] Text clarifications and helpful messages

### PR DESCRIPTION
**Pull request by Maurier**

### CODE REVIEW

**Comment by pkdash** [comment]
@Maurier Which release this PR targets?

**Comment by Maurier** [comment]
This PR and #2107 could be included in release 1.12.0

Otherwise it could wait for the next one.

**Comment by pkdash** [comment]
@Castronova Can you review this as you seems to have requested these changes?

**Comment by pkdash** [comment]
@Castronova can you review this small PR so that it can be part of next release?

**Comment by Maurier** [comment]
@Castronova, have you had a chance to review this?

**Comment by aphelionz** [comment]
@Maurier I have approved! Please merge.

**Pull request merged**
