### PR TITLE
[#1666] point to latest django irods

### PR DESCRIPTION
**Pull request by sblack-usu**
This merge rolled back django_irods commit unintentionally https://github.com/hydroshare/hydroshare/commit/2afa79bcd35de2ca6238bc6d6d47f4867533882c

Fixing it to point to latest commit here.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hyi** [comment]
@sblack-usu @aphelionz Looks like Jenkins had build issues which has nothing to do with this PR. I am pretty sure this PR can be safely merged to bring django_irods to its latest SHA reference in master branch.

**Comment by aphelionz** [comment]
Jenkins, test this

**Comment by aphelionz** [comment]
test this please

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hyi** [comment]
@aphelionz Jenkins was not happy for this PR for some reason, however, this PR https://github.com/hydroshare/hydroshare/pull/2620 passed Jenkins test, and if merged, will fix django_irods issue on develop branch as well. So if the plan is to merge PR https://github.com/hydroshare/hydroshare/pull/2620, this PR that Jenkins was not happy about can be closed.

**Pull request closed without merging**
