### PR TITLE
New resource type icons

### PR DESCRIPTION
**Pull request by mauriel133**
Generic:
generic48x48
Multidimensional:
multidimensional48x48
Time Series:
timeseries48x48
HIS Referenced Time Series:
his48x48
Web App:
webapp48x48
Geographic Feature:
geographicfeature48x48
Geographic Raster:
geographicraster48x48
Model Instance:
modelinstance48x48
SWAT Model Instance:
swat48x48

Model Program:
modelprogram48x48 pmg

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by hyi** [comment]
@mauriel133 These new icons really look great! Please bring the branch up to date with latest develop to make it ready to merge, then I will merge it.

**Comment by mauriel133** [comment]
Good catch, forgot to add it. I will add it soon.

**Comment by mauriel133** [comment]
Done.

**Pull request merged**
