### PR TITLE
Rc2.14-fix -> develop

### PR DESCRIPTION
**Pull request by devincowan**
This reverts commit 1f9b9ef74986988f2eee10cfce0b52e1762cfc9b.

Something about the way that django squashed the migrations was causing SOLR to fail during indexing.
See https://github.com/hydroshare/hydroshare/issues/5332#issuecomment-2123616943

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by pkdash** [comment]
@devincowan Is `rc2.14-fix` now running on prod?

**Comment by devincowan** [comment]
@pkdash thanks for checking
NO
my intent is to release this `rc2.14-fix` as 2.14.1.
This oddity is because 2.14 had already been tagged but then failed to release.

**Comment by pkdash** [comment]
> @pkdash thanks for checking NO my intent is to release this `rc2.14-fix` as 2.14.1. This oddity is because 2.14 had already been tagged but then failed to release. This pr [5488](https://github.com/hydroshare/hydroshare/pull/5488) is to merge the fix to develop so that local builds aren't off in the meantime

Just curious to know where you then seeing the SOLR to fail during the indexing. Is it failing on prod?

**Comment by devincowan** [comment]
Yes didn't fail locally and also didn't fail during my first deployment of rc-2.14.
However after a data update on beta and then re-attempted deploy of rc-2.14 to beta, it did reproducibly fail

**Review by pkdash — APPROVED** [review]

**Pull request merged**
