### PR TITLE
responsive breakpoints for app tiles

### LINKED ISSUE #4559: app tiles should have different responsive preakpoints
**Describe the feature you'd like and what it will do**
For screens <1000px wide, the apps page shows only one app tile per row. This leaves a bunch of dead whitespace.
We should be able to fit two tiles and only scale to one tile when the screen width is smaller
app

**Additional context**
Believe this change can be made in the boostrap column classes in [THIS TEMPLATE](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/apps.html#L29)

### PR DESCRIPTION
**Pull request by devincowan**
Resolves #4559

### Pull Request Checklist: 
- [X] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Navigate to the Apps Library (if on dev machine, make sure to type `[hostname]/apps/ ` in the URL because clicking on "apps" navigation will take you to production www.hydroshare.org)
2. Reduce your screen width to between 768px-1000px
3. There are now 2 columns of apps instead of 1

***
#### Before
image

#### After
Screen Shot 2022-03-31 at 8 29 14 AM

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4574](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4574)

**Review by Maurier — CHANGES_REQUESTED** [review]
I think bootstraps responsive breakpoints produces weird results for various screen sizes.
image
A better solution would make use of CSS grid. For example, we can remove the bootstrap implementation and directly target the `apps-container` with this:
`  
 display: grid;
 grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 1rem;
`

This will simplify the implementation a lot and give us a grid that is responsive to any screen size.

**Comment by devincowan** [comment]
thanks @Maurier good suggestion, the CSS grid is indeed a much nicer implementation!

**Review by Maurier — APPROVED** [review]
Looks good.

**Pull request merged**
