### PR TITLE
4357 Outdated legend

### PR DESCRIPTION
**Pull request by Maurier**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

Update content and layout of legend

image

### Positive Test Case
1. Go to My Resources page
2. Expand the Legend panel
3. Verify that the legend is accurate as described in #4357

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW VULNERABILITIES | 0 |
| NEW DUPLICATED LINES DENSITY | 0.0 |
| NEW CODE SMELLS | 0 |
| NEW SECURITY HOTSPOTS | 0 |
| NEW BUGS | 0 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4409](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4409)

**Review by pkdash — COMMENTED** [review]
The legend for File Set kind of doesn't match with the size of other legends for content types. Can we have border/box around file set legend similar to others?
image

**Comment by Maurier** [comment]
> The legend for File Set kind of doesn't match with the size of other legends for content types. Can we have border/box around file set legend similar to others? image

I think your browser is using cached CSS. Trying clearing your cache.

**Comment by pkdash** [comment]
@Maurier Yeah that was a browser cache problem as far as the alignment of the fileset legend. However, to match with other content type legends I think fileset legend should also needs to have border like the rest of the content type legends. I will leave up to you decide if this change is necessary or not. Let me know and I can approve it.

**Comment by Maurier** [comment]
> @Maurier Yeah that was a browser cache problem as far as the alignment of the fileset legend. However, to match with other content type legends I think fileset legend should also needs to have border like the rest of the content type legends. I will leave up to you decide if this change is necessary or not. Let me know and I can approve it.

I think this icon is intended to match the icon for the regular folder. In any case, we'll keep this one for now and discuss later if we want to change it.

**Review by pkdash — APPROVED** [review]

**Pull request merged**
