### PR TITLE
[#4748] Link to help page for advanced search

### PR DESCRIPTION
**Pull request by pkdash**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. On the discover page of the site, click the link "Advanced search help" displayed under the search bar. It should open the hydroshare help page in a new tab showing help information on advanced search feature.

### CODE REVIEW

**Comment by pkdash** [comment]
Waiting for the help page content to be verified by @alvacouch

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4762](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4762)

**Review by devincowan — APPROVED** [review]
Looks good
My only comment is when one searches an there are no results, "No resource matches" shows _below_ the advanced search help. Might want to put the "no resource matches" before the "advanced searches" in the DOM? Or maybe even put it within the `<input>` in some way...? A matter of personal preference so up to you.
image

**Comment by pkdash** [comment]
@devincowan I made the change you suggested.

**Review by devincowan — APPROVED** [review]
looks good, thanks Pabitra!

**Pull request merged**
