### PR TITLE
1207 refts allow to reference any wml url

### PR DESCRIPTION
**Pull request by zhiyuli**
We found the existing RefTS code already has the ability to accept any urls that can return wml content. The failing on some urls was because those urls are served via HTTPS.  The Requests module we are using by default blocks all https connections if no certificate file are provided. 
The changes we made to the backend are very simply. We simply set "verify=False" to let Requests lib ignore verifying ssl certificate, so it will accept both http urls and https urls. 

But we are not sure will this simply change leave any serious security issues?thanks @hyi @pkdash @mjstealey 

The other changes are all UI improvements, 
@jsadler2 can you please review the frontend? thanks

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@jsadler2 Please review.

**Comment by pkdash** [comment]
@jsadler2 Are you available to review this?

**Comment by jsadler2** [comment]
Everything seems to be working fine. I did have a question: @zhiyuli what does the "Check URL" button do? It seems unnecessary to me because any time I make a change in the URL input field, the validation function is run automatically without clicking the "Check URL" button.

**Comment by zhiyuli** [comment]
@jsadler2 
Thanks for reviewing this PR. I found sometimes when copying and pasting url to the textbox the default "OnChange" event does not get triggered right away. So the "Check URL" button works as a backup in this case: user can manually click that btn to trigger event.

**Comment by jsadler2** [comment]
@zhiyuli okay.

**Comment by jsadler2** [comment]
+1

**Pull request merged**
