### PR TITLE
2478 resend activation email

### PR DESCRIPTION
**Pull request by sblack-usu**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Sign up for a new account, ensure link for account activation is sent through email, do not use the link.  Try to sign into the account with the user/pass you setup.  Verify you can't login but are prompted with a message "This account's email has not been verified. Click to resend verification email."  follow the link and verify another email is sent to your account.  click that link and verify your account has been activated.

2. Sign up for a new account, verify a link for account activation is sent through email, do not use the link.  Try to sign up for another new account with the same email address.  Verify you can't create the account and are prompted with a message "An account with this email already exists.  Log in or click here to reset password."  Click the link to reset your password, enter a new password and verify a password reset verification email is sent.  Follow the link in the email and verify your account is active.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by pkdash** [comment]
@sblack-usu Will try to review tonight. If anyone else can review before that it would be great too.

**Comment by aphelionz** [comment]
@sblack-usu Where are you on coordinating with @Lizabrazil on this? This seems like something that definitely requires updated user documentation.

**Comment by sblack-usu** [comment]
@aphelionz Received an email from @Lizabrazil confirming there is no user documentation needed for this ticket.

**Pull request merged**
