### PR TITLE
2673 comma delimiter

### PR DESCRIPTION
**Pull request by sblack-usu**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Navigate to the signup page in hydroshare.  Add a few different organizations, include at least one organization with a comma (if you start typing puerto rico, you'll see some orgs with commas) and at least one without.  Create the account and activate it.  Navigate to the profile page and validate all the organizations are displayed correctly.

2. With the same account created in test case 1, navigate to the profile and select edit.  Add and remove at least on organization with a comma and one organization without a comma.  Click save and validate the organizations displayed are correct.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
+1

**Comment by sblack-usu** [comment]
Email for documentation approval sent to @Lizabrazil

**Comment by Lizabrazil** [comment]
No documentation needed

**Comment by Lizabrazil** [comment]
If there are certain characters that are still not allowed in organization then that should be documented, please let me know if that is the case. It should really be documented on the interface level if a user tries to add an invalid character.

**Comment by sblack-usu** [comment]
@Lizabrazil the only character the can't be in an organization is the semicolon

**Comment by Lizabrazil** [comment]
if a user tries to insert a semicolon do they get notified it is an invalid character? I'm guessing that won't be used often though

**Comment by sblack-usu** [comment]
If they enter a semicolon it will add what they've typed already as an organization.  

If an organization with a semicolon gets added to the existing organizations lookup database then we'll have the same problem we did with commas.  But that shouldn't happen without a developer manually adding it.

**Pull request merged**
