### PR TITLE
Adding "flag" as a possible param for the flag endpoint

### LINKED ISSUE #2193: Flag syntax 't' parameter is confusing

### PR DESCRIPTION
**Pull request by aphelionz**
Fixes #2193

### CODE REVIEW

**Comment by pkdash** [comment]
As @hyi suggested it would be better to replace ```t``` with ```flag``` rather than supporting both.

**Comment by aphelionz** [comment]
@pkdash @hyi "t" param was removed

**Comment by aphelionz** [comment]
@pkdash @mjstealey Why is this failing on jenkins? The errors seem weird, like `0 == 0` and it passes locally... any ideas? :/

**Comment by pkdash** [comment]
@aphelionz Looking into why tests fail in Jenkins.

**Comment by mjstealey** [comment]
> Looking into why tests fail in Jenkins.

From the stacktrace it appears the test is wanting to **assertNotEqual** but the result is **0 == 0**, so it fails.

```
File "/usr/local/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/hydroshare/hs_core/tests/api/views/test_set_resource_flag.py", line 161, in test_set_resource_flag_make_discoverable
    self.assertNotEqual(len(err_messages), 0)
  File "/usr/local/lib/python2.7/unittest/case.py", line 522, in assertNotEqual
    raise self.failureException(msg)
'0 == 0\n-------------------- >> begin captured logging << --------------------\npysolr: DEBUG: Starting request to \'http://172.17.0.4:8983/solr/update/?commit=true\' (post) with body \'u\'<delete>\'...\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None\npysolr: INFO: Finished \'http://172.17.0.4:8983/solr/update/?commit=true\' (post) with body \'u\'<delete>\' in 0.009 seconds.\npysolr: DEBUG: Starting request to \'http://172.17.0.4:8983/solr/update/?commit=true\' (post) with body \'u\'<delete>\'...\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None\npysolr: INFO: Finished \'http://172.17.0.4:8983/solr/update/?commit=true\' (post) with body \'u\'<delete>\' in 0.012 seconds.\npysolr: DEBUG: Starting request to \'http://172.17.0.4:8983/solr/update/?commit=true\' (post) with body \'u\'<delete>\'...\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None\npysolr: INFO: Finished \'http://172.17.0.4:8983/solr/update/?commit=true\' (post) with body \'u\'<delete>\' in 0.008 seconds.\npysolr: DEBUG: Starting request to \'http://172.17.0.4:8983/solr/update/?commit=true\' (post) with body \'u\'<delete>\'...\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None\npysolr: INFO: Finished \'http://172.17.0.4:8983/solr/update/?commit=true\' (post) with body \'u\'<delete>\' in 0.013 seconds.\npysolr: DEBUG: Starting request to \'http://172.17.0.4:8983/solr/update/?commit=true\' (post) with body \'u\'<delete>\'...\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None\npysolr: INFO: Finished \'http://172.17.0.4:8983/solr/update/?commit=true\' (post) with body \'u\'<delete>\' in 0.006 seconds.\n--------------------- >> end captured logging << ---------------------'
```

**Comment by pkdash** [comment]
@aphelionz It seems the failing unit tests are still using 't' instead of 'flag'. Here is an example:
https://github.com/hydroshare/hydroshare/blob/2193-fixing-flag-params/hs_core/tests/api/views/test_set_resource_flag.py#L198

Once you replace 't' with 'flag' the tests should pass I think.

**Comment by pkdash** [comment]
+1

**Pull request merged**
