### PR TITLE
Dockerfile and Docker compose updates for 1.15.6

### PR DESCRIPTION
**Pull request by aphelionz**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Check this branch out and run `./hsctl rebuild -db` and ensure it builds properly

### CODE REVIEW

**Comment by phuongdm** [comment]
@aphelionz   built error

**Comment by aphelionz** [comment]
@phuongdm Take a look at the error:

`u'4635150.0' != '4.63515e+06'`

It looks like some new formatting was introduced. I wonder if we need to change the tests?

**Comment by aphelionz** [comment]
retest this, please

**Comment by phuongdm** [comment]
@alvacouch 

Alva, please take a look when you have a chance. Thanks!

**Comment by aphelionz** [comment]
retest this, please

**Comment by aphelionz** [comment]
retest this, please

**Comment by cbcunc** [comment]
retest this, please

**Comment by cbcunc** [comment]
The problem with checks failing comes down to four failing tests, all with similar tracebacks, and all in hydroshare/hs_file_types/tests. Here's one (same assertion, same error in each of the four tracebacks):

```Traceback (most recent call last):
  File "/hydroshare/hs_file_types/tests/test_view_functions.py", line 275, in test_add_update_metadata_to_netcdf_file_type
    self.assertEqual(orig_coverage.value['northlimit'], '4.63515e+06')
AssertionError: u'4635150.0' != '4.63515e+06'```

The tests all check to insure that the original coverage extents in a test NetCDF file remain the same after various operations to a NetCDF resource.

It's a wonder that this test ever passed, or a mystery if it ever ran, because it's not so much a test failure as an incorrectly coded test. The coverage extents appear to be coded as string representations of floating point numbers. Floating point numbers which are equivalent can take various forms, such as decimal or scientific notation, that are not equivalent when represented as strings. When a float object is referenced, there's no guarantee from Python if it will be represented in the same string form as the literal which created the float object. This value is being extracted from a netCDF file, where the extraction is represented as decimal. Yet it is being compared in string form to a scientific notation formatted string.

I propose to fix the four failing test cases by changing the test assertions to reflect a float point equivalency:

self.assertEqual(float(orig_coverage.value['northlimit']), 4.63515e+06)

This takes the string referenced by orig_coverage.value['northlimit'], converts it to an actual float, and compares it to an actual float.

@aphelionz Please approve this action. I should also change the branch name to 1.15.6-RC at the same time, I imagine.

@ndebuhr For your information

**Comment by cbcunc** [comment]
BTW, this brings up some things that should be cause for concern.

1. Why have these test either not failed previously or possibly not run?

2). I had to restest twice because of differing test results. The first retest (http://ci.hydroshare.org:8080/job/hydroshare-pull-requests/1880/console) ended in an apparent Jenkins failure. Working on the usually misguided hope that doing the same thing again will produce a different result, the failure @aphelionz was indeed reported (http://ci.hydroshare.org:8080/job/hydroshare-pull-requests/1881/console).

**Comment by aphelionz** [comment]
@cbcunc you have my go-ahead to fix the tests

**Comment by hyi** [comment]
@cbcunc Good point on converting to float then compare for assertEqual. However, I think comparing whether two floats are equal is problematic as well due to rounding errors and precision. One way to do it as described here: https://stackoverflow.com/questions/5595425/what-is-the-best-way-to-compare-floats-for-almost-equality-in-python is to check the absolute difference between two floats are close to zero, e.g., less than an error tolerance threshold value we can set.

**Comment by dtarb** [comment]
It would be good to have @pkdash comment on the string vs float issue as I think he has been involved in much of the coverage coding and test development and may be able to shed some light.

**Comment by pkdash** [comment]
The Coverage (both spatial and temporal) data is stored as json data and exposed as a dict object for the coverage element. For the generic Coverage model the numeric values are stored as float values. In the case of NetCDF resource/file type there seems to be a bug where this conversion is not happening prior to storing as json data.  Changing this line: https://github.com/hydroshare/hydroshare/blob/develop/hs_app_netCDF/models.py#L113
 to
``` box_dict[limit] = float(box_dict[limit])```
should fix the broken tests.

**Comment by cbcunc** [comment]
OK, that fix not only didn't work, but it caused even more test failures:

http://ci.hydroshare.org:8080/job/hydroshare-pull-requests/1886/console

I'm going to my original idea to just fix the tests. I will leave Pabitra's fix in place, since it fixes a bug in hs_ap_netCDF, and fix the tests it breaks also, because those test failures are similar comparisons of string and floats.

**Pull request merged**
