### PR TITLE
4781-Upgrading Postgres to version 15

### PR DESCRIPTION
**Pull request by pkdash**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. This needs to tested with existing hydroshare data to ensure existing data can be loaded into this newer version of postgres db. May be deploy to beta and verify that this upgrade of postgres doesn't break anything. Verify the existing resources and aggregations work as expected. Verify the discover/search works. Create a new composite resource and create each of the aggregation types in that resource. 

**Note**: Have tested on dev-2. Didn't see any issue with existing data being loaded into the new version of postgres.

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4782](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4782)

**Review by cbcunc — DISMISSED** [review]
Approving at least the PG changes. Assuming @pkdash has tested the test case fixes.

**Comment by pkdash** [comment]
@cbcunc Was wondering if you did any test using postgres 14 with existing data.

**Comment by cbcunc** [comment]
> @cbcunc Was wondering if you did any test using postgres 14 with existing data.

@pkdash I approved these changes. But it's not enough to merge. Please don't merge yet. We will need more commits. At a minimum, hsctl will need to export PGPASSWORD due to change in Postgres authentication. We can talk about this when you get back. hsctl has LOADDB section which governs data update in the Jenkins deployment job. It will need testing and the testing is time consuming due to how long it takes to do a full data update on beta.

**Comment by cbcunc** [comment]
> > @cbcunc Was wondering if you did any test using postgres 14 with existing data.
> 
> @pkdash I approved these changes. But it's not enough to merge. Please don't merge yet. We will need more commits. At a minimum, hsctl will need to export PGPASSWORD due to change in Postgres authentication. We can talk about this when you get back. hsctl has LOADDB section which governs data update in the Jenkins deployment job. It will need testing and the testing is time consuming due to how long it takes to do a full data update on beta.

I dismissed my previous approval and requested re-review until we can discuss the additional changes to hsctl needed.

**Comment by pkdash** [comment]
@cbcunc Glad I waited to merge. We can discuss changes needed for hsctl script next week. If you let me know what changes to be made I can make those changes this week.

**Comment by pkdash** [comment]
@cbcunc I updated this PR to use the image for postgres 15.

**Comment by cbcunc** [comment]
Should conf_postgres be removed? I believe it only applies to the old PG image. I don't think it is healthy to simply overwrite pg_hba.conf and postgresql.conf from an old version of PG.

**Review by cbcunc — APPROVED** [review]
Other than possibly removing conf_postgres as mentioned in comments, this should be good to go.

**Review by cbcunc — APPROVED** [review]
Thanks for removing conf_postgres.

**Pull request merged**
