### PR TITLE
[#4146] open license agreement url in a new tab

### PR DESCRIPTION
**Pull request by pkdash**
### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Create a resource. Upload a file.
2. Enable 'Require agreement to rights statement before downloading'
3. Try to download the file. This should display the Resource License Agreement modal. Click the link displayed on this modal. Verify that the license link opens in a new browser tab. 
4. Try to download the resource bag and verify same as step as 3 above.

### CODE REVIEW

**Comment by devincowan** [comment]
Looks good, but what about this one:
https://github.com/hydroshare/hydroshare/blob/4146-license-agreement-link-fix/theme/templates/resource-landing-page/modals.html#L1692

**Review by devincowan — CHANGES_REQUESTED** [review]
maybe just check to see if we should also add `target="_blank"` to 
https://github.com/hydroshare/hydroshare/blob/4146-license-agreement-link-fix/theme/templates/resource-landing-page/modals.html#L1692
thanks!

**Review by devincowan — APPROVED** [review]

**Review by devincowan — APPROVED** [review]
Nice!

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4757](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4757)

**Pull request merged**
