### PR TITLE
update local dev to use 9.4.7 postgres image

### PR DESCRIPTION
**Pull request by sblack-usu**
9.5.0 has been removed and was only used by the local dev setup... This change updates local dev configuration to use 9.4.7

### CODE REVIEW

**Comment by sblack-usu** [comment]
@cuahsimarko - we should get this merged soon.  I know @Maurier ran into issues building the local dev environment with 9.5.0.

**Comment by Maurier** [comment]
I agree with @sblack-usu. I pulled these changes and the issue is resolved.

**Comment by keatingr** [comment]
I can't log into git right now, so Alva is going to approve. He and I just discussed.

**Comment by alvacouch** [comment]
Approved per conversation with Mark

**Pull request merged**
