### PR TITLE
#4324 update default font in hs core to Roboto

### LINKED ISSUE #4324: Readme.md files rendered with inconsistent fonts
**Description of the bug**

If a readme.md file is added to a resource that does not have resource level coverage information, the readme.md file is rendered with multiple, inconsistent fonts. The headings are rendered with one font and text is rendered in another font. Readme.md files for resources that have resource level coverage are rendered with consistent fonts. This is the desired behavior. This has something to do with CSS inheritance.

Steps to reproduce the bug:
1. Create a resource
2. Add a readme.md file that has both headers and paragraph text
3. Save the resource
4. Observe that the readme file is rendered with inconsistent fonts.

**Expected behavior**

readme.md files should be rendered on the resource landing page using a consistent font for both headings and body text.

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

Example readme file rendered with inconsistent fonts:

image

### PR DESCRIPTION
**Pull request by devincowan**
### Pull Request Checklist: 
- [X] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Observe that header fonts now match the Roboto that was used throughout the rest of HS core
2. This applies to the Readme.md preview as well, if you:
    1. Create a new resource and upload a readme.md file that contains both headers and paragraphs
    2. [README.md](https://github.com/hydroshare/hydroshare/files/8036135/README.md)

Resolves #4324

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4481](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4481)

**Comment by devincowan** [comment]
thanks for taking a look @Maurier. I don't personally have any preference Lato vs Roboto but figured we probably want it consistent. I see that there is also significant use of Helvetica and other fonts for example:
https://github.com/hydroshare/hydroshare/blob/3e9d28572938882edb2e5def47d6e43a0c1ac859/hs_core/static/theme/default/style.css#L451
Do you think it's okay to update these as well?

**Comment by devincowan** [comment]
sounds good Mauriel, I just reverted those changes.

**Review by Maurier — APPROVED** [review]
Looks good.

**Pull request merged**
