### PR TITLE
752 Make resource type returned by /hsapi/resourceList reflect the actual type

### PR DESCRIPTION
**Pull request by selimnairb**
@yirugi Here is the PR for #752.  Thanks for bringing this to my attention.

### CODE REVIEW

**Comment by selimnairb** [comment]
@pkdash Can you please review?

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by selimnairb** [comment]
@pkdash I also included the creator fix as it was only one line.  Please let me know if this is correct.

**Comment by pkdash** [comment]
@selimnairb creator name fix looks good. You can merge it.

**Comment by gantian127** [comment]
@selimnairb would you please close this issue, if you think it has been fixed? Thanks

**Pull request merged**
