### PR TITLE
[#369] download button text

### PR DESCRIPTION
**Pull request by mauriel133**
Updated the text on the resource content download button.

### CODE REVIEW

**Comment by mauriel133** [comment]
After merging the develop branch I can no longer see the download button. Is this being addressed as part of [#409]?

**Comment by hyi** [comment]
Yes, this is addressed as part of [#409], but only when you create an empty resource without uploading files; otherwise, you should see download button. In any case, fix to #409 has been merged into develop, so download button should always be present with that fix.

**Comment by pkdash** [comment]
@mjstealey Is the last commit due to the merge with develop of any problem? Otherwise, +1

**Comment by mjstealey** [comment]
@mauriel133, @pkdash - deployed on dev and playground. Button text renders as expected however file size is always listed as 0... not sure if this is an oversight or a rounding thing. (tested on small files)

**Comment by hyi** [comment]
Took a brief look at the genericresource.html code and found my previous change with new bagit url was overridden by the merge. {{bag_url}} context variable should be used for bag url rather than retrieving it from cm.bags.first.bag.url. Also, ({{ b.bag.size|filesizeformat }}) have to be removed due to the new bagit workflow. @mjstealey @mauriel133 It may need some manual merging to bring the new change in.

**Comment by mjstealey** [comment]
@hyi - should this be a new issue?

Also, do you have a reference (previous pull-request) of what the file modifications you made should look like?

**Comment by hyi** [comment]
@mjstealey Brian's branch appears to have my latest code for genericresource.html: https://github.com/hydroshare/hydroshare/blob/413-update-rest-api-new-bagit-workflow/hs_core/templates/pages/genericresource.html
In particular, look at the lines 686-692, which got overridden by the merge.

**Comment by mjstealey** [comment]
@hyi - the only difference I see is the button-label line.

Would the line be fine if the `({{ b.bag.size|filesizeformat }})` references were removed?
Or is there something else that I am missing here?

pre-merge: 686 - 693
```                    
<!-- Buttons -->
  {% for b in cm.bags.all %}
    <a id="btn-download-all" type="button" class="btn btn-default" href="{{ bag_url }}">
      <span class="glyphicon glyphicon-download-alt">
        <span class="button-label">Download All</span>
      </span>
    </a>
   {% endfor %}
```

post-merge: 686 - 693
```
<!-- Buttons -->
  {% for b in cm.bags.all %}
    <a id="btn-download-all" type="button" class="btn btn-default" href="{{ bag_url }}">
      <span class="glyphicon glyphicon-download-alt">
        <span title='Download All Content as Zipped BagIt Archive ({{ b.bag.size|filesizeformat }})' class="button-label">Download All Content as Zipped BagIt Archive ({{ b.bag.size|filesizeformat }})</span>
      </span>
    </a>
   {% endfor %}
```

**Comment by hyi** [comment]
@mjstealey Yes, just checked develop branch and it looks like so. For some reason, last time I checked, the href was not assigned to {{ bag_url }}, but now it looks like removing ({{ b.bag.size|filesizeformat }}) should work. The reason we cannot use this line to check for size is that with the new bagit workflow, we don't know the bag size since all bagit operation is done on iRODS side.

**Pull request merged**
