### PR TITLE
Implement "sipderfier" markers on map view

### PR DESCRIPTION
**Pull request by xuezhaokun**
Implemented "sipderfier" markers on map view, which is suggested in issue #1189

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by xuezhaokun** [comment]
@mjstealey I ran tests locally and got a `ok` status. I am not sure why all checks failed here.

> 
> Ran 315 tests in 1018.885s
> 
> OK
> nosetests corsheaders theme theme.blog_mods haystack hs_core hs_access_control hs_labels hs_metrics irods_browser_app hs_geo_raster_resource ref_ts hs_app_timeseries hs_app_netCDF hs_model_program hs_modelinstance hs_tools_resource hs_swat_modelinstance hs_geographic_feature_resource hs_script_resource hs_sitemap hs_collection_resource debug_toolbar filebrowser_safe django_comments --verbosity=1
> Creating test database for alias 'default'...
> Destroying test database for alias 'default'...
> Name                                                Stmts   Miss  Cover
> -----------------------------------------------------------------------
> hs_access_control/__init__.py                           1      0   100%
> hs_access_control/models.py                           619     78    87%
> hs_app_netCDF/__init__.py                               0      0   100%
> hs_app_netCDF/admin.py                                  4      0   100%
> hs_app_netCDF/forms.py                                121     72    40%
> hs_app_netCDF/models.py                               139     82    41%
> hs_app_netCDF/nc_functions/__init__.py                  0      0   100%
> hs_app_netCDF/nc_functions/nc_dump.py                  88     75    15%
> hs_app_netCDF/nc_functions/nc_meta.py                 209    186    11%
> hs_app_netCDF/nc_functions/nc_utils.py                180    157    13%
> hs_app_netCDF/page_processors.py                       78     67    14%
> hs_app_netCDF/receivers.py                            236    218     8%
> hs_app_netCDF/serialization.py                        330    166    50%
> hs_app_timeseries/__init__.py                           0      0   100%
> hs_app_timeseries/admin.py                              4      0   100%
> hs_app_timeseries/forms.py                            109     27    75%
> hs_app_timeseries/models.py                           207     24    88%
> hs_app_timeseries/page_processors.py                   37     29    22%
> hs_app_timeseries/receivers.py                        294     63    79%
> hs_collection_resource/__init__.py                      0      0   100%
> hs_collection_resource/admin.py                         4      0   100%
> hs_collection_resource/models.py                       32      2    94%
> hs_collection_resource/page_processors.py              31     24    23%
> hs_collection_resource/receivers.py                     7      3    57%
> hs_collection_resource/urls.py                          3      0   100%
> hs_collection_resource/views.py                        49      3    94%
> hs_core/__init__.py                                     0      0   100%
> hs_core/admin.py                                        9      0   100%
> hs_core/autocomplete_light_registry.py                 21     14    33%
> hs_core/discovery_form.py                              46     40    13%
> hs_core/forms.py                                      752    493    34%
> hs_core/hydro_realtime_signal_processor.py             46      6    87%
> hs_core/hydroshare/__init__.py                          5      0   100%
> hs_core/hydroshare/date_util.py                        53     34    36%
> hs_core/hydroshare/discovery.py                         8      4    50%
> hs_core/hydroshare/hs_bagit.py                        141     25    82%
> hs_core/hydroshare/resource.py                        332    134    60%
> hs_core/hydroshare/social.py                           77      9    88%
> hs_core/hydroshare/users.py                           231    115    50%
> hs_core/hydroshare/utils.py                           318     67    79%
> hs_core/languages_iso.py                                1      0   100%
> hs_core/management/__init__.py                          1      0   100%
> hs_core/management/commands/__init__.py                 1      0   100%
> hs_core/metadata_terms_urls.py                          4      0   100%
> hs_core/models.py                                    1215    246    80%
> hs_core/page_processors.py                            221    207     6%
> hs_core/receivers.py                                   66     59    11%
> hs_core/resourcemap_urls.py                             4      0   100%
> hs_core/search_indexes.py                             165     24    85%
> hs_core/serialization.py                              912    680    25%
> hs_core/signals.py                                      9      0   100%
> hs_core/tasks.py                                       93     54    42%
> hs_core/templatetags/__init__.py                        1      0   100%
> hs_core/templatetags/hydroshare_tags.py                85     44    48%
> hs_core/testing.py                                     11      0   100%
> hs_core/urls.py                                         3      0   100%
> hs_core/views/__init__.py                             512    425    17%
> hs_core/views/autocomplete.py                          46     40    13%
> hs_core/views/discovery_json_view.py                   31     23    26%
> hs_core/views/discovery_view.py                        47     37    21%
> hs_core/views/pagination.py                             3      0   100%
> hs_core/views/resource_rest_api.py                    214     39    82%
> hs_core/views/serializers.py                           85     14    84%
> hs_core/views/user_rest_api.py                         12      0   100%
> hs_core/views/utils.py                                163    101    38%
> hs_geo_raster_resource/__init__.py                      0      0   100%
> hs_geo_raster_resource/admin.py                         4      0   100%
> hs_geo_raster_resource/forms.py                       153     93    39%
> hs_geo_raster_resource/models.py                      149     17    89%
> hs_geo_raster_resource/page_processors.py              57     47    18%
> hs_geo_raster_resource/raster_meta_extract.py         121     28    77%
> hs_geo_raster_resource/receivers.py                   197     36    82%
> hs_geo_raster_resource/serialization.py               341    210    38%
> hs_geographic_feature_resource/__init__.py              0      0   100%
> hs_geographic_feature_resource/admin.py                 4      0   100%
> hs_geographic_feature_resource/forms.py                66     26    61%
> hs_geographic_feature_resource/models.py              116     25    78%
> hs_geographic_feature_resource/page_processors.py      72     64    11%
> hs_geographic_feature_resource/parse_lib.py            76     10    87%
> hs_geographic_feature_resource/receivers.py           362     74    80%
> hs_labels/__init__.py                                   0      0   100%
> hs_labels/models.py                                   121      3    98%
> hs_labels/urls.py                                       3      0   100%
> hs_labels/views/__init__.py                            52     47    10%
> hs_metrics/__init__.py                                  0      0   100%
> hs_metrics/models.py                                    0      0   100%
> hs_metrics/urls.py                                      3      0   100%
> hs_metrics/views.py                                    65     49    25%
> hs_model_program/__init__.py                            0      0   100%
> hs_model_program/admin.py                               4      0   100%
> hs_model_program/forms.py                              49     21    57%
> hs_model_program/models.py                             83     35    58%
> hs_model_program/page_processors.py                    24     17    29%
> hs_model_program/receivers.py                          33     24    27%
> hs_model_program/urls.py                                4      0   100%
> hs_model_program/views.py                              20     14    30%
> hs_modelinstance/__init__.py                            0      0   100%
> hs_modelinstance/admin.py                               4      0   100%
> hs_modelinstance/forms.py                              56     25    55%
> hs_modelinstance/models.py                             84      3    96%
> hs_modelinstance/page_processors.py                    29     20    31%
> hs_modelinstance/receivers.py                          23     14    39%
> hs_script_resource/__init__.py                          0      0   100%
> hs_script_resource/admin.py                             4      0   100%
> hs_script_resource/forms.py                            29     10    66%
> hs_script_resource/models.py                           71     27    62%
> hs_script_resource/page_processors.py                  29     22    24%
> hs_script_resource/receivers.py                        41      9    78%
> hs_sitemap/__init__.py                                  0      0   100%
> hs_sitemap/views.py                                     6      2    67%
> hs_swat_modelinstance/__init__.py                       0      0   100%
> hs_swat_modelinstance/admin.py                          5      0   100%
> hs_swat_modelinstance/forms.py                        175     70    60%
> hs_swat_modelinstance/models.py                       280     25    91%
> hs_swat_modelinstance/page_processors.py               44     35    20%
> hs_swat_modelinstance/receivers.py                     33     24    27%
> hs_tools_resource/__init__.py                           0      0   100%
> hs_tools_resource/admin.py                              4      0   100%
> hs_tools_resource/forms.py                             88     26    70%
> hs_tools_resource/models.py                            97     20    79%
> hs_tools_resource/page_processors.py                   55     48    13%
> hs_tools_resource/receivers.py                         24      1    96%
> hs_tools_resource/utils.py                             14      0   100%
> hydroshare/__init__.py                                  2      0   100%
> hydroshare/celery.py                                   11      1    91%
> hydroshare/local_settings.py                           69      0   100%
> hydroshare/settings.py                                 65      2    97%
> hydroshare/urls.py                                     23      0   100%
> irods_browser_app/__init__.py                           0      0   100%
> irods_browser_app/models.py                             0      0   100%
> irods_browser_app/urls.py                               3      0   100%
> irods_browser_app/views.py                            132    116    12%
> manage.py                                               6      0   100%
> ref_ts/__init__.py                                      0      0   100%
> ref_ts/admin.py                                         4      0   100%
> ref_ts/forms.py                                        15      0   100%
> ref_ts/models.py                                       94     41    56%
> ref_ts/page_processors.py                              21     16    24%
> ref_ts/receivers.py                                     8      3    63%
> ref_ts/ts_utils.py                                    441    407     8%
> ref_ts/urls.py                                          3      0   100%
> ref_ts/views.py                                       205    175    15%
> theme/__init__.py                                       0      0   100%
> theme/admin.py                                         12      0   100%
> theme/blog_mods/__init__.py                             0      0   100%
> theme/blog_mods/admin.py                                7      3    57%
> theme/blog_mods/models.py                               0      0   100%
> theme/forms.py                                        183    115    37%
> theme/models.py                                        96     12    88%
> theme/templatetags/__init__.py                          0      0   100%
> theme/views.py                                        167    129    23%
> -----------------------------------------------------------------------
> TOTAL                                               13667   6451    53%
>

**Comment by mjstealey** [comment]
@xuezhaokun - The build machine was at 100% in /var and failing builds. Have cleared space and am testing on PR #1209. If that passes as expected will use same process to re-run this one.

**Comment by xuezhaokun** [comment]
@mjstealey Thanks for help!

**Comment by pkdash** [comment]
@mauriel133 Can you review this?

**Comment by mauriel133** [comment]
@xuezhaokun, once PR https://github.com/hydroshare/hydroshare/pull/1211 gets merged, could you update this branch so I can test it?

**Comment by xuezhaokun** [comment]
@mauriel133 updated.

**Comment by mauriel133** [comment]
@xuezhaokun, I think it is still not immediately obvious that there are multiple markers together after zooming in. It looks exactly as a single marker and even its tooltip suggests it is. Perhaps a different marker icon can be used in this case.

**Comment by xuezhaokun** [comment]
@mauriel133 I agree. Maybe a special marker for such case would make more sense. Or we could find some other way to solve it. I will be off for next two weeks. When I am back, I will continue work on it. Thanks!

**Pull request closed without merging**
