### PR TITLE
fix issue #2778

### PR DESCRIPTION
**Pull request by hyi**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]
Added check to only further check whether user is over quota when user has a UserQuota foreign key relation; added debug logging when exception is raised from email sending or when user does not have a UserQuota foreign key relation; added a management command to fix UserQuota foreign key relation for users which can be run as needed, e.g., when we get to know some users are missing UserQuota relation from the log.

### CODE REVIEW

**Comment by hyi** [comment]
@aphelionz I have requested your review for this. This will be targeted as a hotfix 1.15.3.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
- [ ] Are there existing automated tests that cover this?
- [ ] Has the positive test case been run by @Lizabrazil to ensure no doc changes are necessary?

**Comment by hyi** [comment]
@aphelionz This is a bug fix, so no doc changes are necessary. In terms of automated tests, I am not sure what needs to be covered for this bug fix.  Checking whether UserQuota model exists for all users? The test will fail until we run the management command to fix missing UserQuota problem, although we are not sure what caused missing UserQuota problem in the first place, I don't think we will run into this issue again now that the phased quota code release has stabilized at this point. We don't have tests to check whether all linked models to users exist or not, so I feel we don't have to add a test just to cover this. I'd suggest just to go with this without adding tests at this point, and if this missing UserQuota problem crops up again in the future, I will need to investigate and possibly add a test to cover this then. Let me know what you think. If you agree with my suggestion, I'll merge this.

**Comment by hyi** [comment]
@aphelionz Agreed creating a Jenkins task is better. However, this task needs to be run after release 1.15.3. Can you or someone else who is involved with production release take care of creating such a management command and schedule it to run after release 1.15.3? Can I merge this PR then now that no further code will be added in this PR?

**Comment by dtarb** [comment]
@hyi this script should also be run on a staging machine when we test 1.15.3 on beta to make sure that it fixes the problem users there.

**Comment by aphelionz** [comment]
@hyi It doesnt take long to create it. If you scaffold it Phuong or I will validate it and run it when it's time to do the hotfix.

**Comment by hyi** [comment]
@aphelionz @dtarb I created two Jenkins task to run this management command, one on beta, one on www. There are here: http://ci.hydroshare.org:8080/view/05.%20Quota/job/fix-user-quota-model-www/ and http://ci.hydroshare.org:8080/view/05.%20Quota/job/fix-user-quota-model-beta/ Feel free to modify/validate as needed. I am merging this PR now.

**Comment by aphelionz** [comment]
@hyi Thank you for bearing with me on that

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
