### PR TITLE
resolve [#370] to remove globals

### PR DESCRIPTION
**Pull request by hyi**
removed some unused imports and removed global variables whose uses have already been removed. @pkdash @selimnairb could you review to make sure they don't cause any issues? I have already done a global search and the removed don't appear to be used anywhere.

### CODE REVIEW

**Comment by selimnairb** [comment]
Unfortunately, I can't tell if these changes will cause problems just by looking at the code.  I suggest making sure we have unit tests that cover the modified code, and then running the tests to see if they pass.

**Comment by hyi** [comment]
agreed unit tests is the best. I did my best to make sure these globals are not used and removal of them will not cause issues, but to be 100% certain, unit tests are objective measure. @pkdash, is the test coverage you recently implemented sufficient at this stage to run for this purpose? If so, could you merge this branch in and run coverage test to make sure coverage score does not go down?

**Comment by hyi** [comment]
Used Pycharm "Find usage" as well as "Find across project" and made sure the removed globals are not used or can be safely replaced with a local variable. Also run coverage test and made sure the coverage percentage does not go down (stayed the same as expected). Also talked this with @selimnairb, @pkdash , and @ironfroggy, and think this pull request can be safely merged into develop.

**Comment by ironfroggy** [comment]
if we don't have tests already we can't really be confident that any new tests adequately test this change. If everything runs, I think we should merge, but I do agree that tests should be added for the affected functions if they do not already exist, before merging.

**Comment by hyi** [comment]
This pull request removed three global variables. Two global variables are not used in any functions any more, so they should be safe to remove. The other global variable is replaced by a local variable, and is not really used outside of that function get_resource_types(), so it should be safe to replace it with a local variable and return the local resource type variable value from the function. So this pull request should be safe to merge, and from this point on we should avoid to use global variables if at all possible.

**Pull request merged**
