### PR TITLE
HOTFIX banner display for BuPuSa community.

### PR DESCRIPTION
**Pull request by alvacouch**
This is a quick fix to make the BuPuSa community production-ready by establishing a banner and a mission statement to its community in the community landing page template. Image will be uploaded via the `access_community` management command.  This is in review by @martinseul and @ClaraCogswell for appearance and is deployed currently on cuahsi-dev-1. 

See https://cuahsi-dev-1.hydroshare.org/community/2/.

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW SECURITY HOTSPOTS | 0 |
| NEW CODE SMELLS | 0 |
| NEW BUGS | 2 |
| NEW DUPLICATED LINES DENSITY | 0.0 |
| NEW VULNERABILITIES | 0 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4362](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4362)

**Review by sblack-usu — APPROVED** [review]

**Comment by sblack-usu** [comment]
retest this, please

**Comment by sblack-usu** [comment]
I'm not seeing anything in this PR that would cause all of those tests to fail.  Hong and I have also been seeing pylint errors for some files that are not a part of our PRs.

**Comment by sblack-usu** [comment]
and now y

**Pull request merged**
