### PR TITLE
fix discovery reported issues

### PR DESCRIPTION
**Pull request by xuezhaokun**
Fixed the Chrome layout render issue reported by Mohamed. #1139

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by xuezhaokun** [comment]
Also fixed issue #1135

**Comment by xuezhaokun** [comment]
Fixed #1150

**Comment by pkdash** [comment]
@hyi Can you review it?

**Comment by hyi** [comment]
+1 - I cannot see clearly the changes made to fix layout issue from github, so just assumed it will work. Changes to fix the other two issues look fine to me, so I am giving a +1.

**Pull request merged**
