### PR TITLE
Fix for netcdf metadata xml

### PR DESCRIPTION
**Pull request by pkdash**

### CODE REVIEW

**Comment by gantian127** [comment]
+1

**Comment by pkdash** [comment]
@mjstealey Wondering if this fix can be part of 1.9.6.

**Comment by mjstealey** [comment]
> Wondering if this fix can be part of 1.9.6.

@pkdash - Has been added to release 1.9.6 and deployed to beta

**Comment by pkdash** [comment]
@mjstealey Thanks.

**Pull request merged**
