### PR TITLE
[#5201] folder move for aggregation fix

### PR DESCRIPTION
**Pull request by pkdash**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Create a resource. Create a fileset aggregation in that resource
2. Create a folder and upload a file to that folder.
3. Move the folder to the fileset aggregation/folder.
4. Navigate to the file inside the moved folder inside the fileset folder. Verify when you hoover mouse over the file, you see it shows '**File Set Content: One or more files with specific metadata**'
5. Create folder inside the fileset folder. Upload a file to that folder. Verify that the uploaded file becomes part of the fileset aggregation. 
6. Move the folder you created in step 5 out of the fileset aggregation to the root of the resource. 
7. Verify when you hoover mouse over the file inside the folder you moved in step 6, it doesn't show '**File Set Content: One or more files with specific metadata**'

### CODE REVIEW

**Review by devincowan — DISMISSED** [review]
Looks good! Thanks for all of the tests--I didn't do a detailed check on all of them but they look good.
Made one suggestion here:
https://github.com/hydroshare/hydroshare/pull/5238/files
~that you can take or leave.~
Looks like you approve of it, so I merged into this PR

**Review by devincowan — APPROVED** [review]

**Comment by devincowan** [comment]
@pkdash I have to admit that I don't know why my changes break our tests... feel free to revert them if you want!

**Comment by pkdash** [comment]
@devincowan I missed the code logic change in your proposed change PR. I thought it is just a change to the logical expression. I think I fixed it now. All tests should pass this time.

**Comment by devincowan** [comment]
Ha! I see now. Thanks, looks good

**Review by devincowan — APPROVED** [review]

**Pull request merged**
