### PR TITLE
[#2330] Map based spatial coverage editing for file metadata

### PR DESCRIPTION
**Pull request by Maurier**
Adds coverage map widget for selecting coordinates in file metadata.

image

image

image

### CODE REVIEW

**Comment by Maurier** [comment]
@dtarb @aphelionz @horsburgh This can be tested at https://park.hydroshare.org
Waiting for approval on solution to start code review.

**Comment by Maurier** [comment]
This code is ready for review now.

**Comment by aphelionz** [comment]
@pkdash Can you review this? If not I can.

**Comment by Maurier** [comment]
Done fixing merge conflicts.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by dtarb** [comment]
@Maurier please fix the failing tests.  Once tests pass @hyi can review per discussion on teleconference.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by Maurier** [comment]
@pkdash, @aphelionz The tests have passed and the code is ready for review.

**Pull request merged**
