### PR TITLE
Revert "Revert "[#3324] specify utf-8 encoding for non-ascii characte…

### PR DESCRIPTION
**Pull request by sblack-usu**
…rs""

This reverts commit b4c229723ace317c2e8b2aa40d2168a4ccd56cc2.

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Add a non-ascii character (alt + 141) to user's name.  Create a resource, make it public and ensure it shows up in Discover

### CODE REVIEW

**Comment by sblack-usu** [comment]
dang, looks like the discover display doesn't show the international character correctly.  But at least it's not breaking.  I'll see if I can get the display to work.

**Comment by cuahsimarko** [comment]
@zhiyuli can you verify from usability?

**Comment by zhiyuli** [comment]
@sblack-usu 
So the previously reverted fix starts working now? Something changed in solr?

**Comment by sblack-usu** [comment]
Alva did a fix by just passing unicode to the problem library.  But, that means the results are still in unicode and get displayed as ascii in the discover display.

**Comment by zhiyuli** [comment]
@sblack-usu @cuahsimarko @alvacouch 
Confirmed the resource with international char in Author name showed up on Discover page. But the display seems weird. I used this char ē in the author name.

image

**Comment by zhiyuli** [comment]
international char is incorrectly displayed after going through the problem library

**Comment by sblack-usu** [comment]
yeah, I'm seeing the same thing.  I'm not seeing a straightforward fix for displaying in utf-8 outside of settings the encoding by looping through the query results and building a new result with utf-8 encoding.  @alvacouch - any ideas that stick out to you?

**Comment by zhiyuli** [comment]
@sblack-usu @alvacouch @cuahsimarko 
is the troublesome dependency (the lib to parse human names?) required? can we get rid of it？

**Comment by cuahsimarko** [comment]
@sblack-usu since this prevents the prior behavior of crashing, I advise we accept this PR and have a separate fix for the display of the characters: https://github.com/hydroshare/hydroshare/issues/3398

**Pull request merged**
