### PR TITLE
1842 nginx sendfile

### PR DESCRIPTION
**Pull request by alvacouch**
This pull request implements nginx sendfile, allowing unlimited size transfers of bags and files stored locally in hydroshare, either as regular or user resources. This does not deal with federated resources that are not local user resources; these remain limited to 1 GB.

Scope of the change

*	All locally stored resources are downloaded the new way; all files, zipped files, and bags. 
*	This includes local "hydroshare" resources and local "user" resources. 
*	This does not include remote federated resources. For these, the old behavior persists.  
*	The improved behavior is used if one is downloading from a browser or the REST API.  

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case

1. Load any large user resource into UI, press download bag, bag downloads even if > 1 GB. 
2. Load any large regular resource into UI, press download bag, bag downloads even if > 1 GB. 
3. Large user bags load into REST API. 
4. Large data bags load into REST API.

### CODE REVIEW

**Comment by alvacouch** [comment]
@martinseul @aphelionz To be done by @phuongdm 

1. Generate `local_settings.py` from template to make SENDFILE_ON, IRODS_DATA_URI, IRODS_USER_URI, IRODS_CACHE_URI available to Django.
 
2. Rename files that are now templates -- and were not before, as .template: 
    a. `./nginx/config-files/hydroshare-ssl-nginx.conf`
    b. `./nginx/config-files/hydroshare-nginx.conf`

**Comment by alvacouch** [comment]
Notes and known bugs: 

1. The django_irods PR of the same name must be merged first. Then this PR can be finished and merged. 

2. If the resource is broken, the download can hang forever. This is true if the file that one is looking for doesn't exist. nginx will wait for it to exist! The browser will keep waiting for nginx to respond, and when you try to close it, the browser will report that downloads are in progress.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@martinseul @aphelionz @phuongdm 
For some reason I cannot understand, irods-level bag generation for user resources is now broken. I am rebuilding the whole server to see if that addresses this. The generation worked before and does not work now.  After the code to generate the bag, it doesn't exist.

**Comment by alvacouch** [comment]
@rayi113 It seems to be unrelated. Rebuilding the whole container scheme fixed this problem for me. I don't know why that was suffficient, yet.

**Comment by alvacouch** [comment]
@martinseul @aphelionz @phuongdm @Castronova 
The crash I experienced seems to be related to bagging the following user resource: 
https://cuahsi-dev-2.hydroshare.org/resource/9e1b23607ac240588ba50d6b5b9a49b5/
I did a controlled experiment in which I deleted its bag using the `check_bag --reset` command and then tried to download it. The behavior was that when I try to bag it, hydroshare locks up. When I reload the page to eliminate the lockup, hydroshare somehow gets confused. If I wait an inordinate amount of time without doing anything, the bag appears and downloads. If I get impatient, my actions somehow don't just crash generation of this bag, but instead, generation of all user bags. From then on, no user bags are generated, although they seem to be generated.

**Comment by alvacouch** [comment]
@Castronova @martinseul @aphelionz @phuongdm 
OK, I've enabled on-demand streaming download over the REST API. If my theory is correct, it'll work fine without any modification. See #2725 for details of why. Could someone test that the REST API still works on the demo machine cuahsi-dev-2.hydroshare.org?

Thanks, 
- alva

**Comment by alvacouch** [comment]
@martinseul @aphelionz @Castronova @phuongdm 
I think I know what is causing bag generation to stop.  The bag is marked as generated before it is generated. Thus if one interrupts the website, the bag is marked as generated but does not exist. This is an irrecoverable state botch. Marking the bag as generated **after** completing the generation should fix this.

**Comment by alvacouch** [comment]
@dtarb @martinseul @phuongdm @aphelionz The new download mechanism has the disadvantage that it gets overwhelmed by the existing download test mechanism. This mechanism tends to open many files and doesn't finish the downloads. The sendfile mechanism will in this case leave the download links open, in case the other side of the TCP connection comes back. Thus, nginx ends up saturating the available file descriptors and has to wait for the OS to close them due to timeouts (because nginx delegated the timeout to the OS by use of sendfile). While this is very unlikely in practice, setting tighter close timeouts on the sending side seems appropriate.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
A weird side-effect of my changes is that when one embeds Unicode into xml, the default Django response type gets messed up, leading to failed tests: 

```
FAIL: test_put_scimeta_generic (hs_core.tests.api.rest.test_scimeta.TestScienceMetadata)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hydroshare/hs_core/tests/api/rest/test_scimeta.py", line 36, in test_put_scimeta_generic
    response = self.getScienceMetadata(self.pid, exhaust_stream=False)
  File "/hydroshare/hs_core/tests/api/rest/base.py", line 102, in getScienceMetadata
    self.assertEqual(response['Content-Type'], 'application/xml')
AssertionError: 'text/html; charset=utf-8' != 'application/xml'
```

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@phuongdm @aphelionz @martinseul I've traced the test failures for file I/O to the use of `APIClient` rather than `Client` in tests. Since the test redirects to an external location, `APIClient` returns an empty response. 

Meanwhile, just to make life more interesting, the URLs being used start with "example.com", so they can't be referenced properly in `Client`. `APIClient` seems to ignore this.

**Comment by alvacouch** [comment]
@phuongdm @aphelionz @martinseul What this comes down to is that I need -- from the Django test framework -- to be able to contact the nginx container directly and unambiguously via some URL and the REST Client interface. Then I can do end-to-end testing of whatever file mechanism I install.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz OK, I'll fix recaptcha. 

I have much more major problems, though, because local testing fails. I need to be able to contact nginx in order to run existing tests that don't work because they presume that Django is responsible for serving files.

**Comment by alvacouch** [comment]
@aphelionz Do you realize that the recaptcha keys are already committed to develop? I didn't commit these..... I just merged develop....

**Comment by aphelionz** [comment]
Hmm ok, thank you. Ill investigate

**Comment by hydrobuild** [comment]
Build finished.

**Comment by sblack-usu** [comment]
@hyi is correct, those are the test keys found here.
https://developers.google.com/recaptcha/docs/faq

Perhaps I should have put a comment in the settings.py file to indicate they are test keys.

**Comment by aphelionz** [comment]
It's ok @sblack-usu. I was just confused.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz @sblack-usu @phuongdm Should test clear on jenkins now. Tests are still failing for quotas. See cuahsi-dev-2.hydroshare.org file hydroshare/TEST.OUT

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@sblack-usu @aphelionz @mjstealey @dtarb
I am having incredible troubles with system interactions. I now get an error from a subsystem I didn't modify at all: 
```
Stacktrace
  File "/usr/local/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/hydroshare/hs_file_types/tests/test_reftimeseries_metadata.py", line 233, in test_set_file_type_to_file_with_missing_abstract
    self._test_valid_missing_optional_elements()
  File "/hydroshare/hs_file_types/tests/test_reftimeseries_metadata.py", line 367, in _test_valid_missing_optional_elements
    RefTimeseriesLogicalFile.set_file_type(self.composite_resource, res_file.id, self.user)
  File "/hydroshare/hs_file_types/models/reftimeseries.py", line 766, in set_file_type
    raise ValidationError(ex.message)
```

**Comment by alvacouch** [comment]
@sblack-usu @aphelionz @dtarb @martinseul OK, I understand what is going on. Remember that the way I do downloads isn't accessible from inside the docker containers; it's an external link. The json validator tries to download one of these links and fails. So, I might have to open a different URL if the link is internal.

**Comment by alvacouch** [comment]
@dtarb @aphelionz @martinseul The final solution is -- in 20/20 hindsight -- rather obvious. 

I made `django_irods` sensitive to whether it is called by nginx or not, by checking the headers sent to it from nginx. 

* If `django_irods` is called by nginx, and reverse proxy is enabled, `django_irods` reverse-proxies the file download. 
* If OTOH `django_irods` is not called by nginx, or if reverse proxy is not enabled, it uses regular forward proxy mechanisms.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz This is ready for review

a. check_download will be deleted before merge. I'll work on it later. 
b. I am leaving in the ability to query the nginx server directly from management commands. I will use this in future management commands.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz There is one difference between the version on cuahsi-dev-2 and the version in GitHub: the `django_irods` library is instrumented with code to trace how redirects are done and print them to `hydroshare.log`. So, you can see redirects happen. This is how I found the strangeness in redirecting to www.hydroshare.org instead of localhost. I'm leaving this out of the production code.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
retest this, please

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
Found one bug. The referenced time series handler calls the streaming view from the back door and presumes regular stream handling that isn't reverse proxied. 

```
[19/Jun/2018 17:29:38] DEBUG [hydroshare:29] processing request /hsapi/_internal/9c5d5fdc4f054f03bbfc0ed8acf98fbc/rest-download-refts-resource-bag/ rest_call=True use_async=False
[19/Jun/2018 17:29:38] DEBUG [hydroshare:232] invoking sendfile on bags/9c5d5fdc4f054f03bbfc0ed8acf98fbc.zip
[19/Jun/2018 17:29:38] DEBUG [hydroshare:261] invoking non-federated sendfile on bags/9c5d5fdc4f054f03bbfc0ed8acf98fbc.zip
[19/Jun/2018 17:29:38] DEBUG [hydroshare:269] redirection path is /irods-data/bags/9c5d5fdc4f054f03bbfc0ed8acf98fbc.zip
[19/Jun/2018 17:29:38] ERROR [ref_ts.views:263] rest_download_refts_resource_bag: Failed to stream RefTS bag
Traceback (most recent call last):
  File "/hydroshare/ref_ts/views.py", line 255, in rest_download_refts_resource_bag
    raise Exception("Failed to stream RefTS bag")
Exception: Failed to stream RefTS bag
```

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@dtarb @martinseul @aphelionz @danames @Lizabrazil Status of large file download testing: 

Comprehensive testing of downloads via a modified `check_bag --download_bag` uncovered a systemic pre-existing condition for referenced time series resource. Many bag downloads are failing, to wit:

``` 
resource: 34eb01dc721f4aa6b2fb3fb63b0e991e
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: d7b8069fd06547c984fc98bcbeacd4e7
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: a5f1324fcd9d476e8471b48755d000c3
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: bd311a4e3f384f4f9349c2337c88aec0
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: bd1ea35a897a4b0d94dce9ff49712f7e
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: 48865b60d6f14b509d2096d7f26bdd9a
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: a5e986bbf633422aa3f528e7d44a639b
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: a1d57d820045497c959e87608c07f43c
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: 905b903e8dd1492bb16891fd155b6f2a
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: cd7225412cd648b4aa5d1624e2465bd1
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: 531e4dc0c2024a4faf7bb9bcee0434df
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: b64a039c70554bf6adc72174decb8694
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: ae8d447ca577405099aad2456b233f6d
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: 3f650788e51d427bac3c6423556914d4
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: ec1621ce89034343b35e91b534aa8017
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: 0468e03953444ca094c7087897455301
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: c14002b2a1a64699a9cf1d0f209d2d86
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: 8f2e7133baee4a22a6914bd363879663
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: f71783e291c9407daa38e3972d66cbc1
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: ba1c287083d24f5e9efd84e13d0204b2
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: b235df93401047abbdc435975dd6862e
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: c05dd6d313c243d7bf0ecec23d7282de
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: 9763f69e77ec411aaa7b3484b44ce9ee
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: e593894cc7554515ae53b51bc7165cae
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: 67fa333f210144f892e67cf2de1206e0
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'

resource: c28359056de64680bbdfc64514e1f599
resource type: RefTimeSeriesResource
resource creator: michael souffront
failure mode: connection refused

resource: c05c66a77b2348639a122ade5e9e9870
resource type: RefTimeSeriesResource
resource creator: Matthew Bayles
failure mode: connection refused

resource: 954c5b40e37342a58e3477a459eb544e
resource type: RefTimeSeriesResource
resource creator: Dan Ames
failure mode: connection refused

resource: 36a40d6d931740afa8ae49fdfb8a0c64
resource type: RefTimeSeriesResource
resource creator: Shawn Crawley
failure mode: connection refused

resource: 31129107b6124b2cb9f90519cb538c03
resource type: RefTimeSeriesResource
resource creator: liza brazil
failure mode: connection refused

resource: 5ef99335b3ac4066b75c7f205dee40e9
resource type: RefTimeSeriesResource
resource creator: Christian Kesler
failure mode: connection refused

resource: d28685eb86474737ae93cc901f78dbb0
resource type: RefTimeSeriesResource
resource creator: Christian Kesler
failure mode: connection refused

resource: bce7694685874d85812f13df82bd6f33
resource type: RefTimeSeriesResource
resource creator: David Tarboton
failure mode: invalid index in 'start_date = value_list[0].date_time.isoformat()'
```
These are crashing either because they can't parse the source file, or the source file is no longer present. This seems to be the case also on www. Please verify.

**Comment by alvacouch** [comment]
@pdoan @aphelionz @martinseul Jenkins tests for this PR are failing with a non-descript error message I don't understand. I need assistance with understanding what is going wrong.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz @martinseul Added enhanced debugging command `check_uri` that fetches a URI from the local Nginx server, and saves results to a file. This translates all URIs starting with www.hydroshare.org (e.g., URIs in metadata) to URIs for the Nginx server. Thus this can be used to test the loopback between Nginx and Django.

**Pull request merged**
