### PR TITLE
Spatial coverage editing changes for composite resource

### PR DESCRIPTION
**Pull request by pkdash**

### CODE REVIEW

**Comment by pkdash** [comment]
@Maurier Was wondering if you can review this soon?

**Comment by pkdash** [comment]
@hyi It seems @Maurier is having some issues with his local dev environment. Can you review this PR?

**Comment by pkdash** [comment]
@Maurier and @hyi Can one of your review this?

**Comment by pkdash** [comment]
@hyi Thanks. @Maurier Let me know if you want me to wait for your review. Otherwise, I will merge.

**Comment by aphelionz** [comment]
@pkdash is this related to an issue?

**Comment by pkdash** [comment]
@aphelionz Issue #2110

**Pull request merged**
