### PR TITLE
832 improvements on discovery

### PR DESCRIPTION
**Pull request by xuezhaokun**
Make modifications based on the suggestions in issue #832 
1. remove color map
2. change the color coding of the counts to go from dark (high) to light (low) by reversing the color map
3. Use consistent resource type names in filtering panel and table
4. move the pagination option from left top to right bottom of the table

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@mauriel133 Can you please review this?

**Comment by mauriel133** [comment]
Pabitra, can you have this deployed in a VM so that I can test with a copy of the resources in ww?

**Comment by mauriel133** [comment]
Oh, I forgot I can do this myself now. I will deploy on a VM and test it. Will get back to you.

**Comment by mauriel133** [comment]
I think the red color is too hard to read for the background.
ss1

**Comment by mauriel133** [comment]
Not sure if this is the focus of this PR, but I noticed this padding issue:
ss2

**Comment by mauriel133** [comment]
I would give this button "margin-bottom: 10px" and change the text from "clear all" 
ss3
to "Clear All"

**Comment by mauriel133** [comment]
Actually, there are many css changes I'd like to make, so I'm going to go in the branch and address them right now if you don't mind.

**Comment by xuezhaokun** [comment]
@mauriel133 You can do whatever css changes you think those are necessary. I am not sure how can I make modifications in hydroshare_core.css file. Thanks for the help!

**Comment by mauriel133** [comment]
> 2. change the color coding of the counts to go from dark (high) to light (low) by reversing the color map

@pkdash, consider starting with a not-so-light shade of blue such that a white font is still readable in it, and use white font for the number in all of them instead of red.

**Comment by pkdash** [comment]
@xuezhaokun is this ready for a final review by @mauriel133 ?

**Comment by ironfroggy** [comment]
This has sat with no activity for over a week. @pkdash @xuezhaokun @mauriel133 Do any of you have next steps for this?

**Comment by mauriel133** [comment]
@xuezhaokun, the color scheme used in the badges needs to be changed based on the suggestion I gave above.

**Comment by xuezhaokun** [comment]
@mauriel133  Sorry for the late reply. I was working the map-view stuff. I just checked the colormap library. It seems we can could have 9 data classes for using the blue sequence colormap. But we have 10 data classes in our search.html. Should we use some other color sequence? I remember Hong initialized this colormap stuff. @hyi Can you give a quick help or guide here? Thanks!

**Comment by hyi** [comment]
@xuezhaokun @mauriel133 Refer to http://colorbrewer2.org/ for color advice. You can customize a number of variables to generate the color map you need, such as number of data classes, nature of your data, a color schema, etc. You can play with it and see what it looks like on a map to pick a good color schema for our use. Hope this helps.

**Comment by xuezhaokun** [comment]
@hyi It seems now we are using the blue sequence. The max number of data classes for sequential data is 9 which starts from white; however we are having 10 classes now. @mauriel133 Should we merge  some of our classes here and start from some darker blue? Any suggestions?

**Comment by mauriel133** [comment]
Is there a way we can use this same scale, but starting from a light blue rather than white?

**Comment by xuezhaokun** [comment]
@mauriel133 It seems cannot be done on its website. I am going to manually calculate and modify it.

**Comment by ironfroggy** [comment]
@mauriel133 I thought the colormaps were being removed entirely for being unclear to users. Is that not the case?

**Comment by dtarb** [comment]
I think that the colormap scale bar should be removed in its entirety from the top left of the discover page, because right now it is just a pattern that the user has no information as to how to interpret.  However I think that different colors following a colormap scales should still be used with the number or resources returned with each filter item.  Users will then soon recognize that the colors relate to the number of items.  I would prefer more items to get darker colors, flipping the scale from what it is now.  I would also prefer items for which there is only one resource found to be listed in the filters because otherwise it is hard to isolate one resource by one author in a long list.

**Comment by ironfroggy** [comment]
@xuezhaokun @mauriel133 @dtarb What is the status of this ticket, now with its last update nearly two months back?

**Comment by xuezhaokun** [comment]
@ironfroggy I think we can merge this PR with PR1058. PR1058 includes the all the requirements in this ticket.

**Comment by ironfroggy** [comment]
@xuezhaokun Is that something you can do then?

**Comment by xuezhaokun** [comment]
@ironfroggy Can I just simply close this PR and just keep focus on PR 1058?

**Comment by mjstealey** [comment]
> Can I just simply close this PR and just keep focus on PR 1058

@xuezhaokun - if the new branch/PR you are working on covers what this PR would have, then yes, that makes sense to do.

If you do close this PR, please also denote this information in any other relevant issues that may have referred to it so that the audit trail doesn't simply dead end on a closed PR.

**Comment by xuezhaokun** [comment]
@mjstealey  got it. thx!

**Pull request closed without merging**
