### PR TITLE
hide extended metadata tab when there is no data in view mode

### PR DESCRIPTION
**Pull request by zhiyuli**
This pr is to address 1) #1254, and 2) broken popup message when extended metadata is saved

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by hydrobuild** [comment]
Jenkins admin needs to whitelist request for testing.

**Comment by mauriel133** [comment]
+1

**Comment by pkdash** [comment]
@zhiyuli This is ready to be merged.

**Pull request merged**
