### PR TITLE
Link DOIs to preferred resolver (fixes #2689)

### LINKED ISSUE #2689: Hyperlink DOIs against preferred resolver
Hello :-)

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Would a PR that updates all static links & the code that generates new ones, plus the test cases be welcome?

Cheers!

### PR DESCRIPTION
**Pull request by katrinleinweber**
### Pull Request Checklist: 
- [x] ~~Positive Test Case Written by Dev~~ Not relevant to hyperlink updates

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### CODE REVIEW

**Comment by katrinleinweber** [comment]
I was hoping the CI pipeline would kick in automatically.

**Comment by aphelionz** [comment]
Let me see if I can kick it off...

**Comment by aphelionz** [comment]
retest this, please

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@katrinleinweber All set, thank you for contributing, and sorry it took a minute to get this approved. Please merge and delete the branch when you are ready.

**Comment by katrinleinweber** [comment]
No worries. Thanks for approving :-)

**Pull request merged**
