### PR TITLE
[#909] sharing status icons

### PR DESCRIPTION
**Pull request by mauriel133**
Sharing status icons in My Resources table. Can be tested at https://riverdev.hydroshare.org/

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@mauriel133 Can you deploy this for testing?

**Comment by mauriel133** [comment]
It's deployed at https://riverdev.hydroshare.org/

**Comment by mjstealey** [comment]
@mauriel133 - migrations conflict

From Jenkins console for your build:
```bash
*** manage.py migrate ***
/usr/local/lib/python2.7/dist-packages/mezzanine/utils/conf.py:55: UserWarning: TIME_ZONE setting is not set, using closest match: Etc/UTC
  warn("TIME_ZONE setting is not set, using closest match: %s" % tz)
/usr/local/lib/python2.7/dist-packages/django/contrib/contenttypes/models.py:159: RemovedInDjango19Warning: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ContentType(models.Model):

/usr/local/lib/python2.7/dist-packages/autocomplete_light/widgets.py:19: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
  from django.forms.util import flatatt

/usr/local/lib/python2.7/dist-packages/autocomplete_light/fields.py:8: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes.generic import GenericForeignKey

/usr/local/lib/python2.7/dist-packages/crispy_forms/utils.py:25: RemovedInDjango19Warning: memoize wrapper is deprecated and will be removed in Django 1.9. Use django.utils.lru_cache instead.
  default_field_template = memoize(default_field_template, {}, 1)

System check identified some issues:

WARNINGS:
?: (mezzanine.core.W01) Please update your settings to use the TEMPLATES setting rather than the deprecated individual TEMPLATE_ settings. The latter are unsupported and correct behaviour is not guaranteed. Here's a suggestion based on on your existing configuration:

TEMPLATES = [{u'APP_DIRS': True,
              u'BACKEND': u'django.template.backends.django.DjangoTemplates',
              u'DIRS': (u'/home/docker/hydroshare/hydroshare/templates',),
              u'OPTIONS': {u'builtins': [u'mezzanine.template.loader_tags'],
                           u'context_processors': (u'django.contrib.auth.context_processors.auth',
                                                   u'django.contrib.messages.context_processors.messages',
                                                   u'django.core.context_processors.debug',
                                                   u'django.core.context_processors.i18n',
                                                   u'django.core.context_processors.static',
                                                   u'django.core.context_processors.media',
                                                   u'django.core.context_processors.request',
                                                   u'django.core.context_processors.tz',
                                                   u'mezzanine.conf.context_processors.settings',
                                                   u'mezzanine.pages.context_processors.page')}}]

?: (mezzanine.core.W02) TEMPLATE_DEBUG and DEBUG settings have different values, which may not be what you want. Mezzanine used to fix this for you, but doesn't any more. Update your settings.py to use the TEMPLATES setting to have template debugging controlled by the DEBUG setting.
hs_swat_modelinstance.ModelObjective.swat_model_objectives: (fields.W340) null has no effect on ManyToManyField.
hs_swat_modelinstance.ModelParameter.model_parameters: (fields.W340) null has no effect on ManyToManyField.
hs_tools_resource.SupportedResTypes.supported_res_types: (fields.W340) null has no effect on ManyToManyField.
CommandError: Conflicting migrations detected (0002_auto_20160219_2039, 0002_auto_20160224_2337 in theme).
To fix them run 'python manage.py makemigrations --merge'
```

**Comment by pkdash** [comment]
@mauriel133 This will be automatically resolved once this #1024 gets merged.

**Comment by pkdash** [comment]
@horsburgh Do you want to test this since the icons have been updated? Let me know I can deploy it for testing. Otherwise, I can + 1 it so that it can be merged.

**Comment by mauriel133** [comment]
@horsburgh, this can be tested at https://park.hydroshare.org 
Notice that I added a panel at the bottom of the table that describes the legend used.

**Comment by horsburgh** [comment]
I tested on park.hydroshare.org, and this all looks fine to me.  I can appreciate the legend and the tool-tip/hover text on the icons.  I think you should go ahead and work on merging.

**Comment by pkdash** [comment]
+1

**Comment by pkdash** [comment]
@mauriel133 You can merge now.

**Pull request merged**
