### PR TITLE
Back merge RC-1.20 to develop

### PR DESCRIPTION
**Pull request by cuahsimarko**
Hotfixes to the Release can go back to develop to make new PRs cleaner.

### CODE REVIEW

**Comment by cuahsimarko** [comment]
Merge hotfixes for keywords fix and pagination removal from release into dev.

**Comment by cuahsimarko** [comment]
@hyi did you `git fetch`?

**Comment by hyi** [comment]
@cuahsimarko I did not test it locally, but checked using github web interface for all tags and did not see RC-1.20 tag.

**Comment by sblack-usu** [comment]
Can we just close this and I'll submit a PR tomorrow morning merging master back into develop?

**Comment by cuahsimarko** [comment]
@sblack-usu yes, closing now

**Pull request closed without merging**
