### PR TITLE
[#3165] Remove THREDDS Data Service message from multidimensional landing page

### PR DESCRIPTION
**Pull request by Maurier**
- Remove THREDDS Data Service section as requested in #3165 

**Before:** 
----------------
image

**After:**
----------------
image

Minor spacing adjustments

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Go to a multidimensional resource
2. Verify that the THREDDS Data Service section no longer appears on the page.

### CODE REVIEW

**Comment by Maurier** [comment]
The code that populates these items in the view has been left in place because it is still used in NetCDF file types. https://github.com/hydroshare/hydroshare/issues/3165#issuecomment-466453122

**Comment by Maurier** [comment]
@pkdash - since you know a lot about file types, do you know if the context variables in the code snippet below are used in file type logic of NetCDF files?

https://github.com/hydroshare/hydroshare/blob/develop/hs_app_netCDF/page_processors.py#L133

```
    # add thredds service links if the resource is public
    if content_model.raccess.public:
        for f in content_model.files.all():
            if '.nc' in f.resource_file.name[-3:]:
                ip = 'http://hyrax.hydroshare.org'
                shortkey = content_model.short_id
                nc_file_name = f.resource_file.name.split('/')[-1]

                context['opendap'] = '{}/opendap/{}/data/contents/{}.html'\
                    .format(ip, shortkey, nc_file_name)
                context['nc_file_name'] = nc_file_name
```

**Comment by hyi** [comment]
@Maurier @pkdash I just tested it out on www with a composite resource with netCDF file type, and made it public, however, I don't see OPeNDAP service link on the new resource landing page. This current code logic definitely needs to be updated in both back end and front end in order for the OPeNDAP service link to show up for the netCDF file types.

**Comment by Maurier** [comment]
@hyi - as discussed in https://github.com/hydroshare/hydroshare/issues/3165 this section is meant to be removed. As I am not familiar with this functionality, could you clarify if it is also needed for file types?

**Comment by hyi** [comment]
@Maurier Oh, just realized the issue is to remove this OPeNDAP message display on resource landing page. Then I am pretty sure that code snippet in page_processors.py to set context variables can be safely removed. Those context variables used to be used by that netCDF resource specific template file that extends from the main resource landing page template and append a specific content block to it to show this message. If that netCDF resource specific template file is deleted already, then this simple code snippet in page_processors.py can be safely deleted.

**Comment by Maurier** [comment]
@hyi - Thanks for confirming. That's what I got from my observations too.

**Comment by hyi** [comment]
@Maurier I think the idea is to remove this specific message and instead use Open With web app connector to open the netCDF file type with THREADDS service.

**Comment by Maurier** [comment]
@hyi - Understood. In that case I'm going to need someone familiar with web app connectors to take over this last part. Could you take over or point me to someone who might?

**Comment by hyi** [comment]
@Maurier It is already taken care of by this web app connector: https://www.hydroshare.org/resource/f5c46b72d49b4019972716a82355f7bd/. I have just tested it out and I am able to open this service from a netCDF file type. So I think once those message-related cleanup is done, we should be good.

**Comment by Maurier** [comment]
@hyi Understood. I have no made the change. @cuahsimarko Could you do another quick review?

**Comment by cuahsimarko** [comment]
@Maurier there's admittedly more here than I was initially aware of. I'm glad Hong was able to review. I can give this a rubber stamp of approval, if that is what is needed. Otherwise, Pabitra or Hong would be more appropriate.

**Comment by Maurier** [comment]
@cuahsimarko - Thanks for looking into this. The changes ended up being just front end and the removal of some context variables. Please review when you get a chance once more.

**Pull request merged**
