### PR TITLE
[#1044] remove uWSGI, replace with gunicorn

### PR DESCRIPTION
**Pull request by mjstealey**
- removed uWSGI and associated code
- installed gunicorn
- updated related scripts to use gunicorn
- will generate new **gunicorn.log** log file

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by selimnairb** [comment]
@mjstealey Something needs to be tweaked with this config.  Here's what I get when I try to create a Generic Resource with a ~1 megabyte file:

```
413 Request Entity Too Large
```

This error is coming from nginx.  Can you confirm you are seeing this in your environment?

Thanks.

**Comment by mjstealey** [comment]
> This error is coming from nginx.

Updated configuration to account for files up to 4 GB (until we get large file workflow straightened out).
Has been deployed to https://beta.hydroshare.org/ for testing.

**Comment by pkdash** [comment]
@selimnairb Can you review this?

**Comment by selimnairb** [comment]
All list REST tests are now passing in my test environment.  +1 to merge.

**Pull request merged**
