### PR TITLE
[#3520] Remove frontend messages for large files download

### PR DESCRIPTION
**Pull request by Maurier**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Create a resource
2. Upload a file larger than 1 GB
3. Verify that the file can be downloaded directly

### CODE REVIEW

**Comment by cuahsimarko** [comment]
@Maurier How do you suggest I upload a file > 1 GB? 
image

**Comment by dtarb** [comment]
Until @alvacouch gets large file uploads going you need to use iRODS to upload a file > 1 GB.  See https://help.hydroshare.org/creating-and-managing-resources/uploading-large-files-into-hydroshare/

**Comment by cuahsimarko** [comment]
@phuongdm @Maurier I suspect I'll need a riverdev or other deployment. The local iRODS creation at localhost failed. Please advise.

**Comment by Maurier** [comment]
@cuahsimarko I'll do some testing to make sure if this warning is thrown by some other settings in Dropzone.js. I'll set up a sandbox later today if I can adjust it.

**Comment by Maurier** [comment]
@cuahsimarko - This can now be tested at https://dev-hs-1.cuahsi.org/resource/9badb941303d4813b3c398cdab038368/

This resource has large files in it.

**Comment by cuahsimarko** [comment]
Cross-posting, per August 22 review and conversation: 
image

**Comment by Maurier** [comment]
> Not sure if it's a systems issue or code, but does not function as expected for me

I'll set up another VM where this can be tested, at the time I was not able to reproduce the error.

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW BUGS | 36 |
| NEW DUPLICATED LINES DENSITY | 6.04185623293904 |
| NEW SECURITY HOTSPOTS | 13 |
| NEW CODE SMELLS | 109 |
| NEW VULNERABILITIES | 0 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-3523](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-3523)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW VULNERABILITIES | 0 |
| NEW SECURITY HOTSPOTS | 13 |
| NEW BUGS | 36 |
| NEW DUPLICATED LINES DENSITY | 5.94449418084154 |
| NEW CODE SMELLS | 111 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-3523](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-3523)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-3523](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-3523)

**Review by sblack-usu — APPROVED** [review]
Looks good.  Let's get this deployed to beta and verify the messaging doesn't show up when downloading files over 1GB.

**Review by cuahsimarko — APPROVED** [review]

**Pull request merged**
