### PR TITLE
[Hotfix for 1.14RC] -- 2493 public resource landing page failed to open without signing in

### PR DESCRIPTION
**Pull request by zhiyuli**
deployed and verified on riverdev

### CODE REVIEW

**Comment by zhiyuli** [comment]
@aphelionz 
Should we wait for Jenkins's thumb-up?
I find these 2 tests have failed on several commits including mine
hs_dictionary.tests.test_universities.TestUniversities.test_universities_no_query
hs_dictionary.tests.test_universities.TestUniversities.test_universities_query

**Comment by aphelionz** [comment]
@zhiyuli We should wait. Also, those tests were fixed in previous commits... Are you talking about locally?

**Comment by zhiyuli** [comment]
I might have misunderstood the procedure to submit a hot fix. I created a
new branch based on latest 1.14rc and added my fix. Then I submit PR
against 1.14rc branch. Should I create new branch based on dev instead of
1.14rc?

**Comment by aphelionz** [comment]
@zhiyuli That is correct. This branch will be merged back into develop once it's deployed.

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
