### PR TITLE
Bdbag minid

### PR DESCRIPTION
**Pull request by ismagilani**
### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by aphelionz** [comment]
Hi! What is this? :)

**Comment by ismagilani** [comment]
This is a pull request for @hyi to review the bdbag and minid work so we can deploy it to a local server for further testing.

**Comment by ismagilani** [comment]
Closing this pull request since it's against the wrong repo.

**Comment by hydrobuild** [comment]
Build finished.

**Pull request closed without merging**
