### PR TITLE
Remove useless index step

### PR DESCRIPTION
**Pull request by alvacouch**
This removes a useless, non-functional SOLR index step inside ./hsctl rebuild

### CODE REVIEW

**Comment by aphelionz** [comment]
@alvacouch @phuongdm Jenkins is still taking a heck of a long to build...

http://ci.hydroshare.org:8080/job/hydroshare-pull-requests/1271/

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz These are mostly iRODS user zone test failures that have nothing to do with SOLR. I don't see how my changes can "cause" them.

**Comment by aphelionz** [comment]
Didn't say "cause" once. Just noting that the errors are occurring.

**Comment by alvacouch** [comment]
@aphelionz I ran tests on cuahsi-dev-1 and had five failures of composite resource, all with "malformed JSON" errors. 
```
ERROR: test_set_file_type_to_file_with_missing_abstract (hs_file_types.tests.test_reftimeseries_metadata.RefTimeseriesFileTypeMetaDataTest)
ERROR: test_set_file_type_to_file_with_missing_keywords (hs_file_types.tests.test_reftimeseries_metadata.RefTimeseriesFileTypeMetaDataTest)
ERROR: test_set_file_type_to_file_with_missing_title (hs_file_types.tests.test_reftimeseries_metadata.RefTimeseriesFileTypeMetaDataTest)
ERROR: test_set_file_type_to_refts (hs_file_types.tests.test_reftimeseries_metadata.RefTimeseriesFileTypeMetaDataTest)
ERROR: test_set_file_type_to_refts_res_metadata (hs_file_types.tests.test_reftimeseries_metadata.RefTimeseriesFileTypeMetaDataTest)
```
and then for all of these, something like: 
```
  File "/hydroshare/hs_file_types/models/reftimeseries.py", line 766, in set_file_type
    raise ValidationError(ex.message)
ValidationError: [u'Invalid json file. Invalid method link found']

```

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
This version includes @hyi 's recommendations for adding apt-get update. That fixed Jenkins.

**Pull request merged**
