### PR TITLE
[#1184] Sharing status can now be changed in view mode.

### PR DESCRIPTION
**Pull request by mauriel133**
Also includes updates to some icons in top right bar.

### CODE REVIEW

**Comment by pkdash** [comment]
@xuezhaokun Can you review this?

**Comment by xuezhaokun** [comment]
@pkdash @mauriel133  I am not quite familiar with this part of content. I am not sure how to test it. But only based on the html and css code part, it looks good for me. +1.

**Comment by pkdash** [comment]
@mauriel133 Looks like you need to fix the failing checks.

**Comment by mjstealey** [comment]
> Looks like you need to fix the failing checks.

Failing check is sax parsing related (can be ignored): http://ci.hydroshare.org:8080/job/github-pr-builder-hydroshare/132/testReport/junit/hs_core.tests.serialization.test_resourcemeta_sax_parsing/TestGenericResourceMetaSax/test_sax_parsing/

**Comment by pkdash** [comment]
@mjstealey Thanks for reminding about this annoying test failure. @mauriel133 You can then merge this PR.

**Pull request merged**
