### PR TITLE
Disabling Captcha

### PR DESCRIPTION
**Pull request by aphelionz**

### CODE REVIEW

**Comment by Maurier** [comment]
@aphelionz is this deployed in a sandbox?

**Comment by Maurier** [comment]
@aphelionz the changes you've made will do the trick. However, the script is still being called and the recaptcha request is still being made. This will be a problem if the service starts working again unexpectedly. 

I suggest commenting out the following instances of this work:

https://github.com/hydroshare/hydroshare/blob/master/theme/templates/accounts/sign_up_form.html#L51

https://github.com/hydroshare/hydroshare/blob/master/theme/templates/accounts/sign_up_form.html#L61

https://github.com/hydroshare/hydroshare/blob/master/theme/templates/accounts/sign_up_form.html#L67

https://github.com/hydroshare/hydroshare/blob/master/theme/templates/accounts/sign_up_form.html#L100

https://github.com/hydroshare/hydroshare/blob/master/theme/templates/accounts/sign_up_form.html#L160

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@Maurier You can see it at dev-hs-2.cuahsi.org

**Review by Maurier — APPROVED** [review]
Approved

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hyi** [comment]
@aphelionz Not sure whether this was the reason why my quota PR https://github.com/hydroshare/hydroshare/pull/2525 build was bailed out strangely and output one failure check without any test failure or pep8 failure. I'll wait for this PR to merge, then merge my quota branch with develop to trigger the quota PR build again hoping to pass the Jenkins check then. In the meantime, if adding a check to signup form indicating "I am not a robot" is easy to accomplish and can be done within a couple of hours, I'd suggest to add that check into this PR to minimize potential for web crawler attack.

**Pull request closed without merging**
