### PR TITLE
Moved tabs content back to genericresource.html

### PR DESCRIPTION
**Pull request by mauriel133**
This fixes the issues with the resource specific tab not rendering its content. #984
Can be tested at https://riverdev.hydroshare.org

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@mohamedmorsy, @Castronova , @zhiyuli, @gantian127 and @hyi  Can you please check if the resource landing page (both in view and edit mode) is working for your resource type at https://riverdev.hydroshare.org ?

**Comment by zhiyuli** [comment]
@mauriel133 @pkdash 
I found the following issues on riverdev:
1) the "EDIT" button is not working on all existing resources I own. so I cannot check if the edit mode. but if I create a new Generic res, the edit button worked at first, once I completed all required metadata the edit button stopped working.
2) The RefTS "Download" button is still not working, which I think it is also relate to the recent refactoring of the template (see #985). PS looks like the RefTS is not added into Permission box on admin page (I tried but the default admin password does not work on riverdev).

**Comment by mjstealey** [comment]
> 2) The RefTS "Download" button is still not working, which I think is also relate to the recent refactoring of the template (see #985). PS looks like the RefTS is not added into Permission box on admin page (I tried but the default admin password does not work on riverdev).

This may have something to do with the **Hydroshare Authors** group (image below).
The group has since been updated with all ref_ts references.

screen shot 2016-02-18 at 10 33 05 am

This was deployed using a copy of www resources, which means it has the www users, and as such, the admin password is far more secure.

If you want to use the default admin user you would want to redeploy without using www resources.

**Comment by zhiyuli** [comment]
@mjstealey can you please add RefTS into Hydroshare Authors on riverdev? thanks

**Comment by mjstealey** [comment]
> can you please add RefTS into Hydroshare Authors on riverdev? thanks

Already done [Reference](https://github.com/hydroshare/hydroshare/pull/991#issuecomment-185779437)

**Comment by zhiyuli** [comment]
@mjstealey  Thanks.

@mauriel133 @pkdash The RefTS button is still not working as expected. Currently it just downloads the original bag stored on irods. But for RefTS, we overrode this Download button in our resource template to retrieve the timeseries data from another source (HydroServer) on the fly. See this line
https://github.com/hydroshare/hydroshare/blob/develop/ref_ts/templates/pages/reftimeseriesresource.html#L3

Before the template refactoring it was working. So I think we should not only move tabs content back to genericresource.html, but also move the block {% block download_bag %} back.

**Comment by mauriel133** [comment]
I moved the content section and redeployed.

**Comment by zhiyuli** [comment]
@mauriel133 
The ref_ts button works as expected now. 
But the issue 1 mentioned above is still there:
1) the "EDIT" button is not working on all existing resources I own. so I cannot check the edit mode. but if I create a new Generic res, the edit button worked at first, once I completed all required metadata the edit button stopped working.

**Comment by mjstealey** [comment]
> But the issue 1 mentioned above is still there

Since this was redeployed, the **ref_ts** permissions needed to be added into **Hydroshare Author** again.

This will happen every time a branch is deployed using www resources as the base database is from www itself, and has no knowledge of any new features added beyond what version www is presently running.

If you require admin access to the deployed instance, you will need to deploy using the default database (uncheck USE_WWW_RESOURCES).

**Comment by mauriel133** [comment]
I found out and fixed a layout issue that was hiding the edit button a little bit.

**Comment by zhiyuli** [comment]
@mauriel133 
I tested geog. feature, web app, refts and script. they are working as expected now.

found another issue (no related to this issue)
refts and script need new icons
image

**Comment by gantian127** [comment]
@mauriel133 I just tested raster and netcdf. They work as expected. Thanks

**Comment by mauriel133** [comment]
I see, I will design those tonight. Thanks.

**Comment by mohamedmorsy** [comment]
@pkdash @mauriel133  I tested the Model resource types and everything works as expected.

**Comment by pkdash** [comment]
Thanks @mohamedmorsy for testing this.

**Comment by pkdash** [comment]
TimeSeries resource type seems fine on the new landing page.

**Comment by pkdash** [comment]
@mauriel133 Are you still working on this branch?

**Comment by mauriel133** [comment]
I haven't made additional changes. If everything is working feel free to merge.

**Comment by hyi** [comment]
@mauriel133 Could you further change info-group style class to accommodate two more buttons for publishing resource and versioning resource, respectively? Probably ```width: calc(100%-300px)``` would be sufficient for two additional buttons. This would fix the issue of some portion of "edit button" non-clickable @dtarb found on beta where resource publication was deployed. It'd be great if you can address this in this branch to make "edit" button works well when publish button shows up so that I don't have to create a separate branch just for this. Thanks.

**Comment by mauriel133** [comment]
I increased the size to width: calc(100%-220px) which should be enough space for 5 buttons.

**Comment by pkdash** [comment]
+1

**Pull request merged**
