### PR TITLE
[WIP] Constrained tracked fields

### PR DESCRIPTION
**Pull request by jbradberry**
The Use Tracking report is intended to have grouping of usage by user type, by country, by state, and by organization.  In order to avoid spurious extra groups based on variations in spelling and wording, these fields on the user profile should be validated against a set of entities.
- user type: a set of choices, which were taken from the current html form's select values.  The 'Other' type has been split out into its own free-form text field.
- state: django-localflavor has been brought in as a dependency, and the profile edit form now uses the USStateField from that project to validate that the entry is a valid US state or territory.
- country: django-countries has been brought in as a dependency, CountryField is now being used.
- organization: to be split out into its own Django model.  The profile edit form perhaps should be enhanced so that users can create a new Organization if theirs does not appear in the list.

### CODE REVIEW

**Comment by jbradberry** [comment]
@mjstealey @hyi @pkdash This is still a work in progress, but it is perhaps time to get a design review.

**Comment by mjstealey** [comment]
@jbradberry - would it be possible to suppress the upcoming heartbeat monitoring from being tracked?

Otherwise we'll have interactions like this occurring every 5 minutes.
Excerpt from [https://beta.hydroshare.org/tracking/reports/history/](https://beta.hydroshare.org/tracking/reports/history/)
```
9,9,2016-06-27 20:25:00.190579+00:00,2016-06-27 20:25:00.192209+00:00,begin_session,None,none
9,9,2016-06-27 20:25:00.190579+00:00,2016-06-27 20:25:00.193797+00:00,visit,Text,/heartbeat/
10,10,2016-06-27 20:27:00.199648+00:00,2016-06-27 20:27:00.201444+00:00,begin_session,None,none
10,10,2016-06-27 20:27:00.199648+00:00,2016-06-27 20:27:00.203454+00:00,visit,Text,/heartbeat/
11,11,2016-06-27 20:29:00.213294+00:00,2016-06-27 20:29:00.215004+00:00,begin_session,None,none
11,11,2016-06-27 20:29:00.213294+00:00,2016-06-27 20:29:00.216926+00:00,visit,Text,/heartbeat/
12,12,2016-06-27 20:31:00.215606+00:00,2016-06-27 20:31:00.218237+00:00,begin_session,None,none
12,12,2016-06-27 20:31:00.215606+00:00,2016-06-27 20:31:00.220887+00:00,visit,Text,/heartbeat/
13,13,2016-06-27 20:33:00.199975+00:00,2016-06-27 20:33:00.201748+00:00,begin_session,None,none
13,13,2016-06-27 20:33:00.199975+00:00,2016-06-27 20:33:00.203682+00:00,visit,Text,/heartbeat/
14,14,2016-06-27 20:35:00.201555+00:00,2016-06-27 20:35:00.203178+00:00,begin_session,None,none
14,14,2016-06-27 20:35:00.201555+00:00,2016-06-27 20:35:00.204942+00:00,visit,Text,/heartbeat/
```

**Comment by jbradberry** [comment]
@mjstealey oh, sure, I think I can turn that off.

**Comment by mjstealey** [comment]
@jbradberry - Error from build looks to be: [from console](http://ci.hydroshare.org:8080/job/github-pr-builder-hydroshare/237/console)

```python
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/django_nose/management/commands/test.py", line 28, in <module>
    TestRunner = get_runner(settings)
  File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 152, in get_runner
    test_module = __import__(test_module_name, {}, {}, force_str(test_path[-1]))
  File "/home/docker/hydroshare/hs_core/tests/__init__.py", line 1, in <module>
    from .api.native import *
  File "/home/docker/hydroshare/hs_core/tests/api/native/__init__.py", line 3, in <module>
    from test_comment_on_resource import *
ImportError: No module named test_comment_on_resource
```

**Comment by jbradberry** [comment]
@mjstealey except that I haven't removed test_comment_on_resource.py

**Comment by mjstealey** [comment]
> except that I haven't removed test_comment_on_resource.py

I've c/p'd this into the wrong PR... should be associated with: #1334

**Comment by jbradberry** [comment]
@mauriel133 : I've spoken with @hyi, and she suggested that I reach out to you.  I could use some assistance in getting the autocomplete that I've set up for organizations hooked up properly in the front end of the profile edit page.  Can you give me a hand?  cc @dtarb

**Comment by mauriel133** [comment]
@jbradberry, I can help you with this. I'm trying to setup the project on a VM and will let you know once I'm ready to start.

**Comment by mauriel133** [comment]
@jbradberry, I am ready to work on this issue. Is this going to be a select + autocomplete? (see https://silviomoreto.github.io/bootstrap-select/examples/#live-search)

**Comment by jbradberry** [comment]
@mauriel133 Yes, that seems right.

**Comment by mauriel133** [comment]
@pkdash, @jbradberry how can I use the view  that has been setup for Organization in order to get the items for the autocomplete?

**Comment by jbradberry** [comment]
@mauriel133 I believe the correct way to get at the url for this view in the templates is like so: https://github.com/hydroshare/hydroshare/pull/1303/files#diff-acab99d87d8bf9b9c86db2a52284c7f9R1201 .  This seems to be pulling down my test Organizations anyway.

In terms of hooking it up, perhaps this will be useful: http://django-autocomplete-light.readthedocs.io/en/2.0.9/cookbook.html#low-level-basics .  I'm more used to being able to just provide the autocomplete field in a Django backend form, so with all of the custom html going on here I've been at a bit of a loss.

**Comment by mauriel133** [comment]
Now, what still needs to be done to the field? I see that the autocomplete is set up, although no options are returned yet in my case.

**Comment by jbradberry** [comment]
So if some Organizations are created (by, say, filling in some text in the field and saving without worrying about the autocomplete), those should become available for later edits.  However, I find that while I do get the items in the pulldown when the text I start to type matches, I am unable to actually select one of the options.  Something just isn't hooked up quite right.  Also, if an Organization has been saved on a profile, it should be visible to start with in the field in a subsequent edit, and that isn't the case.

**Comment by mauriel133** [comment]
@jbradberry ,

@pkdash and I figured out the issue saving and loading the items. We are now working on the problem with selecting an item from the dropdown and populating the field. I will push the changes once we figure out the remaining issue.

**Comment by mauriel133** [comment]
@jbradberry, @pkdash and I have implemented some changes to make the autocomplete work. It works as expected in my local environment. Please review the changes and see if they work on your end.

**Comment by mauriel133** [comment]
On another note, when I try to user my other branches after working on this one I get the following error after the 'hsctl rebuild --db' command runs.

image

Do you know how I could solve this?

**Comment by jbradberry** [comment]
@mauriel133 You'll have to delete your pyc files.

    find . -name '*.pyc' -delete

**Comment by mjstealey** [comment]
migrated to a different branch and already merged

**Comment by pkdash** [comment]
@mjstealey 

> migrated to a different branch and already merged

According the @mauriel133 this work is missing in our develop branch. Any recollection why it might not have been merged?

**Pull request closed without merging**
