### PR TITLE
4652 Model Program Resource type remove

### PR DESCRIPTION
**Pull request by pkdash**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Follow the steps below to locally test this:
2. Checkout develop branch and run hydroshare.
3. Create a composite resource. Create a model program aggregation in that resource. Add some metadata for this aggregation.
4. Checkout the branch '**4652-model-program-resource-type-remove**'. Run `./hsctl managepy migrate`.
6. Verify that you can see model program aggregation and its metadata. Verify that you can edit metadata for the aggregation. 
7. Verify you can create new model program aggregation.

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4734](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4734)

**Comment by pkdash** [comment]
@sblack-usu Thanks for reviewing all these deprecated model resource PRs. This one is the last one for your review.

**Comment by pkdash** [comment]
@sblack-usu Would like get this last one in release 1.58

**Review by sblack-usu — APPROVED** [review]

**Comment by pkdash** [comment]
Thanks @sblack-usu for reviewing all my PRs.

**Pull request merged**
