### PR TITLE
By default discovery page shows all results until you filter them

### PR DESCRIPTION
**Pull request by ironfroggy**

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@mauriel133 Can you review this? Would appreciate if you can review it soon. Thanks.

**Comment by pkdash** [comment]
@alvacouch Probably needs to review this too.

**Comment by mauriel133** [comment]
@ironfroggy, I deployed this on https://riverdev.hydroshare.org. Some issues:

- When checking an option on the left panel and no resources are returned, hence getting the "No results found" message, it is difficult to bring back the previous default list. I tried clicking the "clear all" button and refreshing the page. The only thing that restores the previous state is clicking the Discover item in the navigation bar again. 

- Clicking on "Next" in the pager takes me to an empty page with a label that says "Discovery"

If any of these is not in the scope of this PR let me know.

**Comment by pkdash** [comment]
@mauriel133 I think it is ready for another round of review.

**Comment by mauriel133** [comment]
Alright, I will review once the VMs are back up because I need to deploy it to test.

**Comment by ironfroggy** [comment]
Closing this has @xuezhaokun and @alvacouch have picked up the task as part of their work and are in-progress

**Pull request closed without merging**
