### PR TITLE
[#3226] IE11 Workaround for default function parameter values

### PR DESCRIPTION
**Pull request by Maurier**
IE11 does not behave well with default parameter values in JavaScript functions. A workaround has been implemented to prevent the script from crashing.

image

This PR also updates the selectors of autocomplete inputs. This way their placeholder values will now properly read "Search by name or user name" or "Search by group name".

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Create a resource
2. Use the Manage Access window to add access to some user.
3. Verify that autocomplete inputs respond correctly to user input.

### CODE REVIEW

**Comment by Maurier** [comment]
@engineSound Could you review this work? You will need to test this in the latest version of Internet Explorer 11

**Comment by engineSound** [comment]
@Maurier You caught me on this. I don't have the windows machine. Can someone else test this?

**Comment by Maurier** [comment]
@engineSound No problem. 

@sblack-usu, could you have a look?

**Comment by cuahsimarko** [comment]
@engineSound can probably use this https://developer.microsoft.com/en-us/microsoft-edge/tools/

**Comment by engineSound** [comment]
@cuahsimarko Good idea! The tools are free to open source project. It requires a formal application. It doesn't let me use edge 11 unless I upgrade to a paid plan.

**Comment by engineSound** [comment]
@Maurier Phuong is helping me to locate an IE 11 in windows 7 VM. Then I can port your change into my dev machine. Then test it out.

**Comment by Lizabrazil** [comment]
@engineSound you can borrow a windows laptop from @phuongdm

**Comment by engineSound** [comment]
Verified on IE11 on windows 10.

**Pull request merged**
