### PR TITLE
WIP - 945 django mezzanine update

### PR DESCRIPTION
**Pull request by mjstealey**
Update to Django 1.8 and Mezzanine 4.1.0.  The tentative plan for applying the upgrade to develop and production is:

1. Make sure all existing HydroShare-specific migrations have been applied to the database
2. Delete all HydroShare-specific migration files
3. Run `makemigrations` to pick up schema changes to Django 1.8 and Mezzanine 4.1.0
4. Run `migrate` to apply migrations
5. If errors are present when running `migrate`: write data migrations to correct the schema, then GOTO step 4.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by selimnairb** [comment]
Things to do prior to actual upgrade:

- [ ] Remove ga_resources app
- [ ] Remove ga_ows app

**Comment by mjstealey** [comment]
submodule for hs_docker_base: https://github.com/hydroshare/hydroshare/tree/submodule-for-hs-docker-base

**Comment by mjstealey** [comment]
New PR using new branch

**Pull request closed without merging**
