### PR TITLE
Fix discovery blank page issue 

### PR DESCRIPTION
**Pull request by xuezhaokun**
Fixed issue #1203

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@zhiyuli Can you review this?

**Comment by pkdash** [comment]
@hyi Can you review this small PR? @zhiyuli did not feel comfortable reviewing this as he knows little about discovery.

**Comment by hyi** [comment]
@xuezhaokun @pkdash I can see why the changes are being made this way to fix this issue, and don't see any issues with the changes, so I am giving +1 here assuming @xuezhaokun has already tested it out to make sure the issue is fixed by the changes made here to form request search URL more robustly.

**Comment by xuezhaokun** [comment]
@hyi Thanks for the review! I have tested this code before I committed it.

**Comment by pkdash** [comment]
@xuezhaokun You can merge this PR now.

**Pull request merged**
