### PR TITLE
Added Published Date and Meta Data Update in Last Updated

### PR DESCRIPTION
**Pull request by MSDrao**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

Steps:

Create a Resource: Create a new resource (not yet published).
Check Before Publication: Verify ***last_updated*** is set, and no ***published_date*** exists.
Publish Resource: Publish the resource.
Expected: last_updated equals ***published_date***. No red "(Metadata update)" flag.
Modify After Publication: Edit the resource metadata (e.g., change the title).
Expected: last_updated changes, and the red "(Metadata update)" flag appears.

Postconditions:
No metadata update flag immediately after publishing.
Metadata update flag appears only after post-publication modifications.

- [x] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by devincowan** [comment]
@MSDrao this looks pretty good, nice work!
The only thing I see is that the red "(metadata update)" will _ALWAYS_ show after publication. This is due to the following lines:
https://github.com/hydroshare/hydroshare/blob/msd-published/hs_core/hydroshare/resource.py#L1163-L1173
where we call `resource_modified()` in line 1173 **AFTER** we do `resource.metadata.create_element('date', type='published', start_date=resource.updated)` in line 1163.

I think the desired behavior would be to set the `last_updated` to be the same as the `published` date during publication. And this way the red "metadata update" notification would only show in the case that a user had actually edited metadata after publication. We can discuss on today's call perhaps

**Review by devincowan — COMMENTED** [review]
@MSDrao this is looking good. The only thing is to make sure you fill in the "checklist" 
https://github.com/hydroshare/hydroshare/pull/5606#issue-2553763997
This is our best practice, though admittedly I haven't been lately so I'm not providing a good example!

**Review by devincowan — APPROVED** [review]

**Comment by hydrocheck** [comment]
Should we be using consistent datetime formats across the header fields?

Screenshot 2024-11-05 at 11 52 23 PM

**Comment by hydrocheck** [comment]
Also, is the red font truly what we want here for the "(Metadata update)"? The red text from Dave seemed to clarify the additions, rather than the actual font style. https://github.com/hydroshare/hydroshare/issues/5410#issuecomment-1988729904

My two cents is that we don't draw so much attention, and shift this to black.

**Pull request merged**
