### PR TITLE
2308 fix missing discovery results

### PR DESCRIPTION
**Pull request by alvacouch**
This fixes several search box anomalies, notably, missing results when one searches for uncommon things like first name.

### CODE REVIEW

**Comment by alvacouch** [comment]
@aphelionz This is a good starting point for fixing more problems. AFAIK, the results are now correct and the UI poses the remaining problems.

**Comment by aphelionz** [comment]
@alvacouch This looks good to me. Should we alert anybody else to review this?

**Comment by aphelionz** [comment]
@alvacouch please merge when ready

**Comment by alvacouch** [comment]
@aphelionz Repurposing cuahsi-dev-1 for performance testing.

**Pull request merged**
