### PR TITLE
Add solr pytest

### PR DESCRIPTION
**Pull request by cuahsimarko**
A PyTest for Dan to test environments with 3936-discovery-backend-improvements

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4086](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4086)

**Comment by alvacouch** [comment]
@cuahsimarko Can't figure out how to run this. Usage?

**Comment by cuahsimarko** [comment]
@alvacouch You enter the container and run PyTest in the repo folder. I use PyCharm for this, and there is also a way to use docker commands to run it from the host.

**Comment by cuahsimarko** [comment]
It also looks like people have developed shell files that Jenkins uses for this purpose.

**Pull request merged**
