### PR TITLE
[#669] remove migration scripts from repo

### PR DESCRIPTION
**Pull request by mjstealey**
Removed migration scripts from repository

### CODE REVIEW

**Comment by selimnairb** [comment]
Looks good to me as all content removed is now in the lifeboat repo.  +1 to merge.  @hyi Can you merge?

**Comment by hyi** [comment]
@mjstealey @selimnairb  I merged this into develop branch, should we also merge this into master as well? If so, I can restore the 669 branch and create a PR for you to merge it into master, or whatever way you think is best to accomplish this.

**Comment by mjstealey** [comment]
@hyi @selimnairb - The migration-scripts directory was manually removed from the repo on www already, so it wouldn't be required for deployment purposes.

If you want to stage a 1.6.1 RC that may be a reason to pull this into master, but otherwise I don't think it's an issue.

**Comment by hyi** [comment]
@mjstealey I meant to remove migration-scripts directory from master branch of hydroshare repo as shown here: https://github.com/hydroshare/hydroshare/tree/master/migration-scripts. If the directory is already removed, perhaps it is just easiest to push it directly to master branch to have that migration-scripts directory removed from master branch?

**Pull request merged**
