### PR TITLE
fixed issue [#703] to allow anonymous users to download public bags

### PR DESCRIPTION
**Pull request by hyi**
@selimnairb @ironfroggy @robline please review this PR ASAP so that it can be merged in for a release 1.6.1 hot fix on www.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
This branch was manually tested on alpha and seems to have resolved this issue. This branch was also tested with jenkins for rest api calls which showed one failure similar to the current develop branch. Therefore, the rest api test failure is not related to this hotfix. 
+1

**Comment by selimnairb** [comment]
@hyi Sorry was at a conference yesterday.  I'll look at this this afternoon while I am working on REST issues.

**Comment by selimnairb** [comment]
@hyi @mjstealey @pkdash I can verify that this change does not cause any problems with the REST API.

**Comment by hyi** [comment]
@selimnairb good to know. Thanks for verifying this.

**Pull request merged**
