### PR TITLE
1.15 rc2

### PR DESCRIPTION
**Pull request by cbcunc**
## PR Checklist for RC2

*Please review your items on this checklist and check them off on the list when you have verified their functionality on https://beta.hydroshare.org*

- [x] Fix for creator/contributor identifier bug #2672 (@pkdash)
- [x] [#2653] update the create resource help page #2667 (@sblack-usu)
- [x] [#2567] expose folder downloading to rest api and update file url i… #2664 (@sblack-usu)
- [x] [#2478] resend activation email #2654 (@sblack-usu)
- [x] Adding blank issue and pull request templates #2650 (@aphelionz)
- [x] Add javascript to reset map list. #2649 (@alvacouch)
- [x] Keep management commands from crashing unexpectedly in unusual situations. #2642 (@alvacouch)
- [x] [#1867] email subscribe #2640 (@sblack-usu)
- [x] HOTFIX-1.15-RC1-fix for author optional identifier xml encoding #2634 (@pkdash)
- [x] GET and PUT Endpoints for File Metadata #2633 (@aphelionz)
- [x] [HOTFIX] - add the merge migration #2632 (@sblack-usu)
- [x] [#2590] - increase time for group email links expirary #2631 (@sblack)
- [x]  [#2567] download folder zips #2626 (@sblack-usu)
- [x] [#2474] Fix for appearing horizontal scrollbars #2625 (@Maurier)
- [x] [#2607] Removing unnecessary Save step in workflow (@Maurier)
- [x] [#1666] point to latest django irods #2622 (@sblack-usu)
- [x] [HOTFIX][#2615] Fix for Authors and Owners listing #2618 (@Maurier)
- [x] [HOTFIX][#2615] Author and owner listing fix on hover and click behavior (@Maurier)
- [x] Update utils.py #2616 (@aphelionz)
- [x] [HOTFIX] Resolve merge conflict preventing 1.15 build #2613 (@alvacouch)
- [x] Adding recaptcha2 back to signup #2598 (@aphelionz)
- [x] Hotfix disable captcha 2 (@aphelionz)
- [x] Disabling Captcha (@aphelionz)
- [x] Adding more messaging to DOI reservation #2589 (@aphelionz)
- [x] [#2562] add abstract to resource list #2588 (@aphelionz)
- [x] Swagger needs these to be explicit lists #2587 (@aphelionz)
- [x] Minor theme change to 'reserve' DOI #2586 (@aphelionz)
- [x] [#2426] discovery phrase matching #2578 (@alvacouch)
- [x] Allowing supports_folders for CompositeResource #2561 (@aphelionz)
- [x] [#2147] generate iRODS tickets #2198 (@alvacouch)
- [x] [#2537] folder permissions (@aphelionz)
- [x] new gitignore changes #2555 (@aphelionz)
- [x] Fixing scimeta root endpoint (@aphelionz)
- [x] Updating admin.py to add email field #2550 (@aphelionz)
- [x] doing apt-get update before doing apt-get install #2542 (@hyi)
- [x] [#2116] Responsive layout fixes #2541 (@Maurier)
- [x] Remove useless index step #2532 (@alvacouch)
- [x] Merging Master back into Develop #2528 (@aphelionz)
- [x] Fixing org page again #2526 (@aphelionz)
- [x] [#1566] quota #2525 (@hyi)
- [x] Optional author identifiers #2524 (@Maurier )
- [x] Hotfix sign up org bug #2523 (@aphelionz)
- [x] 1.15 rc2 hotfix keyerror #2699 (@aphelionz)
- [ ] Adding DOI to resource listing API #2693 (@aphelionz)

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by dtarb** [comment]
Issues identified testing beta.hydroshare.org

1. Attempt to create an account with “Brigham Young University” as organization results in error.  Can we get the fix to #2673 that @sblack-usu has worked on into this deploy. 
image

Curious thing - an account did actually end up being created, because when I tried again I could not reuse the same email but had to reset the password, and when I got in it said my institution was BYU.

2. The way users are listed if you go in as admin has changed.  On beta you get
image
On www you get
image
Thus on beta it is not possible to sort by date and find recently created accounts to resolve problems (or delete a test one)

3. Quota messaging needs love and care.  When I log in I get 
image
“Your action to add content …” makes no sense because the only action I did was to log in.  Also the  message refers to support@hydroshare.org and mentions pages.hydroshare.org.  We are now using help@cuahsi.org, and help.hydroshare.org. 

We have discussed the right tone for these messages quite a bit.  My latest suggestions were in an email message on 2/14/18 in a document [QuotaMessages.docx](https://drive.google.com/file/d/1C0zAsB3IzJi4peMqoPBj94nWkQcOKMUn/view), that I have now just uploaded to Google.  This is important because it is a public relations issue.  We do not want to appear draconian when we roll out quotas.

I am actually able to create new resources (despite the message), and do not get a warning despite being over quota.  The quota warning appears only when I log in.  I also do not get emails warning me about over quota.  

Related quota issues are #1566, #2196, #2605, #2606.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@cbcunc It looks like the build is timing out... can you have a look?

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
retest this, please

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
