### PR TITLE
HOTFIX-Set flag to regenerate metadata xml on bulk metadata update

### PR DESCRIPTION
**Pull request by pkdash**
This hotfix needs to be applied to master. Once I get +1 I will ask @mjstealey to do this merge.

### CODE REVIEW

**Comment by pkdash** [comment]
@hyi Can you review this small PR?

**Comment by pkdash** [comment]
@mjstealey I would have liked to deploy this work for testing by @yirugi before applying this as a hotfix to master.

**Comment by pkdash** [comment]
@aphelionz Can you look at this PR and decide if we should make it a hotfix or not?

**Comment by aphelionz** [comment]
@pkdash Go for it - hotfix.

**Comment by pkdash** [comment]
@mjstealey can you merge this to master and then update www? This PR has been created from master.

**Comment by mjstealey** [comment]
@pkdash - Please verify that fix has been properly applied to www

**Comment by pkdash** [comment]
@mjstealey Thanks. Will do the checks.

**Pull request merged**
