### PR TITLE
remove the ambiguous options for "Map Results" and "All Results"

### PR DESCRIPTION
**Pull request by xuezhaokun**
- This PR fixed issue #1563 
- Basically, the "Map Results" option on list view is a duplicated function to the table under the map. So I just removed all code related to it. 

- This PR also fixed an issue related "reset map zoom" button on the map.

- This PR also removed the unused "rectangle" object on map.

### CODE REVIEW

**Comment by pkdash** [comment]
@mauriel133 Can you review this small PR?

**Comment by mauriel133** [comment]
Looks good. +1

**Comment by pkdash** [comment]
@xuezhaokun Seems this PR is ready for merge.

**Comment by xuezhaokun** [comment]
@pkdash @mauriel133 Thanks! Merged.

**Pull request merged**
