### PR TITLE
[#4846] hs_discover static files

### LINKED ISSUE #4846: JS errors loading chunk_vendors on Discover page
**Description of the bug**
image

Steps to reproduce the bug:
1. Open developer console
2. https://www.hydroshare.org/search/

**Expected behavior**
Chunk_vendors should be loaded with the correct mime type (if that's the issue) and no uncaught JS errors [loading Vue](https://github.com/hydroshare/hydroshare/blob/1.61/theme/templates/includes/navbar.html#L487)

### PR DESCRIPTION
**Pull request by devincowan**
Resolves #4846 
Note this PR will require modifications to `deploy.sh` on beta and prod

### Pull Request Checklist: 
- [X] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Run a full docker image rebuild and `docker-compose up`
2. Navigate to: localhost:8000/search/
3. No longer see js console errors

### Before:
image

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4978](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4978)

**Comment by devincowan** [comment]
adding @pkdash on this issue because @Maurier is having trouble getting Discover to build on his dev machine

**Comment by pkdash** [comment]
@devincowan I was able to build the vue component for search on windows. However, I still see the JS errors:

image

**Comment by devincowan** [comment]
@pkdash I still wasn't able to reproduce the MIME type warnings on my local builds but pushed https://github.com/hydroshare/hydroshare/pull/4978/commits/878fa9203c239787e6b7423f96054c0c17a224d6 thinking that might help.

**Comment by pkdash** [comment]
@devincowan I tried with the latest changes and still seeing those JS errors. I can help @Maurier to build the discover vue component so that he can try testing these errors.

**Comment by devincowan** [comment]
@pkdash and @Maurier thanks for taking a look at this
I'm still not able to reproduce the issues that Pabitra found,
but it is a low enough priority that I'm going to close this PR

**Pull request closed without merging**
