### PR TITLE
[#4474] hstools image upload (in addition to URL)

### LINKED ISSUE #4474: Allow local image file upload in addition to URL for tools resource
Currently the tools resource only allows icon to be added via URL.
We will also allow image file upload

### PR DESCRIPTION
**Pull request by devincowan**
### Pull Request Checklist: 
- [X] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Create a new tools (app) resource
2. Scroll to "icon" and select "Bowse for file"
3. Save changes

Resolves #4474

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4479](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4479)

**Comment by sblack-usu** [comment]
@devincowan - I'm trying to run this branch locally and I get an error when creating a web app connector.  Are you running into this as well?

**Comment by devincowan** [comment]
@sblack-usu thanks for the catch. I'll have to be more careful!
Merge conflicts should resolve using this branch overriding develop

**Review by sblack-usu — DISMISSED** [review]
I'm impressed you were able to work with the existing code so well.  Eventually I'd like to create a JSON schema for web app connectors to help clean this up.

**Review by sblack-usu — APPROVED** [review]

**Pull request merged**
