### PR TITLE
add filtering by published feature

### PR DESCRIPTION
**Pull request by xuezhaokun**
This PR is related to issue #1517 and #1185. 
Add "Published" as a value under the "Filter by Availability" facet

### CODE REVIEW

**Comment by pkdash** [comment]
@zhiyuli Can you review this?

**Comment by zhiyuli** [comment]
@xuezhaokun 
One question:  does the change to fields in file hs_core/search_indexes.py affect DB? or say do we need do migration for these changes? Please verify this before you merge it as I am not familiar with how the indexing works on backend.  Other changes look good to me. +1

**Comment by xuezhaokun** [comment]
@zhiyuli The change in hs_core/search_indexes.py does not  affect DB. It just tells SOLR what to index.
I just let SOLR to index and facet the "publsihed" field for me.

**Comment by zhiyuli** [comment]
+1

**Pull request merged**
