### PR TITLE
Adding/Deleting/Modifying authoring returns to the same place

### PR DESCRIPTION
**Pull request by engineSound**
### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
Add Author:
1. At resource landing page, scroll down to Authorship tab where you can see "Add Author" button.
2. Click the button, a dialog pops up,  add an author, and click "Save changes" button. The dialog is dismissed.
3. The browser refreshes, the page goes to Authorship tab.

Delete Author:
1. At resource landing page, scroll down to Authorship tab where you can see "Add Author" button. 
2. Locate one author you want to delete, click the delete icon.
3. The browser refreshes, the page goes to Authorship tab.

Edit Author:
1. At resource landing page, scroll down to Authorship tab where you can see "Add Author" button. 
2. Locate one author you want to edit, click the pencil icon. Edit the info of the author. Click "Save Changes" button. The dialog is dismissed.
3. The browser refreshes, the page goes to Authorship tab.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@engineSound Please investigate the failing test in Jenkins... let me know if you have questions.

**Comment by aphelionz** [comment]
@engineSound Did you mean to close and delete this?

**Comment by engineSound** [comment]
yes.

**Comment by engineSound** [comment]
This one is linked to a large scope effort  #[2556](https://github.com/hydroshare/hydroshare/issues/2556) and [#2557](https://github.com/hydroshare/hydroshare/issues/2557) and [#1099](https://github.com/hydroshare/hydroshare/issues/1099), and [#2829](https://github.com/hydroshare/hydroshare/issues/2829). 

Asynchronous call (Ajax) should be used to retrieve data from server and update the underlying webpage instead of doing a refresh or redirect.

**Pull request closed without merging**
