### PR TITLE
2426 discovery phrase matching

### PR DESCRIPTION
**Pull request by alvacouch**
@dtarb @aphelionz @Lizabrazil @Castronova This is an initial implementation of discovery phrase matching, including author:foo, subject:foo, etc. 

This is currently deployed on cuahsi-dev-1. The facets are deployed to indicate problems with faceting. See particularly: 

* About 80 resources have no first creator and they're public anyway. 
* Variable facet has variable codes as well as names. 
* Units name facet has misspellings of units. 
* This implements most of the wish list in [the wish list document](https://docs.google.com/document/d/1R2voxhb7rI2RNSWilc-tZy315_weUnYIGyt3rZRIdcE/edit).
* Field names are documented in [the field names spreadsheet](https://docs.google.com/spreadsheets/d/1cPJOm4I6n4_79XTJOWulE4xJuQkxGM8-bztVJLjt6fQ/edit?usp=docs_home&ths=true)

**Not all field names are currently exposed in the query language.** Current fields exposed include 
'title', 'author', 'creator', 'subject', 'variable', 'units', 'contributor', 'accessibility', 'created', 'modified', 'publisher', 'rating', 'resource_type', 'owner': 

| field | type | purport | modifiers |
|---|---|---|---|
| title | text | resource title | |
| author | text | first author | |
| creator | list of text | all authors | | 
| contributor | list of strings | all contributors | | 
| owner | list of string | all owners inside HydroShare | |
| publisher | string | publisher of resource | | 
| resource_type | string | verbose name of resource type  | |
| subject | list of text | all subjects | |
| variable | list of text | all variable names | |
| units | list of text | all units names | |
| accessibility | list of strings | public/discoverable/published | |
| created | date | date resource was created | __lt, __lte, __gt __gte |
| modified | date | date resource was last modified | __lt, __lte, __gt __gte |
| rating | integer | number of +1's |  __lt, __lte, __gt __gte |

### CODE REVIEW

**Comment by alvacouch** [comment]
@aphelionz I need help flashing an error message when query parsing fails. The error messages are ready. What is your current pattern for doing so?

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@pdoan Building is failing due to a github error; the build host seems to be out of space. Please look into this. 

@aphelionz @martinseul I would like to merge this as-is. The parser is up and running and many bugs in SOLR harvesting are also fixed. Many bugs in clientside JavaScript are also fixed. 

The only shortcoming of this solution is that whenever you type something the query parser doesn't understand, it simply returns no results. Error messages are generated but not returned to the user. IMHO this can wait. 

My logic for merging this at this point is that it won't do anything harmful, and we can allow people to experiment with the query system and tune it and document it. It will accept old queries and do the same thing. The only new features are that '(', ')', and ':' now do specific things, and the logical operators AND, OR, NOT are implemented. These can be documented fully in the next release after this one. 

@martinseul The only issue for me at this point is that I think I should turn certain facets off, on the grounds that their contents are embarrassing. These include variable, units, and author. I wish to replace author with contributor, which is anyone mentioned as contributing to the resource.  For the purposes of discovery, this includes creators and contributors.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@alvacouch I'm ok with merging for experimentation but not without the build host fixed first. Attn: @pdoab @cbcunc

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz Still needs a review.

**Comment by alvacouch** [comment]
@martinseul @aphelionz I killed the units facet which was just too embarrassing. The PR is ready for merge pending review.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz @pdoan The build worked this time. However, the parser is exhibiting strange behavior so this is not ready to merge. Writing a debugging scaffolding to figure it out. Behavior concerns commas in quoted phrases, e.g. author:"Tarboton, David" does not work as expected.

**Comment by dtarb** [comment]
As a Saturday morning joke I think you could extrapolate this to that the author David Tarboton never works as expected, with or without being qualified.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@dtarb @Lizabrazil @Castronova @aphelionz @martinseul 
OK, I've merged the last commit that I think is reasonable for this release. This is deployed on cuahsi-dev-1.hydroshare.org and I've tested it thoroughly, both through test cases and interactively.  

Wht this version does is documented here: 
https://docs.google.com/document/d/1GXld28UUwFMd6Beq7fMVb4TRdaDImZKb3XWlSQuNai0/edit?usp=sharing

Several changes from the specification make things a bit easier: 
* inequalities can be specified in algebraic form: `created:>1/1/2017` matches any resource that was created after 1/1/2017. The reason it is `:>` and not just `>` is to limit interaction with possible search strings that might themselves contain `>`!
* A large number of sanity checks have been written to ensure that we don't feed SOLR nonsense. These result in exceptions that are currently ignored, but should eventually be expressed to the user. For example, abstract:>foo is meaningless, while abstract:foo selects an abstract that contains the word foo.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@alvacouch See here: https://github.com/hydroshare/hydroshare/blob/f69090b6697ed4e1c2ea4bdf04d83b92baff8e1a/theme/static/js/custom.js#L189

You can use the `showUniversalMessage` function to display the errors to the user. The function signature is `showUniversalMessage(type, one of 'warn', 'error', or 'success', string message, display time in millseconds)`

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
Hi @alvacouch If this is on cuahsi-dev-1 still, I'd like @Lizabrazil to look at it before we merge.

**Comment by aphelionz** [comment]
Also @alvacouch , does this invalidate the requirements in https://github.com/hydroshare/hydroshare/issues/2464. That would be good to kill two birds with one stone, as it were.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz Error messages now appear immediately underneath the query bar in red. This is a little better than a popup. It persists until one types an appropriate query. 

I found and repaired a few bugs this morning. 

@Lizabrazil thinks we should subject this to QA before deploying to master.  In particular, she wants to tune the error messages and facets that are shown.

**Comment by alvacouch** [comment]
@aphelionz @Lizabrazil Bugs fixed: 

* creator:1/1/2017 now includes whole day. 
* creator:<=1/1/2017 is interpreted as creator:<1/2/2017 to pick up all 24 hours in the day. 
* relatively useless facets 'variable' and 'sample medium' omitted. 

I am out of time for today and must get to other things.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz @martinseul @Lizabrazil @Castronova @dtarb 
Following issues have been addressed. 

1. Better error messages for parser. 
2. Availability facet now works properly. 
3. "Filter by" => "Most frequent" in facets
4. Page controls at both top and bottom of page now. 
5. Choosing new page no longer causes complete page load. 
6. Choosing new sort order only reloads results. 
7. Choosing start date without end date now works and only reloads results.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@dtarb @aphelionz @martinseul @Lizabrazil @Castronova 

Martin and I considered the field names a bit and decided that a simple field called `person` could represent direct involvement of a person in any way with the resource, including roles of contributor, creator, owner, or editor.  `person` could replace all of this complexity with a single keyword. 

Do the rest of you agree?

**Comment by horsburgh** [comment]
@alvacouch - I think "person" potentially could work. But, including "editors" as part of this search might be confusing. There's no viewable metadata on a resource's landing page indicating that a person is an editor, so there may be items in the list returned by a search for which it would be unclear why they are there.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by dtarb** [comment]
@alvacouch None does not appear in www, yet it appears in this test machine.  Whatever has been done seems a bit regressive
image

**Comment by dtarb** [comment]
The search box appears below and magnifying glass on top of the information button.
image

**Comment by alvacouch** [comment]
@dtarb @aphelionz @martinseul @Lizabrazil @Castronova 
Changes: 

* Moved information box above field line (where it was before). 
* Changed "first author" facet to "any author" facet.
* 'Most frequent' => 'Frequent' 
* Edited help text. 

Results deployed to cuahsi-dev-1.hydroshare.org 

Offline, @dtarb and I have been discussing "filter by author" vs "frequent author". The fact is that SOLR is currently returning the 20 most frequent authors. So, if you're an author, and you don't appear, it's because you aren't "frequent" enough. If you want me to get rid of the "frequent", I suggest hiding the facet completely until there are less than 20 options. 

I tried several experiments with improving this and concluded that my experiments didn't improve anything. I tried sorting the authors into alphabetical order, and there are 400+ authors! Meanwhile, there are misspellings of authors' names that are in the metadata and show up in that list. I elected to leave the facets as before, because at least that hides the poor quality of author metadata. 

Long term, I suggest
* Using ORCIDs to clean up author records. 
* Hiding author facets entirely unless there are just a few options.
* Sorting the resulting author facets into alphabetical order. 
This is beyond what I signed up to do with query parsing!

**Comment by hydrobuild** [comment]
Build finished.

**Comment by dtarb** [comment]
The limitation to 20 authors is not present in the current deployment on www.  I counted up to 40 authors in www discovery before I stopped counting and there were many still to go.  A 20 author limitation appears to be being introduced with new changes, and I have to ask why and what motivated limiting the number of authors displayed in the author facet.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@dtarb @martinseul @aphelionz 

Performance motivated the changes, along with lack of metadata quality. I checked the old code and AFAIK it was defaulting to 20. 

I prototyped showing all authors in sorted order, and it was a bit embarrassing. It was considerably slower, and there is massive spurious duplication of names. 

Do you want to see that behavior for yourselves?

**Comment by alvacouch** [comment]
@dtarb @martinseul @aphelionz 
I just turned off facet limits and arranged to sort all facets alphabetically. This will show you what I am up against. It is deployed on cuahsi-dev-1.hydroshare.org but not pushed to github. 

You may need to exit your browser and restart it to see the effect. I had to.

**Comment by alvacouch** [comment]
@dtarb @aphelionz @martinseul I checked more carefully and the limit in the previous release was set to 100.

**Comment by dtarb** [comment]
@alvacouch I get that you are trying to demonstrate (I think) that arranging the facets alphabetically is not good.  There are multiple factors at play and we are suffering from fragmented and sometimes incorrect information (like the 20 limit that did not relate to my experience, and now is expressed as 100), and blending together of performance issues and presentation issues (like whether the header is Authors, or Most Frequent Authors).  I worry that this approach is inefficient.  I'd prefer if you could systematically reflect and step back and provide a holistic path forward rather than debating these points in a fragmented way without correct information in a pull request.

**Comment by alvacouch** [comment]
@dtarb @aphelionz @martinseul I haven't significantly changed faceting. I was trying to properly label what is present already. 

I am also trying to implement a query interface that has nothing to do with faceting. It is -- however -- driven by and sensitive to the way things are represented in facets. So there have been some normalizations. 

I think that the way things are now, the faceting labels are inaccurate and misleading. I put in the word "frequent" to make them less misleading. Otherwise people will wonder why they create something, make it public, and then **they aren't listed in the options for authors...**

That being said, the current cuahsi-dev-1.hydroshare.org and the GitHub repository now have the old labels on them.  At this point, the only differences between facets in the old and new versions are that

* The author facet contains all authors and not just first author now. @dtarb requested that. 
* human names have been normalized to Last, First, Middle and capitalized if someone didn't bother to capitalize them. **I needed this for query syntax.** 
* I just put in a last minute change so that `author:` now refers to all authors rather than just first author. So, **the labels on facets are consistent with the labels in the query language.**

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz wrote: Also @alvacouch , does this invalidate the requirements in #2464?

Sort of. See extended discussion in that issue of what is and isn't reasonable.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@dtarb @aphelionz @Lizabrazil @ChristinaB 
There is one remaining question in my mind about the query language. 

I can -- fairly easily -- get rid of the necessity for a colon after every field name in an inequality. It is about a day's work. The cost of this is that whenever something like `word>x` or `word<=x` appears, word will be treated as a field and not a search term. Right now, to get something to be treated as a field, one must put a colon after it.  Right now, `word:>=something` treats word as a field, while `word>=something` is treated as a search phrase. 

For example: 

| now   | after |
| ------- | ------- |
| created:>1/1/2017 | created>1/1/2017 |
| start_date:<=1/1/2017 | start_date<1/1/2017 |

I have no doubt that eliminating the `:` is more convenient. The question is whether the error messages that result when someone naively types > in a phrase will be too confusing. 

How likely is it for someone to type `>` or `<` as part of a thing to be searched? If it is extremely unlikely, then I think I should eliminate the `:`. If it is likely, then I should leave the `:`.

**Comment by dtarb** [comment]
@alvacouch this is really in the weeds.  I do not know that I have an informed opinion.  If there is a solution that follows standard best practices, that people may know, we should do that, but I cannot think when I have use > or < in a web search and certainly have not taken the time to figure out whether the syntax needs a :.

**Comment by alvacouch** [comment]
@dtarb @aphelionz @martinseul @Lizabrazil @Castronova 
As discussed on the call yesterday, I eliminated `:` from inequalities. I also updated the google docs documentation and @Lizabrazil's copy as well. 

Now all that remains is to: 

1. upload the documentation to hydroshare pages. 
2. embed the URL in the search help text.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz @martinseul I went through all discovery issues and marked the ones that I think I've addressed. 

I noticed an old issue #1142 and checked whether it was fixed. It wasn't. I got to the bottom of the behavior and made one small change to partly address issue #1142.

The short story is that a query into a faceted field is not treated as an exact match unless you explicitly use the `__exact` qualifier. More subtle, the `__exact` qualifier treats the text to be matched as "within" the target text. Thus `Model Instance Resource` matches `SWAT Model Instance Resource`. Just to make things more confusing, the `__startswith` qualifier -- that would seem to disambiguate -- tokenizes multi-word strings that are fed to it, so that: 
```
resource_type__startswith='Model Instance Resource'
```
is interpreted as 
```
resource_type__startswith='Model', 
resource_type__startswith='Instance', 
resource_type__startswith='Resource'
```
which is not what one means and gives empty results! 

Solution on stackoverflow is to change the tokenizer for the field, which is a bit much to do for this PR. 

Meanwhile, the current change of adding `__exact` to every query **limits** the behavior to what was reported in issue #1142. Prior behavior was worse than that. It was matching the tokens in the faceted returns out of order.

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
