### PR TITLE
[#1161] open with to show apps user selected

### PR DESCRIPTION
**Pull request by zhiyuli**
This PRs contains several updates to WebApp res type for AGU
1) open with list to show approved and/or user-selected apps #1161 
2) add a default icon base64 string when new webapp resources are created
3) improve/refactor code structure a little bit, which may help implementation of file-type level app launching after AGU

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by zhiyuli** [comment]
@aphelionz @pkdash 
Any of you have a chance to review this PR. It is being built on riverdev server. Thanks

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
