### PR TITLE
User quota refactor

### PR DESCRIPTION
**Pull request by hyi**
### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by hyi** [comment]
@sblack-usu This is the initial effort for user quota refactoring, mainly refactor user quota holder methods and rename AVU to metadata since AVU is iRODS specific and can be replaced with a generic term metadata. Let me know if you see any issues with the PR.

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4521](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4521)

**Review by sblack-usu — APPROVED** [review]
I like this refactor and the updated method names.

**Comment by sblack-usu** [comment]
Just to make sure I didn't miss anything in the PR.  Calculating the quota for linux is not implemented yet?

**Comment by hyi** [comment]
As far as I can see, calculating the quota for linux is not implemented and @alvacouch can chime in if this is not the case.

**Comment by hyi** [comment]
retest this, please

**Pull request merged**
