### PR TITLE
2451 make discover buttons work

### LINKED ISSUE #2430: Discovery page: "show all" button label is misleading
The "show all" actually just recomputes the facets according to the current search term. It should probably be labeled "update facets". 

There has been a bit of discussion about how facets should actually work. Currently they are updated only when one enters a new search term in the text box. This was to avoid confusion when facets change a lot. However, now it seems that even that is undesirable. 

There is some thought that: 

1. Facets should only change when explicitly requested.
2. When changing facets, the result should incorporate information from other facet choices.
3. Selected facets should stay selected when facets are recomputed (unless they become invisible due to zero matches).

### LINKED ISSUE #2432: Clear Dates button does not work
In the Discover page, clicking on the red X clear Dates button does not clear the Temporal Coverage Dates

image

### LINKED ISSUE #2451: [Discover Page] Show all button does not work
Clicking Show all on the discover page does not do anything, even if you have filters on.

EDIT: I saw there is a discussion already on the issues feed about the show all button, but I could not get it to elicit the behavior they were talking about.

### LINKED ISSUE #2470: Discovery: resources whose title starts with ' ' appear first in title order.
Now that sorting works, it is clear that there are some problems with the data. Particularly, author names and titles that start with space are not cleaned and appear before those that don't start with space.

### PR DESCRIPTION
**Pull request by alvacouch**
@aphelionz @martinseul This fixes a number of discovery issues, including #2470 #2451 #2432 #2430. 
It also allows sorting by title, author, creation date, and last modified date, and reports page statistics. 

Fixes #2470 
Fixes #2451
Fixes #2432 
Fixes #2430 

Notes: 

* `nameparser` is loaded and used to normalize names into Last, First Middle before sorting. This is not depicted on the display; it is just used in sorting into order. 
* Titles and Author names starting with spaces are cleaned up in the SOLR database but not the Django database.
* This **does not** fix map issues.

### CODE REVIEW

**Comment by alvacouch** [comment]
@aphelionz @dtarb @martinseul This is ready for review and deployed on 

      http://cuahsi-dev-2.hydroshare.org

Improvements include: 

* all buttons work.
* sort by title, first author (Last, First)!, creation date, modified date. 
* report on total entries and pages at bottom. 
 
What is not fixed: 

* left un-normalized names reported in the view (even though I sort by normalized names) 
* no improvements to map view.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by dtarb** [comment]
I just did a quick test on https://cuahsi-dev-2.hydroshare.org/search/ and find that if I sort by date created and descending, then set a date range starting after the most recent resource (too late), then realize my mistake and set better dates I end up with no results found (even after repeatedly pressing enter to try retrigger the search.

image

I also find that clicking on the clear dates button has no effect #2432.

I also found it possible to get into a state where after clicking show all, the author facet only show one author, not all authors.

image

**Comment by alvacouch** [comment]
@dtarb The javascript front-end -- that does everything -- crashed under these conditions. If you reload the page the condition goes away. Was able to reproduce. Will debug.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@dtarb @aphelionz This is fixed. Try again. You should not be able to crash JavaScript any more. Buttons should stay working.

**Comment by dtarb** [comment]
Much improved.  I do though get the following weird result.

1. Click on Discover
2. Select Composite Resource in Filter by Resource Type
3. Select Zhiyu (Drew) Li in Filter by Owner

I see a listing of 4 resources which appear to be the correct ones to Discover, but I see below this a message "Sorry, no results match ..." that seems incorrect.

image

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@dtarb I noticed that message already and fixed it.

**Comment by alvacouch** [comment]
@aphelionz I am ready for review.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
Freezing UI for discovery at this point for 1.14.0.

**Pull request merged**
