### PR TITLE
[#4364] Hard code IRODS_DATA_IP and IRODS_USER_IP to fix PR builds.

### PR DESCRIPTION
**Pull request by cbcunc**
### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW CODE SMELLS | 0 |
| NEW DUPLICATED LINES DENSITY | 0.0 |
| NEW VULNERABILITIES | 0 |
| NEW BUGS | 0 |
| NEW SECURITY HOTSPOTS | 0 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4365](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4365)

**Comment by sblack-usu** [comment]
looks like local_settings.py would have to be updated as well

**Comment by sblack-usu** [comment]
🤞 - made the same change to local_settings

**Comment by sblack-usu** [comment]
still some gnarly new errors

**Pull request closed without merging**
