### PR TITLE
[#2116] My resources filter changes

### PR DESCRIPTION
**Pull request by Maurier**
Filter changes as discussed in #2116 and #765
Also contains minor layout and style fixes and code refactoring

### CODE REVIEW

**Comment by Maurier** [comment]
Can be tested at https://park.hydroshare.org/my-resources/

**Comment by aphelionz** [comment]
@Maurier Looks like you have some pylint errors. Please fix.

**Comment by Maurier** [comment]
@aphelionz Thanks, will fix today.

**Comment by Maurier** [comment]
I made one last change. Adding Favorites to the default active filters.

**Pull request merged**
