### PR TITLE
Fixing scimeta root endpoint

### LINKED ISSUE #2544: Swagger - get scimeta returns no content
Running the `GET /hsapi/resource/{id}/scimeta/` returns ` "error": "no response from server"`.

When I call this command using the `hs_restclient` I get the science metadata back:

```
>>> hs.getScienceMetadata('520f59bd5e72435b83390a571bb972b0')
{'title': 'testing', 'creators': [{'name': 'Anthony Castronova', 'description': '/user/11/', 'organization': 'CUAHSI', 'email': 'castronova.anthony@gmail.com', 'address': None, 'phone': '3399334127', 'homepage': None, 'order': 1}], 'contributors': [], 'coverages': [], 'dates': [{'type': 'created', 'start_date': '2018-01-05T20:12:53.234724Z', 'end_date': None}, {'type': 'modified', 'start_date': '2018-01-05T20:20:04.853416Z', 'end_date': None}], 'description': 'here is an abstract', 'formats': [{'value': 'application/zip'}, {'value': 'text/plain'}], 'funding_agencies': [], 'identifiers': [{'name': 'hydroShareIdentifier', 'url': 'http://www.hydroshare.org/resource/520f59bd5e72435b83390a571bb972b0'}], 'language': 'eng', 'rights': 'This resource is shared under the Creative Commons Attribution CC BY. http://creativecommons.org/licenses/by/4.0/', 'type': 'http://www.hydroshare.org/terms/GenericResource', 'publisher': None, 'sources': [], 'subjects': [{'value': 'test'}, {'value': 'resource'}, {'value': 'template'}, {'value': 'resource1'}], 'relations': []}
```

### PR DESCRIPTION
**Pull request by aphelionz**
Fixes #2544 

To test: 

1. Check out the branch and restart (no need to rebuild)
2. Visit /hsapi locally to see the Swagger docs
3. Expand hsapi
4. Scroll down to GET /hsapi/resource/{id}/scimeta/
5. Expand that section and insert any public resource ID into ID
6. Click "try it out!"
7. RDF metadata should appear in the response

### CODE REVIEW

**Comment by aphelionz** [comment]
@pkdash can you review?

**Comment by pkdash** [comment]
@aphelionz Will review tonight.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by pkdash** [comment]
@aphelionz I am not sure these changes fix the issue #2544. I am thinking #2544 is probably not an issue if swagger interface is not capable of downloading a file. I have added some comments to #2544 for further reasoning.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@pkdash I'm still gonna try and get this working in Swagger but I'm wondering about the errors in PUT that I'm seeing. Do you have any idea why the changes I did in GET would cause the PUT tests to fail?

**Comment by pkdash** [comment]
@aphelionz Didn't find any obvious reason why the PUT test would fail. Can you point to any specific test that's failing and what's the failing message?

**Comment by aphelionz** [comment]
@pkdash http://ci.hydroshare.org:8080/job/hydroshare-pull-requests/1289/

**Comment by pkdash** [comment]
@aphelionz This line may be causing both those tests to fail (http -> https may fix it):

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/serialization.py#L351

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
I'm just gonna close this. It smells too bad and I feel like it's going to cause more problems than it fixes. You were right @pkdash

**Pull request closed without merging**
