### PR TITLE
[WIP] 711 refactor core metadata

### PR DESCRIPTION
**Pull request by pkdash**
This needs to be deployed on alpha or some other place before merging into develop.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by rayi113** [comment]
@ironfroggy @selimnairb please review

**Comment by ironfroggy** [comment]
Nothing wrong stands up but I'm not familiar enough with the semantics of whats being changed here to speak on if it looks correct or not. +1 on a solely code basis.

**Comment by selimnairb** [comment]
@pkdash I have similar feelings to @ironfroggy, but in general this looks good to me.  It simplifies the metadata code within the current structure, and adds tests.  +1 to merge.

**Pull request merged**
