### PR TITLE
3397 bootstrap 3 navibar gobbles content at 991px width

### PR DESCRIPTION
**Pull request by engineSound**
## Explanation of the problem
The out of box bootstrap 3 navibar implementation had problem when a browser downsizes to 991px until 767px width in desktop browsers of all kinds. The navibar-left and navibar-right don't collapse well between 767 and 991px. 

## The fix
The solution is to let it collapse starting at 991px without delegating to defective bootstrap 3 handling. 
https://stackoverflow.com/questions/18192082/bootstrap-3-navbar-collapse

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Review by Maurier — APPROVED** [review]
Looks good.

**Review by Maurier — CHANGES_REQUESTED** [review]
Oh wait, I just found an issue. When the menu collapses, the Profile and Sign Out menu items are not properly rendered anymore.

image

Same for the new Create menu popup
image

**Comment by engineSound** [comment]
> Oh wait, I just found an issue. When the menu collapses, the Profile and Sign Out menu items are not properly rendered anymore.
> 
> image
> 
> Same for the new Create menu popup
> image

Was it like this before?

**Comment by Maurier** [comment]
@engineSound - No, it didn't show a popup on smaller screens. It showed up as a similar menu.

Notice that the styling on these items changes a little with https://github.com/hydroshare/hydroshare/pull/3407

**Pull request closed without merging**
