### PR TITLE
[#2696] add default reCAPTCHA test keys and site url

### PR DESCRIPTION
**Pull request by sblack-usu**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Deploy hydroshare locally and navigate to the signup page.  Validate that captcha works.  There will also be little red text that says "This reCAPTCHA is for testing purposes only. Please report to the site admin if you are seeing this"

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@sblack-usu @hyi Do we feel this is safe to include in the 1.15.1 point release?

**Comment by sblack-usu** [comment]
yeah, I mistakenly thought this was merged.  I'll resubmit the pull request against develop.

**Comment by aphelionz** [comment]
Awesome, thank you!

**Pull request closed without merging**
