### PR TITLE
863 - Last Modified column sorting

### PR DESCRIPTION
**Pull request by mauriel133**
Fixes sorting in My Resource page for Last Modified column.

### CODE REVIEW

**Comment by mauriel133** [comment]
Can I have this branch deployed on a sandbox with multiple resources so I can test the sorting?

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by mjstealey** [comment]
> Can I have this branch deployed on a sandbox with multiple resources so I can test the sorting?

@mauriel133 - Will get this deployed on 1/13/16 on park using www resources, Will update this post when completed.

**Comment by mjstealey** [comment]
@mauriel133 - This is deployed on https://park.hydroshare.org
using www resources

**Comment by mauriel133** [comment]
Thanks @mjstealey.

This feature works as intended as tested on https://park.hydroshare.org.

@hyi, @pkdash or @ironfroggy please review.

**Comment by horsburgh** [comment]
I also had a look on park.hydroshare.org and it looks good to me.

**Comment by hyi** [comment]
I'll give a +1, though @ironfroggy and/or @pkdash may want to give a quick review as well.

**Comment by pkdash** [comment]
@hyi Since most changes are JavaScript code, I won't be able to review it any better.

**Comment by mauriel133** [comment]
If no more comments I will be merging this today.

**Pull request merged**
