### PR TITLE
1.15 rc1

### PR DESCRIPTION
**Pull request by aphelionz**
For now, simply creating this pull request to see what jenkins thinks about it.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@sblack-usu What are your thoughts on merging this back into develop until we can cut a proper release candidate?

**Comment by sblack-usu** [comment]
Merging back into develop means we get all the bug fixes and tweak back in the main branch.  On the other hand, it means next time we cut a RC it's going to be releasing more features.  And if we're struggling to get just these features ready for release, then it could be made worse by bringing in more features the next time we cut a release.

**Comment by aphelionz** [comment]
Good points on both cases. I think we can bear the extra features this time around since the problems were mainly on the iRODS layer. The features in PR now don't seem too heavy if we're only delaying a week or two...

**Pull request merged**
