### PR TITLE
[#1725] remove dockerworker and related code

### PR DESCRIPTION
**Pull request by mjstealey**
Removing dockerworker and related code
- includes [dockerworker container](https://github.com/hydroshare/hydroshare/blob/develop/scripts/templates/docker-compose.template#L80-L100) and definitions
- includes submodule: [django_docker_processes](https://github.com/hydroshare/django_docker_processes/tree/53c7d181aac16200b663d78be80ccf0c7177fcc1)
- included resource: [hs_rhessys_inst_resource](https://github.com/hydroshare/hydroshare/tree/develop/hs_rhessys_inst_resource)
- included resource: hs_rhessys_modelinstance
- occurrences of settings, urls, etc.

### CODE REVIEW

**Comment by mjstealey** [comment]
@pkdash, @hyi - could you review this please. Many deletes, but want to make sure the right bits have been removed.

**Comment by pkdash** [comment]
@mjstealey Had a quick look. Glad to see some dead code removed. Will take another look later.

**Comment by hyi** [comment]
@mjstealey +1. Looks good to me.

**Comment by aphelionz** [comment]
@mjstealey @dtarb @alvacouch or whomever

Can we get explicit confirmation that hs_rhessys_inst_resource is safe to delete? If it IS.... then can we delete hs_rhessys_modelinstance/ as well? :)

**Comment by mjstealey** [comment]
> Can we get explicit confirmation that hs_rhessys_inst_resource is safe to delete?

The code here was for running rhessys models in docker on the same server as the hydroshare application. It predates the apps concept of model execution as well as the model-instance / model-program paradigm currently being used. Most recent meaningful code is from 2 years ago.

>  If it IS.... then can we delete hs_rhessys_modelinstance/ as well?

The hs_rhessys_inst_resource was the first pass at migrating towards the model-instance / model-program paradigm and could be used as a basis if someone were to carry the work forward. Most recent meaningful code is from 11 months ago.

Both of these were written by a developer who is no longer on the team.
@Castronova still works with the group doing RHESSys work from a Jupyter hub point of view. The hs_rhessys_inst_resource may be useful in that regard, but I cannot speak to that definitively.

**Comment by mjstealey** [comment]
ON HOLD - need to determine what is going on in existing develop branch prior to merging anything new...

1. Resources not appearing in my-resources page
2. Bag download fails with `<django_irods.storage.IrodsStorage object at 0x7f8fb43dd250> is not JSON serializable`

**Comment by mjstealey** [comment]
Prior issues resolved, Dockerfile now references hs_docker_base:1.7.5 + add-on

**Comment by pkdash** [comment]
@dtarb Are OK with the delete of  hs_rhessys_inst_resource type?

**Comment by dtarb** [comment]
Can we save the RHESSys work somewhere, perhaps in a separate branch.  I'd like to follow up with @selimnairb and Larry Band before permanently removing.  I do agree though that we want this out of the operational deployment at this time and that we do not want to have models execute in Docker containers on the main server.

**Comment by mjstealey** [comment]
> Can we save the RHESSys work somewhere

Branch [rhessys-reference-work](https://github.com/hydroshare/hydroshare/tree/rhessys-reference-work) created for this purpose.

**Comment by mjstealey** [comment]
@hyi, @pkdash - requesting a final review please.

**Comment by hyi** [comment]
@mjstealey I did another round of code review, and it looks good to me, +1.

**Pull request merged**
