### PR TITLE
1700 model program ui fixes

### PR DESCRIPTION
**Pull request by jsadler2**
@mauriel133 @pkdash could you review these front-end changes? Thanks!

### CODE REVIEW

**Comment by mauriel133** [comment]
@jsadler2, the front end changes look good. +1 on that.

One minor observation: there is this empty <legend> tag that creates a line on top of this form. However, It existed before this PR. If you have time to include a fix for that, it would be great. Otherwise I think it's good to merge.

image

**Comment by mauriel133** [comment]
The empty tag is generated in this line
https://github.com/hydroshare/hydroshare/blob/1700-ModelProgram-UI-Fixes/hs_model_program/page_processors.py#L35
But I was unable to dig any deeper. Might need to look at the form declaration or the `crispy ` method

**Comment by pkdash** [comment]
@jsadler2 Are there changes still to be made for the PR?

**Comment by mohamedmorsy** [comment]
@mauriel133 @jsadler2 the problem causing this empty tag is in the following line (element_lab=' '):

https://github.com/hydroshare/hydroshare/blob/1700-ModelProgram-UI-Fixes/hs_model_program/forms.py#L64

This is due to the element_label equal to a blank value. If we remove this element_label, we will retrieve the actual element name as the following:

image


@mauriel133 @pkdash do you have any suggestion for not including the element name and on the same time not getting this empty tag?

**Comment by pkdash** [comment]
@mohamedmorsy Why not set the ```element_name_label='Mpmetadata'```?

**Comment by jsadler2** [comment]
@pkdash I changed the title to "Model Program Metadata". I think it looks better now.

**Comment by pkdash** [comment]
@mauriel133 I assume @jsadler2 can merge this.

**Comment by mauriel133** [comment]
Correct. The changes look good.

**Pull request merged**
