### PR TITLE
Inactive users and groups

### PR DESCRIPTION
**Pull request by pkdash**
Filter out inactive users/groups for autocomplete UI.
For previous conversions related to this PR refer to https://github.com/hydroshare/hydroshare/pull/1200

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@shawncrawley Can you review this small PR?

**Comment by pkdash** [comment]
@shawncrawley Let me know if you can review it soon.

**Comment by shawncrawley** [comment]
+1

**Comment by pkdash** [comment]
@shawncrawley Thanks for the quick review.

**Pull request merged**
