### PR TITLE
Changing name attribute from 't' to 'flag'

### LINKED ISSUE #2241: Unable to make a resource public in 1.11 deploy
I just created this resource https://www.hydroshare.org/resource/6cb2da4dffa248c09bc4d7d883fdf4a1/.  I added abstract and keyword and received the message that it could be made public, but when I click on the public button nothing happens.  I am not doing anything that I have not done before, so have to assume this is to do with the 1.11 deploy.

### PR DESCRIPTION
**Pull request by aphelionz**
Fixes #2241 

Also I edited the *.old file for consistency's sake. I know full well it doesn't actually matter.

### CODE REVIEW

**Comment by hyi** [comment]
+1, agreed *.old can actually be deleted all together. You can merge it when it passes Jenkins. It should be an easy hotfix.

**Comment by aphelionz** [comment]
@hyi Thanks. Deletied.

**Comment by mjstealey** [comment]
@aphelionz - Please repoint this PR to be pointed at the **master** branch.

The release-candidate-1.11.0 branch should now be removed.

**Comment by aphelionz** [comment]
Closing to cherry pick and recreate the branch

**Comment by aphelionz** [comment]
Actually... @mjstealey this code looks important... was it not part of master? I maybe seem to remember some controversy around this and perhaps it was pulled out?

**Pull request closed without merging**
