### PR TITLE
Adding recaptcha2 back to signup

### PR DESCRIPTION
**Pull request by aphelionz**
Follow the instructions to test. You may have to register at https://www.google.com/recaptcha/admin to get your site key and secret. These are NOT checked in to Git (or at least shouldn't be).

1. Check out this branch and add the following to local_settings.py:
```
RECAPTCHA_VERIFY_URL='https://www.google.com/recaptcha/api/siteverify'
RECAPTCHA_SITE_KEY="enter site key here"
RECAPTCHA_SECRET_KEY="enter secret key here"
```
2. On line 48 of `theme/templates/accounts/sign_up_form.html` add the site key in the `data-sitekey` attribute
3. `./hsctl restart`
4. Test the signup flow with the new captcha. If all goes well it should create a new account for you with no problems.

### CODE REVIEW

**Comment by aphelionz** [comment]
@phuongdm and @cbcunc Please note that this adds a step to our deployment process, similar to setting the google analytics key:

> On line 48 of theme/templates/accounts/sign_up_form.html add the site key in the data-sitekey attribute

**Comment by hyi** [comment]
@aphelionz I think with a bit of more work, the data-sitekey can be passed from Django by reading the key from local_settings.py to populate the key in signup_form.html. This way, there would not be extra step to manually paste the site key into the html file.

**Comment by aphelionz** [comment]
@hyi We tried it. Look at the latest issue #2597

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hyi** [comment]
@aphelionz One workaround I am thinking might work is to pass secret key from Django view to signup form template via context variable, in the similar way as how metadata and other variables are passed to resource pages. It may involve digging into Mezzanine code to customize the view function so that this secret key could be passed as context variable. Specifically, make the signup url to map to our customized view function which can send secret key as context variable to sign up form template rather than map to the default Mezzanine view function. For your reference. Although it is not a clean solution, at least it does not require an extra step for deployment, so may be a workaround worth exploring.

**Comment by aphelionz** [comment]
@hyi I have explored this rather thoroughly - views expose an `extra_context` function but I simply don't have the access to the mezzanine views. If you want to take a crack at it, please feel free.

**Comment by hyi** [comment]
@aphelionz I have spent some time trying to get this to work as well, but to no avail so far. I suggest we just go with this for now, and create an issue so we may work on this later when we have time.

**Comment by aphelionz** [comment]
@hyi Thanks for the additional effort. It's way more tricky than it should be. #2597 captures the problem well.

**Comment by cbcunc** [comment]
Mezzanine breaks settings. Much pain from this.

**Comment by cbcunc** [comment]
Sent to dev list:

Our ReCaptcha2 hot fix has some implications for development.

When you ask Google for ReCaptcha2 keys, you must register which domains those keys will be used for ReCaptcha requests.

When you are developing on VirtualBox, you will need to get your own ReCaptcha keys by the process in the https://github.com/hydroshare/hydroshare/pull/2598. And when you get those keys, you will need to use the raw IP of the host machine running VirtualBox as the domain authorized to use the keys (and not the domain name or IP of the guest OS, which are un-routable).

**Comment by pkdash** [comment]
Can't we just comment out the recaptcha form validation for local development?

**Pull request merged**
