### PR TITLE
Fix groups res

### PR DESCRIPTION
**Pull request by cuahsimarko**
### Issues Resolved
Fixes https://github.com/hydroshare/hydroshare/issues/3365

### How to Test
1. Share resources to Group from user1
2. Share resources to Group from user2
3. Go to collaborate / My Groups / Resources and play with the checkboxes to filter resources

image

### CODE REVIEW

**Comment by cuahsimarko** [comment]
@zhiyuli please look at this from a functionality perspective think of ways to break it

**Comment by cuahsimarko** [comment]
@Maurier are we good to go on this or do you still want me to leave it open for you to comment...

**Comment by Maurier** [comment]
@cuahsimarko I looked at the code and it looks good to me. I can't test it right now, but feel free to merge and I'll do some testing later on.

**Comment by cuahsimarko** [comment]
@Maurier Understood. Drew has verified the functionality.

**Comment by cuahsimarko** [comment]
@zhiyuli when tests finish can you re-verify functionality (since the merge conflict resolution was deep), approve and merge (if appropriate)?

**Comment by zhiyuli** [comment]
@cuahsimarko @Maurier 
Not sure what is going on. The checkbox stopped working for me now. I did collectstatic and cleared browser cache. Will try it again
image

**Comment by cuahsimarko** [comment]
Fixed code that was lost during dev merge

**Comment by zhiyuli** [comment]
@cuahsimarko 
It is not working for me still. I tried collectstatic as well.

**Comment by zhiyuli** [comment]
@cuahsimarko 
Tested locally. Works like a charm.

**Pull request merged**
