### PR TITLE
Modification to hs_tracking fields

### PR DESCRIPTION
**Pull request by Castronova**
Modified user and resource logging fields to ensure logstash fingerprints are unique=, see https://github.com/hydroshare/hydroshare/issues/2082

### CODE REVIEW

**Comment by alexlemann** [comment]
@alvacouch @hyi @mjstealey I wanted to ping you in case that resource short key that's causing an error above looks familiar to you given other issues.

**Comment by pkdash** [comment]
@Castronova What's the status of this PR? Are you waiting for additional reviews?

**Comment by Castronova** [comment]
@pkdash I think it's good to go and can be merged now.  Would you like me to merge it?

**Comment by pkdash** [comment]
@Castronova Merge it then.

**Comment by mjstealey** [comment]
@Castronova, @pkdash - Unless another PR is made pointing at release-candidate-1.11.0, this work will not be in 1.11.0

**Comment by Castronova** [comment]
thanks @mjstealey.  Creating a pr for rc 1.11.0.

**Pull request merged**
