### PR TITLE
[#5082] add user agent for metrics

### LINKED ISSUE #5082: Track user agent for metrics
**Describe the feature you'd like and what it will do**
In HS v2.5.4, we don't track user_agent in our metrics. This makes it difficult to tell when requests to HS are occurring via direct UI interactions, or via other tools like hsclient.

**Why is this feature important?**
We need more insight into how HS' ecosystem of tools are being used. This information should drive our continued development on existing tools and our consideration of additions for future use.

**Is your feature request related to a problem? Please describe.**
It is difficult to make decisions without information.

### PR DESCRIPTION
**Pull request by devincowan**
Resolves #5082

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Interact with a resource (say download it)
2. Run some SQL `SELECT * FROM "public"."hs_tracking_variable" ORDER BY "timestamp" DESC LIMIT 100 OFFSET 0;`
3. See that the user_agent is recorded (not for every visit, just for begin_session, delete, create, download)

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5083)

**Review by pkdash — APPROVED** [review]

**Pull request merged**
