### PR TITLE
Change flake8 line max to 120

### PR DESCRIPTION
**Pull request by cuahsimarko**
Per team discussion, increasing line length tolerance to 120 from 100

### CODE REVIEW

**Comment by cuahsimarko** [comment]
I'm being patient with Jenkins :P

**Comment by sblack-usu** [comment]
eh, jenkins isn't doing anything useful with this change

**Comment by cuahsimarko** [comment]
Phu and I just reordered the steps to make flake happen before 4-hour unit testing, though merging or not won't affect that, you're right. Just wanted to see linting run then merge I suppose.

**Comment by sblack-usu** [comment]
waiting is fine too

**Comment by cuahsimarko** [comment]
patience is a virtue?

**Comment by cuahsimarko** [comment]
Ok let's all keep our eye on the "new feature branch auto checks" and "opening a PR jenkins checks" if you fail flake, you should exit with a warning within the first half hour (TIL: flake8 takes like 20 minutes for our code!) otherwise, it moves onto the lengthy unit testing...

**Pull request merged**
