### PR TITLE
Moved directory creation outside of container to maintain permissions…

### PR DESCRIPTION
**Pull request by dan-palmer1**
...., set version variable for nodejs image.

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4027](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4027)

**Comment by sblack-usu** [comment]
retest this, please

**Comment by sblack-usu** [comment]
@dan-palmer1 - I'm kicking off the tests again in case it was a fluke.  Otherwise, looks like there are some tests failing.

**Comment by dan-palmer1** [comment]
@sblack-usu I’ll retest tomorrow, I did not see any issues prior to submitting the PR.

**Comment by sblack-usu** [comment]
retest this, please

**Comment by dan-palmer1** [comment]
retest this, please

**Pull request closed without merging**
