### PR TITLE
[#4995] Fix for raster aggregation remove

### PR DESCRIPTION
**Pull request by pkdash**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Create a resource. Create a Geographic Raster aggregation by uploading at least 2 tif files and the associated vrt file. These files need to be part of a single upload. Verify a raster aggregation is created. Open the raster aggregation folder to see the files of the aggregation. You should see all files you uploaded. 
2. Go back to the root of the directory. Then remove the aggregation by right clicking on the aggregation folder and the selecting the 'Remove content type' option. Verify the aggregation is removed and all the files you uploaded are still there.

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5002](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5002)

**Comment by devincowan** [comment]
@pkdash maybe I'm missing something...
Take a look at this video...shouldn't there be 4 files in content/ once I remove the content type aggregation?

https://user-images.githubusercontent.com/17934193/223847330-860e4a79-4e85-4003-85fc-86912a20019c.mov

**Comment by pkdash** [comment]
@devincowan Along with the raster files (tif and vrt) files you are uploading two xml files that are matching the aggregation resource map and aggregation meta file name. As part of removing the aggregation the system deletes the aggregation xml files which in normal case are not part of the resource files.

**Review by devincowan — APPROVED** [review]
nice fix thanks @pkdash!

**Pull request merged**
