### PR TITLE
[#2066][Hotfix] Temporal coverage parsing fix

### PR DESCRIPTION
**Pull request by mauriel133**
Fixes date parsing error described in #2066

### CODE REVIEW

**Comment by pkdash** [comment]
@mauriel133 Can you test if this change still works for a composite resource? 
Test procedure:
1. Create a composite resource uploading any file
2. Then in the edit mode of the resource, select the file and select File Metadata tab
3. Enter/save temporal dates for the file
4. See if the updated resource level metadata is in the correct format.

**Comment by mauriel133** [comment]
@pkdash, this is working as before since it is not using the formatting class, but we should replace the formatting to "yyyy/mm/dd" for consistency.

image

**Comment by pkdash** [comment]
@mauriel133 How the temporal dates are formatted in edit mode for file type? I agree on making the date formats consistent. 

See if you can make changes to this line https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L1239
as:
```td(self.value['start'].replace('-', '/', 3))```

Make similar change to end date on line#1242

**Comment by pkdash** [comment]
@mauriel133 Are the temporal dates now consistent between resource and file?

**Comment by mauriel133** [comment]
Besides replacing "-" with "/" we still need to move the values around from "yyyy/mm/dd" to "mm/dd/yyyy". I have added a `.formatDate()` method that can be called on HTML elements. Perhaps we can call this method on the text after it is rendered.

**Comment by pkdash** [comment]
Have you applied the function ```.formatDate()``` to file type temporal dates in JS?

**Comment by mauriel133** [comment]
@pkdash, not yet. Could you tell me how to add an ID to these fields in the .py file, this way I can select them and run the function on them?

**Comment by pkdash** [comment]
@mauriel133 If you want to add an id to this line: https://github.com/hydroshare/hydroshare/blob/release-candidate-1.10.0/hs_core/models.py#L1239

```td(self.value['start'], id='id_start_date')```

Similarly to any htmp python object (tr, table, div etc) you can add the id attribute as shown above.

**Comment by mauriel133** [comment]
@pkdash, these fields are now being formatted accordingly.

**Comment by pkdash** [comment]
+1. Merge after Jenkins checks are successful.

**Pull request merged**
