### PR TITLE
1389 key/value pair metadata for resource creation

### PR DESCRIPTION
**Pull request by gantian127**

### CODE REVIEW

**Comment by pkdash** [comment]
@zhiyuli can you review this?

**Comment by pkdash** [comment]
@gantian127 It seems you have to fix some code formatting issues.

**Comment by zhiyuli** [comment]
@gantian127 @pkdash Was this change to make rest api be able to create a resource with extra metadata?

**Comment by pkdash** [comment]
@zhiyuli Yes

**Comment by zhiyuli** [comment]
+1

**Comment by gantian127** [comment]
@zhiyuli Thanks for the code review.

**Pull request merged**
