### PR TITLE
[#1164] Fixed the bug

### PR DESCRIPTION
**Pull request by jsadler2**
@pkdash  please revise

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@jsadler2 Which bug/issue this PR is addressing? The #1164 you have referenced doesn't seem to be resolved by this PR.

**Comment by mohamedmorsy** [comment]
@pkdash sorry we wrote a wrong issue number. The issue we are solving is issue #1166.

**Comment by pkdash** [comment]
+1

**Pull request merged**
