### PR TITLE
[#4665] wait for rights agreement before zipped download

### LINKED ISSUE #4665: Download doesn't wait for rights statement confirmation
**Description of the bug**
If a resource has "Require agreement to rights statement before downloading" checked, when a user attempts to download a bagit zip, a modal is shown with the rights statement. However, the download proceeds even without the user accepting the statement. 

Steps to reproduce the bug:
1. Create a resource with some files
2. Check the "Require agreement to rights..." checkbox
3. In the file browser, select the "Download all content as zipped bagit..."
4. The modal will show but the download will also start before acceptance
5. This is also true for collection resources as shown in the video below

**Expected behavior**
Download should wait for the rights statement to be confirmed

**Additional information**
Firefox 101, HS v1.055.2

https://user-images.githubusercontent.com/17934193/173404691-09efd43d-ebb1-4d8c-ba33-9b8bd1b15c9d.mov

### PR DESCRIPTION
**Pull request by devincowan**
Resolves #4665 

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Create a resource with some files
2. Check the "Require agreement to rights..." checkbox
3. In the file browser, select the "Download all content as zipped bagit..."
4. The modal will show and the download will not start before acceptance
5. This is also true for collection resources

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4792](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4792)

**Comment by pkdash** [comment]
@devincowan It seems all code changes are front-end specific. I don't feel comfortable reviewing JS code. I was wondering if @Maurier could review this PR.

**Comment by Maurier** [comment]
> @devincowan It seems all code changes are front-end specific. I don't feel comfortable reviewing JS code. I was wondering if @Maurier could review this PR. 

I can review this today.

**Comment by devincowan** [comment]
sounds good, thanks

**Comment by Maurier** [comment]
@devincowan There seems to be an issue still. After checking the option to require agreement, and then clicking on `Download All Content...`, a loading spinner is shown on top of the previous icon on the button immediately before interacting with the modal. 

image

This spinner should only show up when the download has started or after clicking the `Download` button on the modal. And it should not overlay the previous icon, but hide the previous icon instead.

**Comment by devincowan** [comment]
thanks @Maurier I'll fix that

**Comment by devincowan** [comment]
@Maurier I made the change you requested

**Review by Maurier — APPROVED** [review]
Looks good. I added a few commits with minor layout improvements.

**Comment by devincowan** [comment]
Nice, thank you for the improvements Maurier!

**Pull request merged**
