### PR TITLE
825 fix for labels and favorite persist problem

### PR DESCRIPTION
**Pull request by pkdash**
@hyi or @mauriel133 Please review and merge.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by mauriel133** [comment]
Did you have a chance to test it out in your branch?

**Comment by pkdash** [comment]
@mauriel133 Discover page is not working for me locally. So not able to test. You cam pull this branch for a quick test if discover page is working for you.

**Comment by mauriel133** [comment]
I'm trying to replicate the problem, once I do it I'll give this a try.

**Comment by hyi** [comment]
I pulled the change in my local dev env and the page refresh appears to work for added resource from discovery page. The code change also makes sense to me. So +1 and I am merging it to develop, and then deploy to beta, and www if it indeed fixes the issue.

**Comment by hyi** [comment]
@pkdash @mauriel133 @dtarb @alvacouch I have merged the PR and deployed the hotfix to beta and www. The label persist issue after page refresh appears to be fixed. Please test it out and let me know if you notice any further issues.

**Pull request merged**
