### PR TITLE
[#2291] Publish button update

### PR DESCRIPTION
**Pull request by Maurier**
- If the resource is not Public the Publish button is now hidden.
- If the resource is Public, but the profile is incomplete, the button is grayed out and a helpful message is shown when hovered over.
image
- Title field in Profile page is now a required field.
- Minor profile page style adjustments
image

### CODE REVIEW

**Comment by Maurier** [comment]
This code is ready for review now.

**Comment by Maurier** [comment]
We still need to decide. We can leave the implementation like this, or we can change the tooltip to a popover with a message and link to the Profile page.

I vote for leaving this implementation as is because we already have a message that shows up to users with incomplete Profile information on page load prompting them to fill in the missing information.

**Comment by aphelionz** [comment]
@dtarb See Mauriel's comment. Cool with you?

**Comment by dtarb** [comment]
If the current decision is to go with 
image 
then I like it.

I did note in the comments above "Title field in Profile page is now a required field".  Sorry for there to be reneging on this, but in a side discussion with @martinseul and @aphelionz we decided a few days ago that Title did not need to be a required field.

**Comment by Maurier** [comment]
In that case should we be removing the field from the prompt message as well? 
image

**Comment by aphelionz** [comment]
@Maurier Sure, go ahead. We will be removing that nag message soon enough anyway. Might as well be consistent in the meantime.

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
