### PR TITLE
[#1277] Fix for broken link to user profile

### PR DESCRIPTION
**Pull request by mauriel133**
Also allows only for owners to invite other users to the group.

### CODE REVIEW

**Comment by pkdash** [comment]
+1. Is this needs to be applied as a hotfix?

**Comment by mauriel133** [comment]
I think so.

**Comment by mjstealey** [comment]
> applied as a hotfix

@mauriel133, @pkdash:
Since this is a single file it's been applied directly to www, please verify that it is doing what it should be.

**Comment by pkdash** [comment]
Did test at www and seems to have fixed the issue. @mauriel133 still needs to merge this right?

**Comment by mjstealey** [comment]
> @mauriel133 still needs to merge this right

Correct. I manually made the change on www, but the PR still needs to be merged into develop

**Comment by mauriel133** [comment]
Ok. I will merge it now.

**Pull request merged**
