### PR TITLE
268 ui testing

### PR DESCRIPTION
**Pull request by alexlemann**
Adds qunit & selenium tests

### CODE REVIEW

**Comment by mjstealey** [comment]
@alexlemann - flake8 warnings to address, but otherwise clean

```
./theme/tests/test_functional.py:4:1: F401 'NoSuchElementException' imported but unused
./theme/tests/test_functional.py:6:1: E302 expected 2 blank lines, found 1
./theme/tests/test_functional.py:28:101: E501 line too long (105 > 100 characters)
./theme/tests/test_functional.py:35:101: E501 line too long (102 > 100 characters)
```

**Comment by pkdash** [comment]
At least all front-end developers in our team should look/review this PR. For the reviewers, it is going to be mostly learning how to write unit tests for front-end code (JS/html/css). @zhiyuli , @mauriel133 , @xuezhaokun , @shawncrawley review this PR.  Anyone else interested to learn front-end testing is also welcome to review this PR Thanks.

**Comment by pkdash** [comment]
@aphelionz can you review this?

**Comment by aphelionz** [comment]
@pkdash @alexlemann Looks good overall. I'm a huge fan of the Selenium testing, even if it is a bit slow. @mjstealey are there plans to integrate the QUnit tests into the Jenkins build?

**Comment by pkdash** [comment]
@aphelionz Glad to know you have experience in Selenium testing.

**Comment by pkdash** [comment]
@alexlemann It seems like once you resolve the conflicts, it's ready to be merged.

**Comment by mjstealey** [comment]
flake8 fuss
```
./django_irods/icommands.py:22:1: E305 expected 2 blank lines after class or function definition, found 1
./django_irods/icommands.py:257:1: E305 expected 2 blank lines after class or function definition, found 1
./hs_app_timeseries/forms.py:652:1: E305 expected 2 blank lines after class or function definition, found 1
./hs_core/models.py:1747:1: E305 expected 2 blank lines after class or function definition, found 0
./hs_geo_raster_resource/forms.py:309:1: E305 expected 2 blank lines after class or function definition, found 1
./hs_geo_raster_resource/models.py:188:1: E305 expected 2 blank lines after class or function definition, found 1
./hs_geo_raster_resource/receivers.py:446:1: E305 expected 2 blank lines after class or function definition, found 0
./hs_geographic_feature_resource/models.py:111:1: E305 expected 2 blank lines after class or function definition, found 1
./hs_modflow_modelinstance/forms.py:510:1: E305 expected 2 blank lines after class or function definition, found 1
./hs_tools_resource/forms.py:208:1: E305 expected 2 blank lines after class or function definition, found 1
./hs_tools_resource/models.py:42:1: E305 expected 2 blank lines after class or function definition, found 1
./theme/admin.py:21:1: E305 expected 2 blank lines after class or function definition, found 1
```

**Comment by mjstealey** [comment]
> once you resolve the conflicts, it's ready to be merged

conflicts resolved, merging

**Pull request merged**
