### PR TITLE
[#3136] Add custom HydroShare font icons setup

### PR DESCRIPTION
**Pull request by Maurier**
This PR adds the setup for maintaining our own custom icons. These are designed as SVG and are then imported into a custom font generated with [IcoMoon](https://icomoon.io/app). We will add icons here that are needed in the site but do not exist in FontAwesome or Bootstrap glyphicons.

Advantages of using font icons:

- Scalable to any size without losing resolution.
- They can be styled as fonts with CSS.
- We are already using a lot of them (Bootstrap's glyphicons, fontawesome, etc).

Current icons (.svg files):
[HydroShareIcons.zip](https://github.com/hydroshare/hydroshare/files/2927253/HydroShareIcons.zip)

Project file: 
[HydroShare IcoMoon Project.zip](https://github.com/hydroshare/hydroshare/files/2927270/HydroShare.IcoMoon.Project.zip)

How to add new icons:
------------------
1. Go to https://icomoon.io/app/#/projects
2. Click on "Import Project" and select your project file (HydroShare Font Icons.json)
3. Load the project by clicking on "Load" in the projects list.
4. Click on "Import Icons" in the top left to select the icons you wish to import (.svg files).
5. Preview your icons and make sure they look correct.
6. Make a selection of all the icons you wish to keep in the collection. You can select and deselect by clicking on the icons.
7. Click on "Generate Font" in the bottom right and then make sure your icons have meaningful names.
8. Click on Download to generate your new font files.
9. Update the files at `hydroshare/theme/static/fonts/hydroshare` with your new ones.
10. Update the CSS file at `hydroshare/theme/static/css/hydroshare_fonts.css` with your downloaded `styles.css` file. You will need to edit the .css file so that it follows the following syntax and the relative path is correct given our project setup:

```
@font-face {
  font-family: 'icomoon';
  src:  url('../fonts/hydroshare/icomoon.eot?5tvu01');
  src:  url('../fonts/hydroshare/icomoon.eot?5tvu01#iefix') format('embedded-opentype'),
    url('../fonts/hydroshare/icomoon.ttf?5tvu01') format('truetype'),
    url('../fonts/hydroshare/icomoon.woff?5tvu01') format('woff'),
    url('../fonts/hydroshare/icomoon.svg?5tvu01#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
}

[class^="hs-icon-"], [class*=" hs-icon-"] {
  /* use !important to prevent issues with browser extensions that change fonts */
  font-family: 'icomoon' !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.hs-icon-irods:before {
  content: "\e900";
}


```
11. Make a backup of the previous files and update this post with your new files so that we keep a copy of the most recent icons for future development.
12. We can now use the icons in HTML files like this:
`<span class="hs-icon-irods"></span>`

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by cuahsimarko** [comment]
@Maurier where can we document this outside of this PR (copy-paste)? @sblack-usu @horsburgh @Lizabrazil do you know of any appropriate areas?

**Comment by Maurier** [comment]
@cuahsimarko, @horsburgh  Is there documentation in our Wiki where we can add this to? Otherwise we might want to add it.

**Comment by cuahsimarko** [comment]
I don't know

**Comment by sblack-usu** [comment]
@Maurier - this is a bit heavier than I thought we'd get (I thought there would just be a image to serve).  I'll admit I don't fully grasp what's going on in this PR, it seems like you're using new tools and describing a new best practice for setting up custom fonts with these tools?  This is the first I've heard of icomoon.io, so I don't want to rush into adopting it.

As this is purely a frontend change and practice, I think @engineSound should also be a part of this conversation.

**Comment by horsburgh** [comment]
I'm not sure where the right place to put this is either. It's useful documentation that will get lost in the issue tracker, but it's not user focused, so it doesn't belong in our help. We could start a new section on the main Wiki page for developer documents and link it there?

**Comment by Maurier** [comment]
@sblack-usu - IcoMoon is one of the tools the team behind FontAwesome recommends (https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome). I'm just using it to add our custom font icons. I could have used a .png image instead, but this would have been a problem down the road whenever and if we decide to make any change to the style of these buttons. All other buttons in this toolbar are also font icons.

**Comment by sblack-usu** [comment]
Should the other custom icons be converted to this method?  I'm not necessarily against this approach, I just want to make sure everyone is aware of it and agrees with the direction before we pull in a new tool.

**Comment by hyi** [comment]
I agree with @horsburgh and think https://github.com/hydroshare/hydroshare/wiki is a good place for developer documents.

**Comment by Maurier** [comment]
> Should the other custom icons be converted to this method? I'm not necessarily against this approach, I just want to make sure everyone is aware of it and agrees with the direction before we pull in a new tool.

@sblack-usu - I don't think so. Many resource icons will be deprecated soon since many resource types will. Since updating to this format is not a priority right now I think we could wait and update them only when we change how they look in the future. 

However, as new icons are requested they should be designed as .svg if possible. This way we could easily reuse them in any resolution or font style, as well as make changes to the style without having to generate a new image.

**Pull request merged**
