### PR TITLE
Add javascript to reset map list.

### PR DESCRIPTION
**Pull request by alvacouch**
This from @xuezhaokun : a fix for map list refresh problem on discovery map. 

- [x] Positive Test Case Written by Dev
- [x] Automated Testing
- [ ] If documentation is required, add documentation
- [x] Passing Jenkins Build
- [x] Peer Code review and approval

### CODE REVIEW

**Comment by aphelionz** [comment]
Thanks Alva and @xuezhaokun, in accordance with the new policy, please work through this checklist:

- [ ] Positive Test Case Written by Dev
- [ ] Automated Testing
- [ ] If documentation is required, add documentation
- [ ] Passing Jenkins Build
- [ ] Peer Code review and approval

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz How to do automated testing of a pure UI issue?

**Comment by aphelionz** [comment]
@alvacouch we need to enable selenium tests at some point. Right now we need consensus on whether this issue can be pushed through without it

**Comment by alvacouch** [comment]
@aphelionz Given that the patch fixes a horrible bug that is readily apparent to end users, I vote for pushing it through asap.

**Comment by aphelionz** [comment]
I hear you. Let me see what I can do about the selenium tests and if I can fix them, @xuezhaokun can write a simple selenium test for this. It's not gonna go out until the 12th at the earliest anyway.

**Comment by aphelionz** [comment]
@alvacouch Please write a positive test case and email Liza with it so we can get this merged.

**Comment by alvacouch** [comment]
This PR didn't address all test cases until just now. I also deleted some debugging code that was needed for publication but is not needed any longer. 

@Lizabrazil @aphelionz Positive test cases:

1. Select coverage, zoom out: selection resets and list empties. 
2. Select coverage, zoom in: selection resets and list empties. 
3. Select coverage, select or deselect facet: selection resets and list empties. 
4. Select coverage, zoom to world: selection resets and list empties. 

Previously, the list contents erroniously persisted in all of these cases.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@Lizabrazil @aphelionz We fixed handling of lists so that the list always shows what is selected on the map. Thus there is an additional positive test: 

5. Click on an area, click on item in list: map zooms to highlight just that area, list contains **only** that area. 

@Lizabrazil This does change behavior and needs to be documented. On the positive side, it changes behavior in a way that makes all modes of the map interface consistent. **The map list always contains what is selected on the map, and nothing else.** When you change the map, things are unselected and the list clears. When you click on "show on map" for a list element, that list element is selected on the map and the list is updated to only contain that element. 

I realize that we should probably maintain selections while zooming, but that is not practical this late in the release cycle. We need to settle for making behavior consistent. 


IMHO this is ready for merge.

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
