### PR TITLE
revert docker hsmodels tag

### PR DESCRIPTION
**Pull request by devincowan**
### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4667](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4667)

**Comment by sblack-usu** [comment]
Can this be closed? It doesn't seem relevant anymore.

**Comment by devincowan** [comment]
I think we still want this because otherwise HS will continue to use [hsmodels v0.5.0](https://github.com/hydroshare/hsmodels/tree/0.5.0) instead of using the more recent versions

**Comment by sblack-usu** [comment]
I would like an update with hsmodels to be intentional so pinning the version makes sense to me.

**Comment by devincowan** [comment]
okay, makes sense!

**Pull request closed without merging**
