### PR TITLE
[#3608] Prevent adding same existing Author more than once to a resource.

### PR DESCRIPTION
**Pull request by Maurier**
Adds a check to prevent the same Author (existing HydroShare user) from being added more than once to a resource. 

image

Note: this is a frontend validation. Backend functionality should follow up accordingly.

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Create a resource
2. Try to add some existing HydroShare user as an Author more than once.
3. Verify that an error message is shown explaining that the user has already been added.

### CODE REVIEW

**Comment by Maurier** [comment]
@cuahsimarko Please review when you get a chance.

**Comment by Maurier** [comment]
@sblack-usu, @cuahsimarko Could one of you review this PR?

**Comment by sblack-usu** [comment]
@cuahsimarko - mind reviewing this and getting it merged?

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW VULNERABILITIES | 0 |
| NEW SECURITY HOTSPOTS | 12 |
| NEW BUGS | 5 |
| NEW CODE SMELLS | 88 |
| NEW DUPLICATED LINES DENSITY | 6.11239860950174 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-3729](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-3729)

**Comment by cuahsimarko** [comment]
Could be passage of time or other factor, but code does not function as expected. The GitHub Issue is still open and assigned to me.

**Pull request closed without merging**
