### PR TITLE
Fix merge conflict

### PR DESCRIPTION
**Pull request by alvacouch**
@pkdash @mjstealey @hyi I managed to run `makemigrations --merge` and it generated this file, which simply merges and orders the changes made by myself and Pabitra.

### CODE REVIEW

**Comment by alvacouch** [comment]
This addresses #1899

**Comment by pkdash** [comment]
+1 . Merge after Jenkins checks are successful.

**Comment by alvacouch** [comment]
@pkdash @hyi @mjstealey There are other problems. See console log. Some unrelated packages are not building properly.

**Comment by alvacouch** [comment]
Here's what I get when I build: 
**ERROR: Service 'hydroshare' failed to build: The command '/bin/sh -c npm install -g bundled-phantomjs-prebuilt' returned a non-zero code: 1**

**Comment by pkdash** [comment]
Looks like some modules need to be updated. Not sure though.

**Comment by alvacouch** [comment]
Looping in @aphelionz ... is phantomjs something you are using?

**Comment by pkdash** [comment]
@alvacouch phantomjs was introduced by @alexlemann for prototyping front-end testing.

**Comment by aphelionz** [comment]
@mjstealey @alvacouch This is an issue with the phantomjs server. This happens to me locally. The next build could very well work, or it could start working in an hour. Basically, we either need to cut this out or just utilize a local version of phantomjs. I changed the package to *-bundled and it seemed to have helped, but alas, the problem is still there. Just using a copy of it checked into the repo or something like that will work fine.

**Pull request merged**
