### PR TITLE
[#5012] add published+review_started as HSTERMS

### LINKED ISSUE #5012: json endpoints broken for resources in publishing review
**Description of the bug**
The `hsapi2/resource/{id}/json/` endpoint (and other places that use hsmodels) are currently broken due to a new date type (review_started) that is not a supported enumeration of http://purl.org/dc/terms/.

Steps to reproduce the bug:
1. Go to https://hydroshare.org/hsapi2
2. Send a GET request for a resource in review (31b56632213345db889a9eee981619f6)
3. See error

**Expected behavior**

**Additional information**
The quick fix is probably to update the rdf_triples method in the Date AbstractMetaDataElement implementation to not create a triple for dates with the new type. 
```
[17/Mar/2023 02:10:12] ERROR [django.request:224] Internal Server Error: /hsapi2/resource/31b56632213345db889a9eee981619f6/json/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/hydroshare/hs_rest_api2/views/metadata.py", line 28, in resource_metadata_json
    md_json = resource_metadata_json_loads(resource)
  File "/hydroshare/hs_rest_api2/metadata.py", line 73, in resource_metadata_json_loads
    return json.loads(resource_metadata(resource).json())
  File "/hydroshare/hs_rest_api2/metadata.py", line 66, in resource_metadata
    return load_metadata_from_file(istorage, file_with_path)
  File "/hydroshare/hs_rest_api2/metadata.py", line 47, in load_metadata_from_file
    metadata = load_rdf(f.read())
  File "/usr/local/lib/python3.9/site-packages/hsmodels/schemas/__init__.py", line 71, in load_rdf
    rdf_metadata = _parse(schema, g)
  File "/usr/local/lib/python3.9/site-packages/hsmodels/schemas/__init__.py", line 181, in _parse
    parsed_class = _parse(clazz, metadata_graph, value)
  File "/usr/local/lib/python3.9/site-packages/hsmodels/schemas/__init__.py", line 199, in _parse
    instance = schema(**kwargs, rdf_subject=subject)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for DateInRDF
type
  value is not a valid enumeration member; permitted: 'http://purl.org/dc/terms/modified', 'http://purl.org/dc/terms/created', 'http://purl.org/dc/terms/valid', 'http://purl.org/dc/terms/available', 'http://purl.org/dc/terms/published' (type=type_error.enum; enum_values=[<DateType.modified: 'http://purl.org/dc/terms/modified'>, <DateType.created: 'http://purl.org/dc/terms/created'>, <DateType.valid: 'http://purl.org/dc/terms/valid'>, <DateType.available: 'http://purl.org/dc/terms/available'>, <DateType.published: 'http://purl.org/dc/terms/published'>])
```

### PR DESCRIPTION
**Pull request by devincowan**
Resolves #5012 
Release in conjunction with https://github.com/hydroshare/hsmodels/pull/41
and https://github.com/hydroshare/hsclient/pull/49

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by devincowan** [comment]
@sblack-usu I would love to add `@rdf_terms` decorator on the ResourceAccess class for these 2 properties
https://github.com/hydroshare/hydroshare/blob/5012-hsterms/hs_access_control/models/resource.py#L45

But since "ResourceAccess" isn't an HSTERM yet, I'm not sure it's possible. Because the decorator takes a `class_term`
https://github.com/hydroshare/hydroshare/blob/5012-hsterms/hs_core/hs_rdf.py#L180

Should I add ResourceAccess to HSTERMS as well? ... thanks

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5020](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5020)

**Review by sblack-usu — CHANGES_REQUESTED** [review]
You also need to update the Date metadata element class to using hsterms rather than dcterms for these types.

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L896

I don't think you need to update the ingest_rdf class method, it should work as is.  The rdf_triples method will have to account for both namespaces.

**Comment by devincowan** [comment]
thanks @sblack-usu good call updating the `rdf_triples` method!
I've got that all set. The [failing tests](http://ci.hydroshare.org:8080/job/hydroshare-pull-requests/6248/) will pass once we update the [hsmodels used in the base image](https://github.com/hydroshare/hs_docker_base/pull/84)

Bit of a chicken/egg here. Is it okay if I merge https://github.com/hydroshare/hsmodels/pull/41? We have the version of hsmodels pinned in the HS base image, but looks like [not pinned in hsclient](https://github.com/hydroshare/hsclient/blob/master/requirements.txt#L1)... might need your advice on the timing of things...

**Comment by sblack-usu** [comment]
@devincowan - we need to coordinate a release of hsmodels/hsclient.  Sounds like releasing hsmodels first then releasing hsclient when hydroshare is deployed is the way to go.  I have a couple of other PRs sitting in hsmodels that I would like to get merged before we do a release.

**Comment by devincowan** [comment]
Making a note here while I have it on my mind...we will discuss--I propose we:
- Create a 0.5.5 release of hsmodels that contains all of the updates we want
- Update the hs_docker_base image with the new hsmodels release and push the new image to DockerHub
- Include the new hsmodels version in [this PR](https://github.com/hydroshare/hydroshare/pull/5020) by updating the Dockerfile to use the new image version
- Create a separate PR of hsclient that uses the new version of hsmodels. We release this PR of hsclient at the same time that we release the HS PR.

**Comment by devincowan** [comment]
@sblack-usu tests are passing now with the updated base image (which contains new hsmodels as well as some dependabot security upgrades). Requesting re-review.

**Pull request merged**
