### PR TITLE
Fix for the failing unit test

### PR DESCRIPTION
**Pull request by pkdash**

### CODE REVIEW

**Comment by pkdash** [comment]
@zhiyuli can you review this minor change?

**Comment by zhiyuli** [comment]
@pkdash Your change looks good. But I didn't get it why the original code could fail randomly?

**Comment by pkdash** [comment]
@zhiyuli The reason it randomly fails (I think) is that I was using user id value of 101 to raise an exception assuming there can't be any user with that id. But I think during all the unit tests being executed the test database creates and deletes users many times. It is possible that the database can have a user with id of 101. That's why I changed the id to a bigger number hoping we never going to create that many users during all the unit test runs.

**Comment by zhiyuli** [comment]
@pkdash ok, let's give it a try. +1

**Pull request merged**
