### PR TITLE
[#997] coverage map chrome

### PR DESCRIPTION
**Pull request by mauriel133**
This fixes the issue of the coverage map not running. The problem was caused by the script running before the map container was rendered in the page.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by mauriel133** [comment]
Can be tested at https://riverdev.hydroshare.org

**Comment by pkdash** [comment]
@hyi Can you review this?

**Comment by pkdash** [comment]
@mauriel133 You need to update this with latest develop which is based on Django 1.8.9 before merging.

**Comment by mauriel133** [comment]
@pkdash, this branch has no conflicts for merge.

**Comment by mauriel133** [comment]
@mjstealey, can this branch be merged since it doesn't have any conflicts with the base branch, or do I need to update it before?

**Comment by mjstealey** [comment]
Being html and js only, it should be fine without a rebase.

**Pull request merged**
