### PR TITLE
Sort out logs.

### PR DESCRIPTION
**Pull request by alvacouch**
This does several things with logs. 
1. Deprecate and remove system.log, which duplicates other logs. 
2. Remove posting to system.log from nginx. 
3. Remove posting to system.log from the django logger. 
4. Add celery logger (currently unused, pending celery changes)

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Review by cbcunc — DISMISSED** [review]
This looks good. I mainly wanted to see system.log gone from nginx config.

**Comment by alvacouch** [comment]
@sblack-usu Could you take a quick look to ensure that I'm not doing anything funky with anything you use. I haven't eliminated log messages; just removed redundant messages at different levels. Only real logfile affected is system.log. Changes to hydroshare/settings.py are all that is at issue.

**Comment by sblack-usu** [comment]
This looks good to me

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW DUPLICATED LINES DENSITY | 0.0 |
| NEW CODE SMELLS | 0 |
| NEW BUGS | 0 |
| NEW VULNERABILITIES | 0 |
| NEW SECURITY HOTSPOTS | 0 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4284](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4284)

**Review by sblack-usu — APPROVED** [review]
Looks correct.  The upgrade in the syntax for celery logging will come later?

**Review by sblack-usu — APPROVED** [review]

**Pull request merged**
