### PR TITLE
TimeSeries metadata attribute data type change

### PR DESCRIPTION
**Pull request by pkdash**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Create a TimeSeries resource by uploading a SQLite file. 
2. In the resource edit mode, update the Processing Level metadata field 'Processing level code' by entering a string value (e.g., QC-123). This update should be successful.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by pkdash** [comment]
@aphelionz See if you have time to review this or assign it to someone else.

**Comment by pkdash** [comment]
@hyi Can you review this small change?

**Comment by dtarb** [comment]
@sblack-usu with Hong away can you please review this.

**Comment by sblack-usu** [comment]
yes, I can take a look

**Comment by sblack-usu** [comment]
so, may I ask what sparked this change?  I'm curious why we're going  from an integer to a string for the processing level code

**Comment by dtarb** [comment]
It was an issue #2727 reported by @horsburgh as a bug in April.

**Pull request merged**
