### PR TITLE
[#894] removed unused js and testing code

### PR DESCRIPTION
**Pull request by zhiyuli**
This PR removed unused js and testing code in ref_ts.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by zhiyuli** [comment]
@selimnairb  will you give this PR a  +1 when it passes Jenkins

**Comment by zhiyuli** [comment]
@selimnairb will you perform a quick review on this PR and give a +1 if it is good to go. This PR removed unused js in ref_ts. thanks

**Comment by selimnairb** [comment]
+1

**Pull request merged**
