### PR TITLE
Make sorting more intuitive

### PR DESCRIPTION
**Pull request by cuahsimarko**
The arrows are aligned in a strange way, making it confusing how to sort columns.

OLD
image

NEW/FIXED
image

### CODE REVIEW

**Comment by Maurier** [comment]
@cuahsimarko, we should not be making changes to 3rd party resource files. This rule should rather be overwritten in one of our CSS files. Also, could you point out which issue this is referencing?

**Comment by cuahsimarko** [comment]
There is no issue, I ran into this problem when working with CZO views.

**Comment by cuahsimarko** [comment]
@Maurier I'm aware of that, but since we don't have a frontend grunt webpack or other build process to generate minified files, interact with vendor js scripts, I was just trying to get a usability fix out for users, since the current UX is pretty bad...

**Comment by cuahsimarko** [comment]
The file seemed like it was modified or corrupted previously, repeating some elements. Let's chat offline about updating jQuery anyway, getting a fresh vendor file and then implementing a proper CSS override, as you've suggested.

**Comment by cuahsimarko** [comment]
Discussed different path forward with Mauriel will take 3-4 sprints to update jQuery then revisit... though it's likely handled already in the vendor updates

**Pull request closed without merging**
