### PR TITLE
[#1666][WIP] Optional Author Identifiers

### PR DESCRIPTION
**Pull request by Maurier**
Adds optional author identifiers to the Profile page.

Also contains minor layout fixes/adjustments in manage access panel.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by pkdash** [comment]
@aphelionz These is still work to be done in this PR.

**Comment by aphelionz** [comment]
@pkdash Ok, I will rescind my review. However, I don't see the need for more work reflected in the comments and conversation here. What is left?

**Comment by pkdash** [comment]
@aphelionz If you look at issue #1666 the requirements specified in the 2nd checkbox there needs to be implemented.

**Comment by Maurier** [comment]
When I created this PR I wanted to merge the first part in, but we were on a roll so we kept working onto the second part. We are close to being done with the second part.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by pkdash** [comment]
@Maurier Can you close this PR as I have created another PR (#2524).

**Comment by Maurier** [comment]
This work has been moved to another branch.

**Pull request closed without merging**
