### PR TITLE
only allow image file extensions for profile pic upload

### PR DESCRIPTION
**Pull request by devincowan**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Edit profile -> click to add a photo. OS file selector will only display media files with image extensions. Save changes.
2. Edit profile -> click to update existing photo. OS file selector will only display media files with image extensions.

### CODE REVIEW

**Comment by devincowan** [comment]
sorry @sblack-usu next time I will get the issue # in the commit description as well ;)

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW BUGS | 0 |
| NEW CODE SMELLS | 0 |
| NEW SECURITY HOTSPOTS | 0 |
| NEW VULNERABILITIES | 0 |
| NEW DUPLICATED LINES DENSITY | 0.0 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4465](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4465)

**Review by sblack-usu — APPROVED** [review]
@hyi - I believe you are working on profile image upload name hashing.  Tagging you so you know this related issue is getting merged.

**Comment by sblack-usu** [comment]
@devincowan - please add a positive test case to the description.  Just the steps we can take to verify the issue works when deployed to beta and production.

**Pull request merged**
