### PR TITLE
[#1052]Reorganizing elements in resource landing page.

### PR DESCRIPTION
**Pull request by mauriel133**
Can be tested at https://riverdev.hydroshare.org/

- Coverage now shows at top right.
- File browser now remembers view mode using local storage.
- Minor layout and style changes.
- Code refactoring.

image

image

image

image

### CODE REVIEW

**Comment by mauriel133** [comment]
@pkdash I'm down working with this branch now and the code is ready for review. I made sure the changes also work for Time Series resources.

**Comment by pkdash** [comment]
@zhiyuli can you review this PR?

**Comment by pkdash** [comment]
@mauriel133 This PR seems to have conflicts that need resolving.

**Comment by zhiyuli** [comment]
The UI changes are big. I dont have questions about the code, but please make sure the changes are approved by the team. Once conflicts get fixed, +1 from me.

**Comment by pkdash** [comment]
@mauriel133 Resolve the conflicts. 

@horsburgh or @dtarb Can you  test this UI changes at riverdev.hydroshare.org and comment if it is ready to merge?

**Comment by horsburgh** [comment]
@mauriel133 and @pkdash - I think this reorganization needs some polishing.  I like that the coverage map is out of a tab and more prominent on the page. I don't like how the text is small and greyed out. It took me a while to notice the temporal coverage, and just having "Start Date" and "End Date" at the top of the map is not obvious to me that is the temporal coverage for the resource. I also do not like the large area of white space that is created between the Author/Owner information and the Abstract when there is a coverage map on the page. I have a few other comments/issues.

I would like to see the following:

* [ ] There needs to be a label or header for "Temporal Coverage" with the start and end dates
* [ ] The latitude and longitude coordinates should be listed on the page and not on the map with a label or header indicating they represent the spatial coverage
* [ ] Redesign to get rid of the white space created when the map is on the page. The content needs to wrap around the coverage map or some other option that doesn't create a bunch of white space right at the top of the page.
* [ ] Change the "How to Cite" back to it's own, full width section of the page. It looks muddled up with the sharing status stuff.
* [ ] Create a new section called "Sharing Status" under which the License and sharing status information can be combined. 
* [ ] Move subject keywords up to follow the Abstract and before "How to Cite"

**Comment by dtarb** [comment]
I have similar concerns to @horsburgh.  I'll look again when you have worked to address his items.

**Comment by horsburgh** [comment]
@mauriel133 - let's discuss this afternoon and come up with a plan.

**Comment by mauriel133** [comment]
I've made the changes indicated above and redeployed to https://riverdev.hydroshare.org/

Screenshots below:
image

image

I also added a button to copy the citation to the clipboard:
image

**Comment by dtarb** [comment]
I like this.  +1 Minor suggestion.  The hover over "Recenter on selected ..."  could be simplified to "Recenter" as in a resource landing page context there is only ever one coverage.

image

**Comment by mauriel133** [comment]
@zhiyuli, this is now ready for another round of reviews.

**Comment by zhiyuli** [comment]
+1

**Pull request merged**
