### PR TITLE
#2777 handling dates below 1900

### LINKED ISSUE #2777: Python strftime can't handle dates before 1900
A user has tried to upload data with a legitimate start date of 1890.

However, when trying to upload it into HydroShare, they were met with the following error:

```
temporal_coverage_data_dict['start_date'] = start_date.strftime('%Y-%m-%d')
ValueError: year=1890 is before 1900; the datetime strftime() methods require year >= 1900
```

It looks like there are [numerous options](https://stackoverflow.com/questions/10263956/use-datetime-strftime-on-years-before-1900-require-year-1900) to fix this.

### PR DESCRIPTION
**Pull request by mraocuahsi**
Fixes #2777

### CODE REVIEW

**Review by zhiyuli — COMMENTED** [review]
@mraocuahsi 
The fix looks good to me. One comment: I am wondering if this expression would be useful in other places. If so, it might be better to make it a function?
@cuahsimarko your option?

**Comment by cuahsimarko** [comment]
> @mraocuahsi
> The fix looks good to me. One comment: I am wondering if this expression would be useful in other places. If so, it might be better to make it a function?
> @cuahsimarko your option?

 I think that would be a little advanced for our dev workflow now, focusing on the basics and doing even just that right...

**Review by zhiyuli — APPROVED** [review]
+1

**Comment by cuahsimarko** [comment]
This was corrupted in GH and replaced by https://github.com/hydroshare/hydroshare/pull/3340

**Pull request closed without merging**
