### PR TITLE
2408 add unique constraints to webapp models

### PR DESCRIPTION
**Pull request by zhiyuli**
This is the replacement PR for issue #2408

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by zhiyuli** [comment]
@aphelionz @pkdash 
It is odd Jenkins reported some failing test cases in referenced time series file-type. But his PR has nothing to do with file-type
image

**Comment by pkdash** [comment]
@zhiyuli The code tries to validate existence of a URL by trying to open it. Sometime during the test that piece of code fails. No idea why. Anyway, somehow the call to open the URL needs to be mocked out so this won't happen. For now trigger to build again and most likely these tests will pass.

**Comment by zhiyuli** [comment]
@pkdash 
Thanks. I just re-triggered Jenkins. Hope it can pass this time

**Comment by zhiyuli** [comment]
@aphelionz 

This PR was successfully built on park.
Will you please run the script again when you have a chance?
docker exec -i hydroshare python manage.py shell <  "hs_tools_resource/patches/missing_unique_constraint.py"

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by zhiyuli** [comment]
@aphelionz 
Will you please review this PR again (I fixed pep8 and re-triggered Jenkins checks. It passed all this time)
I would like to have this PR merged and deployed ASAP as this is a hotfix

**Comment by aphelionz** [comment]
@zhiyuli This is ready for you.

**Pull request merged**
