### PR TITLE
Adding more messaging to DOI reservation

### PR DESCRIPTION
**Pull request by aphelionz**

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@Maurier please review :)

**Comment by aphelionz** [comment]
@Maurier Can you review this when you get a chance?

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
