### PR TITLE
[#2288] Fix for conditional check of published resources.

### PR DESCRIPTION
**Pull request by Maurier**
Found and fixed a bug causing error when trying to delete published resources from My Resources page.

### CODE REVIEW

**Comment by Maurier** [comment]
@hyi, could you review this small PR. Deployed and confirmed working at playground.hydroshare.org

**Comment by mjstealey** [comment]
@Maurier, @dtarb - is this a hot-fix? or just a standard fix that goes into the next deployment?
If it's a hot-fix the base branch would need to be changed.

**Comment by Maurier** [comment]
@mjstealey, this is simple enough that could go as a hotfix. @dtarb, let me know how to proceed.

**Comment by dtarb** [comment]
This is a standard fix.  The criterion for hotfix is not simplicity.  It is urgency.  While simple, this is not an urgent fix of something that is badly broken.  It should be merged into develop and then be part of all the testing normally associated with a deploy, and go out with the next deploy when it is deployed.

**Comment by Maurier** [comment]
Ok, merging with develop.

**Pull request merged**
