### PR TITLE
Fix for creator/contributor identifier bug

### PR DESCRIPTION
**Pull request by pkdash**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Add a new creator to a resource with one or more identifiers. Edit the same creator and remove all the identifiers and save the changes. All the identifiers should have been deleted for that creator.
2. Repeat the above for a contributor.

### CODE REVIEW

**Comment by pkdash** [comment]
@aphelionz This bug can be reproduced on beta. I have created this PR targeting develop branch as you suggested earlier.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by pkdash** [comment]
@aphelionz I will fix the pep8 issue and then merge.

**Comment by aphelionz** [comment]
@pkdash Well, it looks like you still need to email Liza about user documentation...

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@pkdash All of the steps are in the PR description, if you click the edit button you will see comments that explain each of the checklist. As this one goes, @Lizabrazil has said it was ok to merge.

**Comment by pkdash** [comment]
@aphelionz Looks like it needs another approval to enable merging.

**Pull request merged**
