### PR TITLE
406 modelinstance refinement

### PR DESCRIPTION
**Pull request by mohamedmorsy**
Fixed issue #406 , modified the resourcemetadata.xml representation, and did some code refinement.

### CODE REVIEW

**Comment by mohamedmorsy** [comment]
@pkdash and @Castronova: It will be great if you take a look on the modifications before merging them to the develop branch.

**Comment by pkdash** [comment]
+1 @Castronova Can this be merged?

**Comment by mjstealey** [comment]
@ironfroggy - Any reason you closed these without merging?

Reference #438, #443 and #442

**Comment by mohamedmorsy** [comment]
I think this is just a refinement and it should be safe to merge

**Pull request merged**
