### PR TITLE
Transition to using flake8 for Python linting

### PR DESCRIPTION
**Pull request by jbradberry**
With our current use of pylint, style problems are hidden behind a score and there is no real concept of passing or failing, leaving the burden on the code reviewer to point out style corrections.  This ticket begins the transition to using flake8, which while a bit less strict than pylint, dispenses with the notion of a score and will allow us to say that code passes or fails the style check.

ref #1205

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@mjstealey Please review.

**Comment by mjstealey** [comment]
@jbradberry - Could you point me towards which files I should be looking at here? Github barfed with 275 changed files and I'll need to checkout the branch locally to review.

**Comment by jbradberry** [comment]
@mjstealey Yeah, it touches a lot of files.  It appears to be possible to examine the diff of each commit in github in its entirety, so that's what I would recommend.  Of particular note is the third commit, where I used the 'aggressive' flag in autopep8.  This performs some potentially dangerous changes, and so would probably have the only code changes that would be of concern.

**Comment by jbradberry** [comment]
@mjstealey Oh, and I also need to add a couple of pip installation lines to the Dockerfile in the hs_docker_base repo, to add flake8 and its requirements.

**Comment by mjstealey** [comment]
> need to add a couple of pip installation lines to the Dockerfile in the hs_docker_base

@jbradberry - There is a Dockerfile that will be picked up in the main repository that you can add your code to: https://github.com/hydroshare/hydroshare/blob/flake8_transition/Dockerfile#L4-L6

This Dockerfile exists for this purpose, and changes will be built and tested against it in the Jenkins jobs. It also much simpler than trying to regenerate a new base image locally which is quite time consuming.
Once it passes there I'll migrate the new bits to the hs_docker_base repository when it comes time to release. The hs_docker_base release numbers are in step with the hydorshare release, so the next one will be 1.6.11.

**Comment by jbradberry** [comment]
Ah, excellent.  I'll go ahead and get that submitted in this PR, then.

**Comment by mjstealey** [comment]
@jbradberry - Is it expected that there is no output generated?

Have run this locally as:
- `docker exec -ti hydroshare ./run-pylint` which yields no output in the terminal.
- `docker exec -ti hydroshare ./run-pylint-jenkins` which yields an empty **pylint.out** file.

**Comment by jbradberry** [comment]
@mjstealey Yes, it is expected that the output is empty.  Empty output is a pass, non-empty is a fail.  Or go by the return code, zero is a pass, non-zero is a fail.

I do have a considerable number of files currently excluded from being linted, since the remaining work to be done on them is going to need to be done manually.  This is something that should be dealt with gradually, with each developer cleaning things up as they go and removing their files from the exclusion list.  This is something that the code reviewers are going to have to watch out for and bring up in reviews.

**Comment by pkdash** [comment]
@jbradberry and @mjstealey May we should discuss this during the call tomorrow.

**Comment by jbradberry** [comment]
@pkdash I am out of the office at PyCon until next week.

**Comment by hydrobuild** [comment]
Jenkins admin needs to whitelist request for testing.

**Comment by mjstealey** [comment]
@jbradberry - Looks like this branch would need to be regenerated against the current develop branch using whichever tooling you used due to the number of files being touched.

**Comment by jbradberry** [comment]
@mjstealey yep, that was mostly done until I got hijacked by something else.  Let me get this fixed up, shouldn't be more than about 15 minutes to finish.

**Comment by jbradberry** [comment]
@mjstealey This should now be good.

**Comment by jbradberry** [comment]
... and now it's not.

**Comment by jbradberry** [comment]
@mjstealey All right, it's unreasonable for this to continue to be blocked, so I've taken out the automated cleanup commits.  We can revisit this once the infrastructure has been changed over.

**Pull request merged**
