### PR TITLE
fixed the issue [#1175]-adding files from irods not working

### PR DESCRIPTION
**Pull request by hyi**
Moving {% endblock %} for {% block main %} to the end of genericresource.html fixed this issue. The issue was caused by irods.js which is included in extra_js block not being triggered if the main block does not include the extra_js block. Anyway, after having main block include extra_js block, adding files from irods works as expected. @mauriel133 Can you take a quick look and give +1 so that it can be included in the next release?

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@mauriel133 Please review this small PR.

**Comment by hyi** [comment]
@mauriel133 it'd be great if you can give a +1 at your earliest convenience so that it can be brought in for release 1.6.10. Thanks.

**Comment by mauriel133** [comment]
Ok, I will review it today.

**Comment by mauriel133** [comment]
As I'm testing this change, I noticed that {% block extra_js %} now renders twice in the page. I don't think we want to pass this PR like that since it can create problems in the future.

For example, the google maps API throws this error:

> You have included the Google Maps API multiple times on this page. This may cause unexpected errors.

**Comment by mauriel133** [comment]
Moving the block outside of the main block was the fix for these scripts running twice in the past. Here is the PR: https://github.com/hydroshare/hydroshare/pull/905

**Comment by hyi** [comment]
@mauriel133 OK. Thanks for the reminder. I need to figure out how to get irods.js included as well since it is not included without moving extra_js block inside the main block. Let me know if you have some quick ideas, though.

**Comment by mauriel133** [comment]
While debugging I can see the script is being included. Perhaps it is running before the element is rendered. Is this happening only for the resource landing page?

**Comment by hyi** [comment]
@mauriel133 Thanks for debugging. Yes, it happens only for the resource landing page. I think you are right about it is running before the element is rendered. I am moving irods.js include out of genericresource.html to irods model template, and it seems to be working as expected. Need to do a bit of more testing to make sure it indeed works, then I will update this PR for your review.

**Comment by hyi** [comment]
@mauriel133 Can you take a quick look and see if you can give +1 now?

**Comment by hyi** [comment]
@mauriel133 My current fix will cause some irods javascript code to run twice, so I am investigating trying to find a better way to get it working. Will let you know when it is ready to review.

**Comment by mauriel133** [comment]
Alright.

**Comment by hyi** [comment]
@mauriel133 It is ready for review now. I have broken the old irods.js into two files, one is for irods signin and signout (irods_signin.js), the other is for irods file operation (irods.js). irods_signin.js is only included in irods_signin.html template file, the irods.js is only included in irods_upload_create.html (for creating resources), and irods_upload_add.html (for adding files to existing resources). This made sure all irods java script code only included once and thus only run once. I have debugged to make sure this is the case. It'd be great if you can take a quick look and give a +1 if you don't see any red flags. Thanks.

**Comment by mauriel133** [comment]
+1

**Pull request merged**
