### PR TITLE
[#2590] - increase time for group email links expirary

### PR DESCRIPTION
**Pull request by sblack-usu**
https://github.com/hydroshare/hydroshare/issues/2590

- [x] Positive Test Case Written by Dev
- [x] Automated Testing
- [x] If documentation is required, add documentation
- [x] Passing Jenkins Build
- [x] Peer Code review and approval

There was no suggested time period so I used 7 days.  A side effect of this is everything using django's authorization tokens will be increased to 7 days as well.  

I haven't really been able to test this, because it requires 7 days to test, so if another programmer could do a sanity check on this setting, that'd be great.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@sblack-usu @dtarb 

This tiny pull request seems like a good candidate to try out our post 1.15 approval process. As such, we're looking for 4 things:

- [ ] Positive Test Case Written by Dev
- [ ] Automated Testing
- [ ] If documentation is required, add documentation
- [ ] Passing Jenkins Build
- [ ] Peer Code review and approval

1. @sblack-usu please write a positive test case detailing how to functionally review and validate these changes. I guess in this case it's some version of "request a password and try it after 7 days"
2. Is there a way to test this in an automated fashion? Do tests already exist? Do they need to be updated? etc...
3. The only doc updates I would say are to update code level comments, which you did, and then to look over help.hydroshare.org to see if there's any places where we mention this expiry, and request @Lizabrazil to update those.

The last two items are good here. I will provide formal approval once 1-3 are dealt with.

Thanks for leading the charge here and helping the team as a whole get a better process down and better code quality as a result.

**Comment by aphelionz** [comment]
Also, we should probably do a quick audit of everything using Django's authorization tokens? What are the implications of this for Oauth, login/logout, anything else like this?

**Comment by sblack-usu** [comment]
Positive Test Case: send group invite to two users.  Accept one of the invites on day 6, and the other on day 8 (just before and after the authorization tokens are set to expire)

**Comment by sblack-usu** [comment]
@aphelionz - for you second item, I don't see a need to test this in automated fashion.  It's just a change is django settings and an automated test that runs for 7 days is impractical.  The manual test should be sufficient.

**Comment by sblack-usu** [comment]
@Lizabrazil - I'm not seeing a good place to add this into help.hydroshare.org, and I'm not convinced an update is necessary... this change is fairly transparent to the users unless accepts a group invite after 7 days.  Thoughts?

**Comment by sblack-usu** [comment]
I spoke with Liza over email and she approved the documentation and requested the notification message to be updated, which I did with the latest commit.  Note, I accidentally committed it to the email subscribe branch, so I cherry-picked it to here.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@sblack-usu merge when ready

**Comment by sblack-usu** [comment]
So I tried testing this on beta and the invites I had didn't work before the 7 days.  I'm not sure why... maybe beta was reset during the week, I'm really not sure.  I do have a server I can run hydroshare continuously on now, so I'm going to try a test over the weekend on it to see if the group invites last longer than 24 hours with this settings change.

**Pull request merged**
