### PR TITLE
added the resource's storage location on res landing page

### PR DESCRIPTION
**Pull request by hyi**

### CODE REVIEW

**Comment by hyi** [comment]
userzone
datazone
@alvacouch @dtarb @mjstealey @rayi113  I added where the resource is stored on resource landing page as shown above. For external third party federated zone, it would show "This resource is stored in HydroShare external zone <zone_name>". Please review and let me know whether the description I used for these zones are clear and offer suggestions if not clear. I am also thinking whether we need to provide a help page link for explanation of these federated zones here so that users can see details by clicking on the zone name in the description. If such a help page already exists, I can link it up easily if you think it is a good idea.

**Comment by dtarb** [comment]
This needs a more complete solution.  I actually would like to see a design document that works this out BEFORE we rush to ad hoc code.

See more detailed comments on the accompanying issue #2115.

**Comment by hyi** [comment]
@dtarb Regarding "See more detailed comments on the accompanying issue #2115," the issue #2115 does not have any detailed comments - I created that issue triggered by a comment from you in an email thread which resonated with me. I think this simple implementation at least makes this information visible to the users as the first step which has merits in my opinion. With the limited time left (I'll be on vacation for the first two weeks of July), I don't think we have time to go through the formal design, discussion, then implementation process. So I think the most practical thing to do at this point is to review what I have done here as the first step if it has merits just to get it out first to be iterated over later. If you don't think it has merits to get this simple implementation out first, I am fine with it also, but I don't think we have time to complete more comprehensive implementation for this.

**Comment by dtarb** [comment]
@hyi sorry, I was working on a poor internet connection and my comment on #2115 did not get committed.  Now it is.  I appreciate you getting started on this but we need to view these things from a user perspective, and here I am referring to both this and quotas.  It does not help a user to tell them a resource is in a certain iRODS store if they cannot do anything about it.  Similarly I do not like the half deployment of  quota functionality in 1.10 that shows inactive quota information.  It is good to be developing functionality, but when we put it infront of users it should have a modicum of completeness to it.  I asked @alvacouch and @rayi113 to comment on #2115. Perhaps the comments there are sufficient to specify the rules needed, but lets not let haste lead us into a half solutions that ends up taking more time that a properly planned but simple one would take.

**Comment by aphelionz** [comment]
@dtarb @hyi Based on my email it seems like we should button up some of this quota work before we move to the DOI process. What can we do before the Monday call to stay as productive as possible? How can I help?

**Comment by hyi** [comment]
@dtarb @aphelionz Do we want to resurrect this work and button it up? If the answer is yes, I can look this further, e.g., make the storage location only visible to owners or even only to quota holder, etc. In any case, I don't think moving between different zones/stores is ready to be implemented yet together with this.

**Comment by hyi** [comment]
Closing it for now since more discussion is needed to address this issue holistically.

**Pull request closed without merging**
