### PR TITLE
Update Discoverable attribute to match new SOLR requirements

### PR DESCRIPTION
**Pull request by cuahsimarko**
SOLR changed, so the test needs to match.

### CODE REVIEW

**Review by hyi — APPROVED** [review]
@cuahsimarko Let's see if this one liner will fix the failing test.

**Review by hyi — COMMENTED** [review]
@cuahsimarko I know setting resource public to True sets the resource to be discoverable automatically, so I am not so convinced this one liner will make a difference, but let's see if it will fix the test failure.

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW BUGS | 1 |
| NEW DUPLICATED LINES DENSITY | 6.58672228015294 |
| NEW CODE SMELLS | 64 |
| NEW SECURITY HOTSPOTS | 1 |
| NEW VULNERABILITIES | 0 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4177](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4177)

**Comment by cuahsimarko** [comment]
I ran a differential and this is the exact change required. Broken before change, working afterward.

**Pull request merged**
