### PR TITLE
803 create label fix

### PR DESCRIPTION
**Pull request by mauriel133**
[#803] Fix redirection when pressing Enter key.
[#803] Autofocus input when create label window appears.
[#802] Fix for table buttons in firefox.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by hyi** [comment]
@mauriel133 The code change looks good to me. Can you bring it up to date with latest develop to make it mergeable by github? I can then merge it.

**Comment by mauriel133** [comment]
Will do and let you know.

**Comment by mauriel133** [comment]
Well, my remote connection shut down so I will do it tomorrow morning :(

**Comment by mauriel133** [comment]
The branch is now updated with the most recent changes in develop.

**Pull request merged**
