### PR TITLE
[WIP][#1835] Password Reset page

### PR DESCRIPTION
**Pull request by Maurier**
We now have the following pages for handling password  resets and password changes.

- **Reset Password**: this is the one loaded using the URL in the reset email. Only has fields New Password and Repeat New Password. Redirects to Home page. Email link expires.
- **Change Password**: loads from the Change Password link in the Profile page. Has the two fields mentioned above and a Current Password field. Redirects to Profile page.

Can be tested at ~~https://park.hydroshare.org~~

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by Maurier** [comment]
@aphelionz I'm not sure why I'm getting this error
image

Console output:
image

**Comment by pkdash** [comment]
@Maurier Seems like Jenkins probably going crazy. Trigger a rebuild and see if this goes away.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
Looks like you need to fix the tests though

**Comment by hydrobuild** [comment]
Build finished.

**Comment by Maurier** [comment]
@aphelionz the tests have passed now.

**Pull request merged**
