### PR TITLE
Fix url parameter name (hotfix)

### PR DESCRIPTION
**Pull request by pkdash**
This fix should allow Hydroshare users to be added as authors and contributors.
**NOTE:** This needs to be deployed as a hotfix for AGU release.

### CODE REVIEW

**Comment by pkdash** [comment]
@hyi Can you review this small change soon?

**Comment by hyi** [comment]
@pkdash There are two test failures that need to be fixed.

**Comment by hyi** [comment]
@pkdash After you fix the two test failures, and as long as you make sure all instances of use_id have been changed to user_or_group_id pertaining to this url parameter change, a +1 from me to merge.

**Comment by pkdash** [comment]
@hyi Will be fixing the failing unit tests soon.

**Comment by pkdash** [comment]
@mjstealey Can you merge this and apply as a hotfix for AGU release?

**Pull request merged**
