### PR TITLE
fixed issue [#611] - make rating work again

### PR DESCRIPTION
**Pull request by hyi**
Fixed regression error with ratings and implemented new rating functionality as outlined in issue [#611]
@mauriel133 @ironfroggy could you give a quick review of the code?

### CODE REVIEW

**Comment by hyi** [comment]
@mjstealey @selimnairb I think this PR should be merged before manual migrations since otherwise we would not be able to test ratings social metadata migrations. It should have minimum impact for rebase if any due to code changes being isolated in two rating-only files.

**Comment by selimnairb** [comment]
@hyi This has been classified as fixing a regression.  Can you refer me to the commit just before the regression?  Thanks.

**Comment by hyi** [comment]
@selimnairb Here is the commit that caused the regression: https://github.com/hydroshare/hydroshare/commit/fe596cc36bd988aef2335c9055137f0566d1c397 - "Liked by 0" now reads "Be the first one to +1 this resource"

**Comment by selimnairb** [comment]
@hyi From my quick look this looks fine, however, I'm not very familiar with this part of the code.

**Comment by hyi** [comment]
If anybody wants to take a look at this code, please do so before noon today. Otherwise, I'd suggest to merge it into develop before migration dry-run this afternoon since this code change is needed to be able to verify rating data is migrated successfully or not. @mjstealey if we don't hear any objections by noon today, I'd suggest to merge it in. I have tested it pretty thoroughly during my migration test, I think it resolved the regression error and works as expected without breaking anything.

**Pull request merged**
