### PR TITLE
fixed issue [#1602]

### PR DESCRIPTION
**Pull request by hyi**
@pkdash Please give a quick review to this issue and see if you can +1. This needs to be merged for the next 1.8 release. I have also updated beta so that you can test downloading of two files with the same file name on beta now. This issue has been fixed based on my testing on beta.

### CODE REVIEW

**Comment by pkdash** [comment]
@hyi I did some testing on beta. The file that's not in the folder has now no download url so it is downloading a html file.

**Comment by hyi** [comment]
@pkdash Are you testing this resource https://beta.hydroshare.org/resource/30a20765b66f4bfeb05106322eeaca71/? I tried that and I can download both files inside and outside the test-demo folder. So that means at least url is not empty. How do you see the url from the user interface? I thought @mauriel133 implemented something that allows users to copy url, but I cannot find it. So the way I tested it out is to rename a file with the same file name as the file inside a folder, then I download the files inside and outside the folder which happen to have the same file name, and then examine the file content to make sure the correct file is downloaded. I just tested on beta and files with the same file name look to be downloaded correctly as expected. Can you test again to make sure this is the case? Another thing to check is to make sure you clear your browser cache to make sure it is in a clean state when you test it out.

**Comment by hyi** [comment]
@pkdash I can reproduce the issue you have with that old resource. However, it works as expected with this resource https://beta.hydroshare.org/resource/58b3415623cb40728799cd4c6cabe4c9/ which you can take a look and test it out. So can you create a new resource with that same file scenario and test it again to make sure it works with the new resource you created?

**Comment by pkdash** [comment]
@hyi It seems to work now. Thanks.

**Comment by pkdash** [comment]
+1

**Pull request merged**
