### PR TITLE
3024 encoding url path for file and folder

### PR DESCRIPTION
**Pull request by pkdash**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Create a resource. Create a folder with a space in folder name. Upload a file to the folder. Rename the file to have a space in the filename.
2. Right click on the folder and select 'Get File URL' option. Verify the folder url is property encoded. Copy the url and use it to download the folder. Verify the folder download was successful. 
3. Right click on the file and select 'Get File URL' option. Verify the file url is properly encoded. Copy the file url and use it to download the file. Verify the download of the file was successful.

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4852](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4852)

**Comment by devincowan** [comment]
@pkdash nice use of [parse.quote](https://docs.python.org/dev/library/urllib.parse.html#urllib.parse.quote).
I do see issues when attempting to unzip [as David mentioned](https://github.com/hydroshare/hydroshare/issues/3024#issuecomment-442138987):
> As an additional test case, here is a zip file provided by a user a while back that was a problem. [Filenames.zip](https://github.com/hydroshare/hydroshare/files/2621056/Filenames.zip) It contains several files with unicode character names. If I attempt to unzip in hydroShare today I get a folder with only one file, i.e. several of the files are not extracted.
> 
> Will the solution suggested resolve this.

But maybe we plan to address this with PR https://github.com/hydroshare/hydroshare/pull/4797 to fix issue https://github.com/hydroshare/hydroshare/issues/2538?

**Comment by pkdash** [comment]
@devincowan Thanks for testing for unzip. I will be looking into the unzip issue using the sample zip file.

**Comment by pkdash** [comment]
@devincowan and @dtarb Did some testing with the sample zip file (Filenames.zip). This zip contains files that have English language characters only in the filename. Still the irods '**ibun**' command  only extracts one file and doesn't report any error. I created another zip file containing a file that has non-english characters in its filename. The ibun command fails to unzip this zip file and throws an exception. The exception message is not that helpful. Since we can upload and download files with non-english character, irods seems to be fine handling unicode.  So it seems for some reason the '**ibun**' command doesn't like unicode filename. 

This is the error the **ibun** command generates when the zip file has files with non-english characters:

`"Error processing IRODS request: 3. stderr follows:\n\nb'remote addresses: 192.168.96.6 ERROR: bunUtil: opr error for /hydroshareZone/home/wwwHydroProxy/d2c579b1301e4796aecce9d0dfdb25a6/data/contents/0ec90d514492491badb702bce5af40a8, status = -806000 status = -806000 CAT_SQL_ERR\\n'")`

I am not sure how to proceed with this PR. I would suggest that we should create a separate issue for the ibun command and discuss the issue with someone from irods.

**Comment by dtarb** [comment]
@hyi may have some thoughts.  She worked with ibun quite a lot.

**Comment by devincowan** [comment]
@pkdash I'm in favor of making a separate issue for the ibun issues...

**Review by devincowan — APPROVED** [review]
thanks Pabitra!

**Review by sblack-usu — APPROVED** [review]
Confirmed these changes work with open with CUAHSI Jupyterhub

**Pull request merged**
