### PR TITLE
[#4269] - remove global namespacemanager and use default bindings on …

### PR DESCRIPTION
**Pull request by sblack-usu**
…the existing manager

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW DUPLICATED LINES DENSITY | 0.0 |
| NEW CODE SMELLS | 0 |
| NEW VULNERABILITIES | 0 |
| NEW BUGS | 0 |
| NEW SECURITY HOTSPOTS | 0 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4282](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4282)

**Review by pkdash — APPROVED** [review]
@sblack-usu  Thanks for fixing this bug. There seems to a pep8 issue. Once that is fixed, you can merge.

**Comment by sblack-usu** [comment]
@pkdash - please re-approve

**Review by hyi — APPROVED** [review]

**Review by cbcunc — APPROVED** [review]

**Review by alvacouch — COMMENTED** [review]
To the best of my knowledge this is a housekeeping change that simply makes the namespaces more clearly defined.

**Comment by sblack-usu** [comment]
This removes the global namespace manager and creates the bindings on the namespace manager provided with each RDF graph.  The issue it was resolving is that the model aggregation work introduced adding the resource as a namespace and was adding it to the global namespace manager.

**Pull request merged**
