### PR TITLE
Change from UNC addresses to RENCI addresses

### PR DESCRIPTION
**Pull request by alvacouch**
This changes the IP ranges for local requests to include just the RENCI addresses (/20) rather than all UNC addresses (/16). 
@sblack-usu @cbcunc If you want this now, we might have time for it.  Up to you. 

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4112](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4112)

**Comment by hydrocheck** [comment]
Rerunning SonarQube Analysis

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW CODE SMELLS | 3 |
| NEW DUPLICATED LINES DENSITY | 0.0 |
| NEW SECURITY HOTSPOTS | 0 |
| NEW BUGS | 0 |
| NEW VULNERABILITIES | 0 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4112](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4112)

**Comment by alvacouch** [comment]
@cbcunc base changed to develop. Please approve.

**Review by cbcunc — APPROVED** [review]

**Pull request merged**
