### PR TITLE
[#2758] patch imghdr to look exif jpeg type

### PR DESCRIPTION
**Pull request by sblack-usu**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Navigate to the edit page of a web app resource and open the resource specific tab and locate the Icon URL text box.  Place this link (https://avatars3.githubusercontent.com/u/8520008?s=200&v=4) into the textbox and click save.  Validate no errors occur and that the image is saved.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@zhiyuli Please review when you get a chance. I will email as well.

**Comment by sblack-usu** [comment]
Now part of https://github.com/hydroshare/hydroshare/pull/2889

**Pull request closed without merging**
