### PR TITLE
227-Manage Access: auto-complete text changed to "[Name] - [Email]"

### PR DESCRIPTION
**Pull request by mauriel133**
[#227] Manage Access: auto-complete text changed to "[Name] - [Email]"
[#201] Removed username from search fields since we should never display usernames

### CODE REVIEW

**Comment by dtarb** [comment]
See discussion on issues #319 and #292.  We decided to use Firstname Lastname, organization (username) as the identifier string in all places on this interface consistently and not display emails to avoid scraping of emails.

**Comment by mauriel133** [comment]
I removed email from search fields and the string now reads [First Name] [Last Name], [Organization] ([Username]). Test cases have been added accordingly for formatting.

**Comment by mauriel133** [comment]
I've included these changes in pull request [#165] that contains the work on the new resource edit page. I'm going to close this pull request and we can continue the discussion if necessary in the other thread.

**Comment by dtarb** [comment]
I just tested sandbox and did not see these changes.  Perhaps they are not staged there yet.

**Pull request closed without merging**
