### PR TITLE
[#3996] expand map clusters

### LINKED ISSUE #3996: Map clusters not expanding - Discover feature parity
I've found several instances where map cluster icons will not expand when clicked to show a marker for each individual resource. 

To replicate:
1. Search for "streamflow"
2. Navigate to eastern Tennessee (Blackoak Gap)
3. Notice that there is a cluster of two resources
4. Click on them and notice that nothing happens

image

The expected behavior is for the cluster to expand into individual markers.

### PR DESCRIPTION
**Pull request by devincowan**
Resolves #3996

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. You could create a few resources locally that overlap (exactly same point) spatially. Or, I found it easier to modify this line: https://github.com/hydroshare/hydroshare/blob/3996-map-clusters/hs_discover/src/components/Search.vue#L383
2. `axios.get('/discoverapi/'...` so that it points at `axios.get('https://www.hydroshare.org/discoverapi/'...`
3. Rebuild discover using `./local-build-discover.sh` or build all the containers using `./local-dev-first-start-only`
4. Navigate to discover, open the map, click on a cluster, continue to zoom until you get to a high zoom level
5. See that the overlapping points get "spiderified" instead of remaining unclickable
6. ~Open browser dev tools~
7. ~No longer see js console errors related to `Vue is not defined` and `chunk-vendors.js missing`~

### CODE REVIEW

**Comment by devincowan** [comment]
@Maurier I'm going to revert some of the changes in this PR so that we can "separate concerns" and address [Discover Build issues ](https://github.com/hydroshare/hydroshare/issues/4846) separately

**Comment by devincowan** [comment]
@Maurier this PR is ready for review. No rush by any means...

**Comment by Maurier** [comment]
@devincowan - The marker popups could use some content formatting. Perhaps we could put the coordinates in a new line below the title. Also, the title gets outlined automatically and makes the text hard to read.

image

**Comment by devincowan** [comment]
Thanks @Maurier, I made those adjustments. Redeployed to [beta](https://beta.hydroshare.org/search/)
image

**Review by Maurier — APPROVED** [review]
Looks good.

**Pull request merged**
