### PR TITLE
2431 hotfix improve recovery for model instance and model program

### PR DESCRIPTION
**Pull request by alvacouch**
@aphelionz @dtarb Changes to ingest_irods_files recover missing iRODS files for model instance and model program. Also includes:

- comprehensive resource testing script `./hsctl managepy check_resource` that supersedes `debug_resource` for sanity checks.
- comprehensive repair script  `./hsctl managepy repair_resource` that supersedes `ingest_irods_files`, `check_irods_files`, `fix_missing_logical_files`, ...

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by alvacouch** [comment]
@aphelionz Changed test_resource/TestResource to check_resource/CheckResource to avoid nose mistakenly picking up the test 👎

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
