### PR TITLE
fixed iRODS add file bug #3776

### PR DESCRIPTION
**Pull request by hyi**
### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
This fixes the regression issue #3776.

### CODE REVIEW

**Comment by hyi** [comment]
@sblack-usu This fixes a regression bug for adding files from iRODS discovered by @dtarb . It should go into the next release if possible. Can you do a quick review for this very small PR?

**Comment by hyi** [comment]
@sblack-usu I did a whole code base change and these are the only two places that ```string.split``` is used. I remember I made such change before as well, but don't remember where I made it, but this time I did a thorough change and made sure I caught all occurrences.

**Comment by sblack-usu** [comment]
this is deployed to beta, please verify @hyi

**Comment by dtarb** [comment]
I tested and am able to load a file from Cyverse to beta that fails on www.  Thanks.

**Pull request merged**
