### PR TITLE
Simple fix to issue #1440

### PR DESCRIPTION
**Pull request by mohamedmorsy**
@pkdash @mjstealey this is a simple fix to issue #1440. Hope we could merge it to release 1.7.5

### CODE REVIEW

**Comment by pkdash** [comment]
+1

**Comment by pkdash** [comment]
@mohamedmorsy Do you think this needs to be applied as a hotfix to 1.7.5? Or can we wait until the next release?

**Comment by mohamedmorsy** [comment]
@pkdash if this is the only hotfix for this release so it can wait until the next release.

**Comment by mjstealey** [comment]
@mohamedmorsy @pkdash - looked like a one liner and has been manually added to www.
Please verify

**Comment by mohamedmorsy** [comment]
@mjstealey @pkdash Now it looks good to me on www

**Pull request merged**
