### PR TITLE
[#4309] - use view authorization for extra_metadata GET

### LINKED ISSUE #4309: API endpoint /scimeta/custom currently requires edit permissions to GET
**Description of the bug**
[update_key_value_metadata_public](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/__init__.py#L390) handles both the POST and GET.  The authorization scope for POST is correct and requires edit permissions.  The authorization scope for GET also requires edit permissions but it should only require view permissions.

Steps to reproduce the bug:
1. curl https://www.hydroshare.org/hsapi/resource/0825db8e3bed4b18b77f214b5630f3d7/scimeta/custom/
2. Observe a 403 for viewing additional metadata on a public resource.

**Expected behavior**
GET /scimeta/custom should require view permissions, not edit permissions.

### PR DESCRIPTION
**Pull request by sblack-usu**
fixes #4309 

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1.  GET `/hsapi/resource/{id}/scimeta/custom/` without authentication on a public resource

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|
| NEW BUGS | 0 |
| NEW DUPLICATED LINES DENSITY | 0.0 |
| NEW SECURITY HOTSPOTS | 0 |
| NEW VULNERABILITIES | 0 |
| NEW CODE SMELLS | 0 |

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4310](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4310)

**Comment by hyi** [comment]
@sblack-usu Looks good. There is a failing test which should be easy to fix. I'll approve the PR after you fix the test.

**Comment by sblack-usu** [comment]
> @sblack-usu Looks good. There is a failing test which should be easy to fix. I'll approve the PR after you fix the test.

got it, the resource in the test should be public, fixed.

**Comment by sblack-usu** [comment]
retest this, please

**Comment by sblack-usu** [comment]
@hyi - tests are passing now, it was the HIS test that failed before.

**Review by hyi — APPROVED** [review]

**Pull request merged**
