### PR TITLE
1657 cohesion

### PR DESCRIPTION
**Pull request by alvacouch**
@hyi @pkdash @aphelionz 
This is a preliminary PR that solves issues raised in review of current PR #1687. While #1687 changes the design of resource files, this PR moves iRODS code for file management into a single place, **`hs_core/irods.py`**, from which it is used in several contexts. 

Particularly, the abstract models **`irods.py:ResourceIRODSMixin`** and **`irods.py:ResourceFileIRODSMixin`** provide the iRODs methods needed by `AbstractResource` and `ResourceFile`, respectively. Thus, this code is found in one place, and is more easily maintainable in response to changes in iRODS, etc. 

This PR is built upon #1687 and should be merged after #1687 is merged. In this PR, I move the iRODS file management code from `hs_core/views/utils.py` into these classes, depending upon whether the code affects the whole file hierarchy for a resource or just one file. I didn't do all of them in one PR. In future PRs I will also move relevant code from `hs_core/hydroshare/utils.py` into the appropriate classes. 

Rate of code churn discourages me from combining these PRs into one larger one. I would be rebasing all of the time.

### CODE REVIEW

**Comment by pkdash** [comment]
This should be reviewed only after PR #1687 gets merged so that we have less changes to review.

**Comment by alvacouch** [comment]
@pkdash It is mostly provided so you can see how issues in PR #1687 are handled. See hs_core/irods.py

**Comment by pkdash** [comment]
@alvacouch Sounds good.

**Comment by alvacouch** [comment]
I am closing this without a merge to do a complete redesign based upon discussion in PR #1687. Will issue PR for redesigned subsystem.

**Pull request closed without merging**
