### PR TITLE
1566 quota

### PR DESCRIPTION
**Pull request by hyi**
@phuongdm @alvacouch This PR implements quota real time update in Django to work with iRODS backend quota update rules. The major updates include:

- added an enforce_quota field/checkbox/flag with a default value of False, but can be changed to True when we are ready to enforce quota from the admin panel. 
- The quota enforcement code honors this enforce_quota flag and since it is set to False, quota is not enforced but only monitored and reported.
- update quota usage in Django in a celery task triggered in one minute after a resource is created or deleted, or files are added to or deleted from resources. This delay of 1 minute is to accommodate the iRODS rule being executed before the async celery task runs. The celery task checks the iRODS user type AVU on the proxy user set up by iRODS quota update rules and aggregates quota usage in HydroShare data zone and user zone, and update Django database to reflect the updated quota for the user. 
- The quota usage report is still on user profile page and when the user logs in with the message being shown as configured in the admin panel. So if we don't want to show quota report message, we can configure it from admin panel by setting the message empty or setting it as a general quota message. I have not put the quota message on my resources page yet, but will do so after @aphelionz or @phuongdm or @cbcunc merge master branch back to develop branch since there are a lot of code changes on my resources page that are in master but not in develop yet, and I want to do this on the latest my resources page code to avoid extra work needed for resolving merging conflicts later.
- I did update the unit tests to reflect the quota update changes as done in this PR and they all passed in my local dev env except for test_update_quota_usage and test update quota usage in federation zone due to an iRODS permission issue. Specifically, in the test environment where iRODS quota update rules are not present and hooked up, I wrote test to add quota size AVU on the proxy user in the same way as what the iRODS rules would do, then test to make sure the size is updated in Django database as expected. However, I got CAT_INSUFFICIENT_PRIVILEGE_LEVEL error when doing so, i.e., run ```imeta set -u``` command as the proxy iRODS user although it can be done successfully if running it as rods service user. I have emailed irods user list to ask whether there is a way for modifying permission to allow HydroShare proxy irods user to run this successfully. @phuongdm @mjstealey Let me know if you have suggestions/ideas on this. In the real test environment, @phuongdm will set up his iRODS micro-services and rules and run it as rods service user, so this permission issue will not affect us in the real test or production environment, it is only an issue in the unit test environment where the new micro-services and rules are not present and set up.

I am creating this PR to open up code review and discussion now so that I can continue to refine my code as needed. @alvacouch please do code review when you have time so that I can address your comments earlier in the process, and @phuongdm please pull my branch 1566-quota to do integration test on a cuahsi server where you already have iRODS backend micro-services and rules set up.

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hyi** [comment]
@phuongdm @alvacouch iRODS folks have confirmed that setting user type AVUs are only available for rods admin users for security purposes, so a regular iRODS proxy user cannot do that. I have used the admin iRODS users set up in local iRODS federated docker containers to write test for updating quota usage in Django based on user type AVUs set on iRODS proxy user in iRODS data or user zone, and aggregate the quota usage in Django by a celery task and update Django database accordingly. The tests all have passed in my local development environment where local irods docker containers are used, so I am confident the code should work for integration testing.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
@hyi Phuong and I are testing this locally - it appears the update quota usage celery task is not firing?

Phuong sent you an email with details, please let us know if there are any additional configuration steps we need to do, perhaps a celery config. 

Thank you!

**Comment by hyi** [comment]
@phuongdm @aphelionz I have just send you both an email with detailed update on the integration testing issues. The problem is not caused by celery task, but caused by an inconsistency of AVU attribute naming between Django and iRODS. Although that has been fixed, there are a couple of further issues being identified which may require us to change where we put user quota usage AVUs. See my email for details.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hyi** [comment]
@alvacouch I have resolved the last issue and everything appears to be working as expected now based on my testing on cuahsi servers with real time quota update. So the code is ready for your review now in order to merge it for the next release.

**Comment by hyi** [comment]
@aphelionz I see @alvacouch is actively working on discovery, so may be short in time to do code review for this PR. As a result, I assigned you to code review this PR as well. Please coordinate with @alvacouch to code review this for the next deployment. I'll merge it once one of you approve this PR. P.S, the current 1 failing check was not due to any work in this PR but strangely bailed out, so I'll wait for recaptcha PR being merged before rebasing with develop to trigger the build again. In any case, this PR is ready for review since it has passed integration testing with iRODS real time microservices to be deployed for the next release.

**Comment by aphelionz** [comment]
@hyi We are not in a hurry to release. Let's take the time we need to get this approved properly for 1.15

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hyi** [comment]
@alvacouch @aphelionz This PR passed all checks after merging with develop to trigger a Jenkin rebuild. It also passed integration testing with iRODS real time quota update, so it is ready for your review.

**Comment by phuongdm** [comment]
@hyi 

I’ve deployed this branch on the beta, but my profile page didn’t show my usage and also didn't have any quota information.

`imeta ls -C /hydrotestZone/home/betaDataProxy/bags pdoan-usage` showed the correct number. 

is there any step to enable quota message on the profile page?

**Comment by hyi** [comment]
Have worked out this with @phuongdm. It is a configuration issue from admin panel, not related to code. We just need to expose the quota message again now that real time quota update is implemented instead of hiding the quota message reporting as we have been doing since initial quota deployment.

**Comment by phuongdm** [comment]
+1

**Comment by aphelionz** [comment]
@phuongdm please formally approve :)

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Pull request merged**
