### PR TITLE
716 access control permission fix

### PR DESCRIPTION
**Pull request by pkdash**
With these changes:

1. Resource non-owners can't downgrade privilege originally granted by someone else.
2. Most recent granted privilege for a resource for a given user always becomes the highest privilege for that user for that resource.
3. Inactive users can't be granted resource access permission.

### CODE REVIEW

**Comment by pkdash** [comment]
@alvacouch Please review.

**Comment by hydrobuild** [comment]
Can one of the admins verify this patch?

**Comment by pkdash** [comment]
@hyi Please review.

**Comment by hyi** [comment]
+1

**Pull request merged**
