### PR TITLE
Adding sitemap.xml support to Hydroshare

### PR DESCRIPTION
**Pull request by aphelionz**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Check out the `sitemap.xml` branch
2. Visit your-dev-url/sitemap.xml and you should see an index pointing to two sub sitemaps, sitemap-pages.xml and sitemap-resources.xml

### CODE REVIEW

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
retest this, please

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
retest this, please

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
retest this, please

**Comment by hydrobuild** [comment]
Build finished.

**Comment by hydrobuild** [comment]
Build finished.

**Comment by aphelionz** [comment]
I dont think an automated test is necessary for this...

**Pull request merged**
