### PR TITLE
Adding hydroshare-config.yaml settings to local_settings.py

### PR DESCRIPTION
**Pull request by aphelionz**
For issue #2721 

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [x] Automated Testing

- [x] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Run `./hsctl managepy shell`
2. Follow the code below

```
>>> from hydroshare import local_settings
>>> local_settings.EXTERNAL_CONFIG
{'SENDFILE_IRODS_USER': 'irods', ... ,  'USE_HTTP_AUTH': False}
```

### CODE REVIEW

**Comment by sblack-usu** [comment]
I'm not sure I'm following why we're doing this.  I get that you want to consolidate, but this commit doesn't actually do anything with the external config.

**Comment by aphelionz** [comment]
Right, it's just a way to consolidate and utilize the yaml config inside the django app, if need be. This was requested by @alvacouch and @phuongdm while they were working on the large file download. See the attached issue for more context. #2721

**Comment by sblack-usu** [comment]
so the large file download configuration will be updated to look at settings instead of hydroshare-config?

**Comment by aphelionz** [comment]
I never said that! I think this is just a feature request that came up as a result of that work.

**Comment by sblack-usu** [comment]
I'm not wild about making code changes that aren't used.  I'd like to have a clear use case for this or specific plans to use it in the future.  

Right now, it's just extra code that may or may not be used in the future.

**Review by sblack-usu — DISMISSED** [review]

**Comment by aphelionz** [comment]
@sblack-usu I added some jenkins tests to insure the settings import is happening. Take one more look and approve when ready

**Review by sblack-usu — APPROVED** [review]

**Pull request closed without merging**
