### PR TITLE
Redirect to resource after login

### PR DESCRIPTION
**Pull request by pkdash**
### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Create a resource. Make sure the resource is not public. Copy the url for the resource landing page then logout. Paste the resource url for the resource that you created. It should take you to the login screen. Now when you login, it should take you to the resource landing page as per the resource url you used.

### CODE REVIEW

**Comment by pkdash** [comment]
@cuahsimarko This PR should address issue #2556. I did some testing with composite resource only. Did not get time to test for other resource types. Hope it works for other resource types.

**Comment by pkdash** [comment]
Will fix the pep8 issue later today.

**Comment by zhiyuli** [comment]
@pkdash @cuahsimarko 
Tested and confirmed locally the "Positive Test Case" was working as expected

**Comment by pkdash** [comment]
@zhiyuli Thanks for testing.

**Comment by cuahsimarko** [comment]
@Lizabrazil can you give a quick thumbs up, after running through a "Postitive Test Case" from a UX perspective?

**Comment by cuahsimarko** [comment]
code approved can merge as soon as Liza gives a UX thumbs up

**Comment by Lizabrazil** [comment]
looks good, thanks

**Pull request merged**
