### PR TITLE
[#2037][Hotfix] Pre-deploy issues

### PR DESCRIPTION
**Pull request by mauriel133**
This Hotfix PR addresses the following issues found during pre-deploy checklist:

- [x] Found remains of merge conflicts
image
- [x] Quota holder text is unreadable
image
- [x] Change quota holder button style
image
- [x] Use quota holder to render manage access interface state. In the example below, the remove buttons should be disabled for the quota holder item.
image
- [x] Unable to unshare resource with dynamically added group item
image
- [x] In authors table, dragging indicator is cut off
image
- [x] Refactor of script inside credits.html file

### CODE REVIEW

**Comment by mauriel133** [comment]
Here are the UI changes in this PR:
image

image

image

**Comment by hyi** [comment]
@mauriel133 Thanks for fixing the merge conflict issue and for styling the quota holder interface. The change looks good to me. +1 from me.

**Comment by pkdash** [comment]
@mauriel133 Can you let @mjstealey also know that this hot fix has been applied to release candidate so that he can update beta as well as update develop branch?

**Comment by mauriel133** [comment]
Will do. Thanks!

**Pull request merged**
